### ISSUE TITLE
Memory Test

### ISSUE THREAD

**Issue by twhtanghk** [espruino/Espruino#1008]
Any hints to check memory usage for function call as below:
```
a = function() { console.log(process.memory()); a(); }
```
At last, assert failed is shown below
```
ASSERT(jsvGetLocks(var) < 15) FAILED AT src/jsvar.c:556
```

**Comment by gfwilliams** [comment]
What device are you running this on? I presume it's one of your own builds as assertions are built in?

The stack gets checked on recursion and usually in these infinite recursion cases an error gets thrown when the stack runs out (which is before the lock count rises too high).

To measure static memory usage use `E.getSizeOf(a)` or for dynamic:

```
a = function() { console.log(process.memory().usage-mem); }
var mem = process.memory().usage;
mem = process.memory().usage; // do it again, since storing the memory usage uses up memory
a();
```
