### ISSUE TITLE
Puck: Can't remove magnetometer listener

### ISSUE THREAD

**Issue by rsmeral** [espruino/Espruino#1009]
After calling `Puck.on("mag", listener)`, there currently seems to be no way to remove the magnetometer event listener.
The `Puck` class would ideally implement the standard `Object.removeListener` for the `"mag"` event.

**Comment by gfwilliams** [comment]
Argh. Thanks - I'll make sure that's added. This might apply to the NRF class too

**Comment by gfwilliams** [comment]
This actually works - I can only assume it wasn't tested?

Looks like the issue is maybe just that tab complete doesn't autocomplete with removeListener?

**Comment by gfwilliams** [comment]
No problem. It alerted me to the issue with tab complete anyway :)
