### ISSUE TITLE
raw esp8266-12e - how to point Waveform to the analog pin

### ISSUE THREAD

**Issue by mrbar42** [espruino/Espruino#1015]
Hi,

I use esp8266-12e boards directly with espruino v1.89 (no devboard).
As i read in many other [issues](https://github.com/espruino/Espruino/issues/929) and forum discussions,
analogRead() ignores the pin and uses the only available one - that's working as expected.
But does Waveform acts the same?
I couldn't get any data defining any pin number to Waveform.

In a more general fashion i wonder if it would be helpful to add the pins to the `ESP8266` module similar to `NodeMCU` making usage more clear and explicit:
```js
var esp8266 = require('ESP8266');
esp8266.A0
esp8266.D0
```

**Comment by MaBecker** [comment]
for PWM check #914

**Comment by gfwilliams** [comment]
I'm afraid waveform isn't really supported on ESP8266 at the moment.

As far as I know, ESP8266 Waveform doesn't properly use interrupts anyway (so it gets stalled by JS execution). As a result, even if this could be made to work, you'd still be a very glitchy and unreliable waveform read out of it.

**Comment by mrbar42** [comment]
Then there's no issue here I guess.

Thanks.
