### ISSUE TITLE
Truthiness of Uint16Array objects is wrong

### ISSUE THREAD

**Issue by stokebrain** [espruino/Espruino#1030]
V8 engine:
```javascript
var a = new Uint16Array([1, 2])
!!a
> true
```
espruino:
```javascript
var a = new Uint16Array([1, 2])
!!a
> false
```

This causes some significant issues, for example, `var a = myUintArray || 0`, a will be `0` when `myUintArray` contains the data I want.

**Comment by gfwilliams** [comment]
Ouch, interesting - thanks! I'll try and see what's up.

**Comment by gfwilliams** [comment]
Fixed now - should be in the 1v92 release :)
