### ISSUE TITLE
pins csv for nrf52-DK

### ISSUE THREAD

**Issue by OwenBrotherwood** [espruino/Espruino#1036]
https://github.com/espruino/Espruino/tree/master/boards/pins 
Would you like / need a csv for nrf52-DK?
Not sure if needed as such but could be nice.

**Comment by gfwilliams** [comment]
Thanks - it's not really needed though. On nRF52 most of the peripherals can be on *any* pins - there are one or two static, but I've hard-coded those in the BOARD.py file.
