### ISSUE TITLE
Accessing Serial Ports

### ISSUE THREAD

**Issue by ganehag** [espruino/Espruino#105]
Enumeration of serial ports is currently done when Espruino is compiled. For environments with unknown static "ttySX" and dynamic "ttyUSBX, ttyACMX". We need a way to list and connect to devices at runtime. For example like how `node-serialport` does it:

    var SerialPort = require("serialport").SerialPort
    var serialPort = new SerialPort("/dev/tty-usbserial1", {
      baudrate: 57600
    });

This solution is just a suggestion. Espruino already has its own `Serial` object. Or should we use `require` for all serial ports as well?

**Comment by gfwilliams** [comment]
Closing, as this works now. Use `Serial1.setup({path:"..."});`
