### ISSUE TITLE
nRF5x: Only perform Write With Response where it's accepted

### ISSUE THREAD

**Issue by gfwilliams** [espruino/Espruino#1059]
http://forum.espruino.com/conversations/298621/#comment13463259

In BLE_GATTC_EVT_CHAR_DISC_RSP, it's in p_chr->char_props.write_wo_resp / write

Then we need to write that to the JsVar for the characteristic, and then read that when we do a write in order to do the correct thing.

**Comment by gfwilliams** [comment]
This might be fixed with https://github.com/espruino/Espruino/commit/766a577e3f5da127ce4815544a31cb7562dfd96c - needs testing on hardware that won't allow write with response

**Comment by Whizzard** [comment]
confirmed to work by two people in http://forum.espruino.com/conversations/298621/?offset=25

**Comment by gfwilliams** [comment]
Great - thanks! Fixed then :)
