### ISSUE TITLE
E.setBootCode() save 8 bytes  on ESPs

### ISSUE THREAD

**Issue by MaBecker** [espruino/Espruino#1068]
This should erase saved code, but saves 8 byte.

````
E.setBootCode("")
Erasing Flash.....
Writing...
Compressed 25600 bytes to 8
Checking...
Done!

.....

Loading 8 bytes from flash...

`````

@gfwilliams, please label ESP8266

**Comment by gfwilliams** [comment]
This applies to all boards I think, but I'm pretty sure it's fine. It's just the amount of data referring to the header.

Personally I'd close this.

**Comment by MaBecker** [comment]
Yes - same for Pico
