### ISSUE TITLE
docs update?

### ISSUE THREAD

**Issue by jgtaylor** [espruino/Espruino#1084]
So I found this [stuff about GPIOs](https://github.com/espruino/Espruino/wiki/Architecture-of-GPIO), and decided to make a little hack on my wemos D1-mini so i can call d0-8 and a0, rather than the D0-15. I tried this:
```javascript
var d4 = new Pin(2)
```
and it returns:
```
WARNING: The Pin() constructor is deprecated. Please use `D2`, or NodeMCU.Dx instead
```

is it safe to say that:
```javascript
var d4 = D2;
```
is the best way do this kind of 'remapping'? Do the docs need changing?

**Comment by gfwilliams** [comment]
Yes, absolutely - `d4 = D2` is fine. It could be worth just defining:

```
var Wemos = {
  D4: D2,
 ...
};
```

Those docs were written by Neil a long time ago *as he went about trying to understand the Espruino codebase* - for some reason he didn't like the idea of writing stuff in the EspruinoDocs repo where everything else is. The wiki pages haven't been maintained ages so I think it's a very good idea to ignore them.

If you need normal docs take a look at Espruino.com, and if you need low-level docs, check out the code - I put quite a lot of documentation about internals in there in the hope that it actually stays up to date.

I'll put a note in all the Wiki pages and close this.
