### ISSUE TITLE
Compatibility with Tessel/Johnny-five etc

### ISSUE THREAD

**Issue by gfwilliams** [espruino/Espruino#11]
Tim from technical.io has come up with this proposal http://hardwarejs.io/ - but at the moment it's a big departure from Espruino's implementation (which already has a bunch of code written for it).

As a starting point (and to be compatible with J5-type arrangements where you can have more than one board) we'll want to have a 'hardware' object with all the existing API calls in. Hopefully this could be the root namespace, so you can still do ```digitalWrite(LED1,1)``` but also ```hardware.digitalWrite(hardware.LED1,1)``` in order to be compatible...

**Comment by the1laz** [comment]
I was just looking into Johnny five and stumbled across this. Would this be better off as a separate installable module rather than a complication in the firmware? It doesn't sound feasible to reshape espruino around hardwarejs, and it sounds like it could instead be done as a pure js abstraction. If so, would it be good to have a separate "module wishlist" somewhere?

**Comment by gfwilliams** [comment]
Yes, that's a good plan... Perhaps I could set a tag up in EspruinoDocs for modules that would be good to implement.

Personally I'd like to dissuade people from using extra frameworks on top of Espruino though. It'll use up a bunch of extra RAM, and I think that if someone is going to try and copy/paste code that was meant for a device with >32MB RAM on Espruino, they're going to be disappointed.

In a way it's better that they find the differences out sooner rather than later :)

**Comment by the1laz** [comment]
Yeah, good point. The nrf24l01+ driver for node I was just looking at requires eight other libraries (not to mention the dependencies of those libraries!). I suppose most libraries referencing specific hardware won't be suitable for the espruino regardless of interface.

**Comment by gfwilliams** [comment]
> The nrf24l01+ driver for node I was just looking at requires eight other libraries

Sadly the way most people write code for node.js (depending on libraries wherever possible) isn't really a good idea on Espruino (or IMO on small microcontrollers).

A good optimising compiler usually saves you, and to a certain extent a really good minifier that could throw away all the unused stuff that gets `require`d would help - but then you're basically pre-compiling your code and you're not really gaining anything over what you'd get with C/C++.

**Comment by gfwilliams** [comment]
Closing this - nobody seems particularly bothered (and there's now smartjs.io, iot.js and TouchDevelop to add to that list), and *way* more people (in fact pretty much all users) would get upset if Espruino's API changed now.

Potentially a wrapper layer could be written as a module, but any potential issues for that should go in: https://github.com/espruino/EspruinoDocs
