### ISSUE TITLE
On the issue of TAB_COMPLETE 

### ISSUE THREAD

**Issue by lancernet** [espruino/Espruino#1124]
TAB_COMPLETE can not work in Pin object, when I use D4., And then press the tab key, the options appear when the number of function options, this time what the problem, someone can tell me what

**Comment by gfwilliams** [comment]
Yes, this is because pins are handled with a separate piece of code - they're not actually stored in the symbol table. It's because digitalWrite/etc is also able to take strings that could define pins, and I don't want to duplicate the code that handles them.
