### ISSUE TITLE
A few questions on the C library for Espruino

### ISSUE THREAD

**Issue by gappi92** [espruino/Espruino#1135]
Hello, I'm trying to write my library on C for STM32 MCUs Peripherals so that I can put it in the Espruino/libs folder about In the process of writing, several questions appeared. Help Me Please with it:

**1) What is difference between**
What do _"generate"_ and _"generator_full"_ param in JSON function description?
This article does not answer this question:
[JSWrapper processing](https://github.com/espruino/Espruino/wiki/JSWrapper-processing)

**2)  As inside a function that has a type _"method"_, get data from the parent object.**
For example if we have a _"function ()"_ in the _"class"_ and we previously created an object of this class using the constructor. The constructor created the _"id"_ parameter in the object.
How do we get the value of the parameter in the parent object in the C function?
```
pin1 = new PIN(); //Create object and add parameter "id" in constructor
pin1.getId(); //How in C get id?
```
By selection, I realized that I should write this:
```
JsVar * jswrap_class_function (JsVar * parent, var1, var2, ...)
{
  JsVar * jsVar_id;
  // Get param
  JsVar_id = jsvObjectGetChild (parent, "id", 0);
}
```

But why is the parent first? This syntax is described somewhere?

**3)  Having written a function with many parameters of 6 pieces, I noticed that some parameters are incorrect.** 
JS code:
`pin1.write(var1, var2, var3, var4, var5, var6); `
C code
`var6 = read in C function not correct!`
Why this can happen, are there any restrictions on the number of parameters of the function?

**4) How delete object from C code?**
The documentation describes how to correctly create an object using the jspNewObject () or the jsvNewWithFlags(JSV_OBJECT);
Is it possible to correctly delete an object from the C function - to create a destructor of an object that was created earlier?
like
```
pin1 = new PIN()
pin1.delete();
```

In the constructor function, I save a reference to an object in a static array in the C library. Therefore, when deleting an object, I need to clean the corresponding cell in the array.

```
typedef struct
{
  mySuperStruct MyStruct;
  JsVar* parentPtr;
} EspruinoStruct;
EspruinoStruct structArr[5];
```
Is it possible to correctly delete an parent object from the C function - to create a destructor of an object that was created earlier?

**Comment by gfwilliams** [comment]
If this for an official Espruino board, or some other STM32 device?

> "generate" and "generator_full" 

generate just calls a function, but generate_full will create a function for you with the text you provided

> As inside a function that has a type "method", get data from the parent object.

it's as you said.

> But why is the parent first? This syntax is described somewhere?

It just is (the same thing happens internally in most object oriented languages I think). I don't believe it is documented

> 3) Having written a function with many parameters of 6 pieces, I noticed that some parameters are incorrect.

You only get 5 parameters max. I'm surprised there aren't warnings generated from build_jswrapper.py though

> 4) How delete object from C code?

It'll be deleted when it's unreferenced and unlocked. There is no way to automatically call a destructor function at the moment.
