### ISSUE TITLE
E.flashFatFS Documentation

### ISSUE THREAD

**Issue by wilberforce** [espruino/Espruino#1145]
http://www.espruino.com/Reference#l_E_flashFatFS

Is there a way to label this as ESP32 only to avoid confusion?

The sample needs to be corrected as the addresses don't match, and the three back ticks don't work in this situation.

Can we reword this globally?
Note: This is only available in not devices with low flash memory

Perhaps:
Note: Not available in devices with flow flash memory

**Comment by gfwilliams** [comment]
Sorted.
