### ISSUE TITLE
Bad Response on Serial in

### ISSUE THREAD

**Issue by denzelwamburu** [espruino/Espruino#1157]
Am using [Sparkfun thing](https://www.sparkfun.com/products/13231), and i successfully flashed the firmware (v1.92), also i've followed all steps successfully. Though when i try to serial in, the response am getting is not even human readable. Changing the baud rate really doesn't help.
What could be the issue?
![screen shot 2017-05-02 at 11 59 32 am](https://cloud.githubusercontent.com/assets/6532631/25611262/1ed5e3c2-2f2f-11e7-8793-03c79576bcba.png)

**Comment by gfwilliams** [comment]
Please can you ask on the Espruino forums for ESP8266? http://forum.espruino.com/microcosms/925/

This kind of problem seems super-common.

**Comment by denzelwamburu** [comment]
Okay. Thanks
