### ISSUE TITLE
seed Math.random() during boot

### ISSUE THREAD

**Issue by drandreas** [espruino/Espruino#1166]
I've noticed that all my Pucks produce the same sequence of random numbers. I think the RNG is not properly seeded during boot.
```
Connected
>
>Math.random();
=0.93255273901
>Math.random();
=0.70772355874
>Math.random();
=0.25562629208
>Math.random();
=0.68512640366
>Math.random();
=0.65661093343
>
Disconnected
---> Hardware Reset <---
Connected
>
>Math.random();
=0.93255273901
>Math.random();
=0.70772355874
>Math.random();
=0.25562629208
>Math.random();
=0.68512640366
>Math.random();
=0.65661093343
>Math.random();
=0.43274184848
```

**Comment by drandreas** [comment]
`E.srand(v)` I've no idea why I haven't found it in the first place....

**Comment by gfwilliams** [comment]
Thanks - sorry for the delay - I was on holiday last week.

I'll reopen this as I'd like to properly seed the RNG on boot anyway. It's what I do on other platforms.
