### ISSUE TITLE
Support socket.setEncoding(null) for reading binary data

### ISSUE THREAD

**Issue by rikte88** [espruino/Espruino#1196]
Currently there is not support for reading binary data from sockets. This makes uploading binary files to flash difficult. Please consider adding readablestream.setEncoding(), please see https://nodejs.org/api/net.html#net_socket_setencoding_encoding.

**Comment by gfwilliams** [comment]
Thanks - that's a good idea. Although you can probably push the string directly into `flash.write` or whatever you're using?

If you do need to convert a string to an array quickly, you can use the `E.toUint8Array` function: http://www.espruino.com/Reference#l_E_toUint8Array

Which is able to convert the data pretty quickly and efficiently.
