### ISSUE TITLE
length of views on typed array wrong

### ISSUE THREAD

**Issue by drandreas** [espruino/Espruino#1204]
If I create a view with an offset on a typed array. I'd expect to obtain a view with a length of `m.length - offset`. Espruino however prints 32.
```
var m = new Uint8Array(32);
var n = new Uint8Array(m.buffer, 16);
console.log(n.length);
```
Is this intended behaviour?

**Comment by wilberforce** [comment]
@drandreas 

When I run the code in  chrome - it says 16 - so looks like a bug!
