### ISSUE TITLE
Update formatFs docs

### ISSUE THREAD

**Issue by wilberforce** [espruino/Espruino#1230]
Update this 

http://www.espruino.com/Reference#l_E_flashFatFS

Update docs to use try/catch as per http://www.espruino.com/ESP32

As now error is thrown on Unformatted filesystem.

**Comment by wilberforce** [comment]
https://github.com/espruino/Espruino/blob/8aae321cd880fa98d862416915a6e1c9c9dea458/libs/filesystem/jswrap_file.c#L606

```
fs=require("fs");
if ( typeof(fs.readdirSync())==="undefined" ) {
  console.log("Formatting FS");
  E.flashFatFS({format:true});
}
```

To become

```
try {
  fs.readdirSync();
 } catch (e) { //'Uncaught Error: Unable to mount media : NO_FILESYSTEM'
  console.log('Formatting FS - only need to do once');
  E.flashFatFS({ format: true });
}
```

**Comment by gfwilliams** [comment]
Do you want me to do that and close this issue then?

**Comment by wilberforce** [comment]
Thanks! - If you can be bothered!

I documented what needs to be done on the ipad, as it's hard to edit code on that, let a alone check it compiles!

Otherwise I'll do it sometime.

**Comment by wilberforce** [comment]
Thanks!
