### ISSUE TITLE
UDP support for WIZnet

### ISSUE THREAD

**Issue by gfwilliams** [espruino/Espruino#1233]
It should be possible to add UDP support for WIZnet now, after https://github.com/espruino/Espruino/pull/1198

**Comment by opichals** [comment]
Perhaps can be closed now?
 commit https://github.com/espruino/Espruino/commit/5ed55d91d227eca1a22429dc18a0f81e5c47010a

**Comment by gfwilliams** [comment]
Yes, totally - thanks!
