### ISSUE TITLE
CoAP - Constrained Application Protocol over UDP

### ISSUE THREAD

**Issue by MaBecker** [espruino/Espruino#1249]
As UDP is available we can plan to implement [CoAP](https://en.wikipedia.org/wiki/Constrained_Application_Protocol) as another service layer for M2M communication.

Got touched by CoAP as watching video number  [144](https://www.youtube.com/watch?v=pfG8uEDZj5g) by Andreas Spiess

First question:     

    Implementation in C or JS,  for both lots of sample are available on github

Any comment, suggestion or ideas are helpful

**Comment by gfwilliams** [comment]
Personally I'd say use JS. It'll be a lot faster to iterate/develop, and we've already used it for things like MQTT and Websockets - I'm not sure there are huge reasons why CoAP should be significantly different?

**Comment by jaimejim** [comment]
Hi, I'd be interested on having CoAP on Espruino too. Has anyone moved forward on this already?
There are multiple CoAP implementations available, JS too.

http://coap.technology/impls.html

**Comment by bartmichu** [comment]
There is a lot of talk about CoAP in context of Ikea Tradfri system. How cool would that be if we could talk with these devices via Espruino? One thing to keep in mind is that it would also require DTLS implementation.

**Comment by MaBecker** [comment]
there is no interest - reopen it needed
