### ISSUE TITLE
ERROR:Connect failed (err113) Uncaught InternalError: Unable to create socket

### ISSUE THREAD

**Issue by wangnuannuan** [espruino/Espruino#1254]
a mqtt client implementation ,use the esp32
var ssid="AndrewSun";
var password="fanxu123456789";

var wifi=require('Wifi');
var server='115.156.218.4';

var options={
    client_id : "random",
    keep_alive: 60,
    port: 1883,
    clean_session: true,
    username: "username",
    password: "password",
    protocol_name: "MQTT",
    protocol_level: 4,
};

var mqtt = require('MQTT').create(server,options);

mqtt.on('connected', function() {
    console.log("MQTT connected");
    mqtt.subscribe("test");
});

mqtt.on('publish', function (pub) {
  console.log("topic: "+pub.topic);
  console.log("message: "+pub.message);
});

wifi.connect(ssid, {password: password}, function() {
  console.log("Connected to access point");
  mqtt.connect();
});

ERROR:Connect failed (err113)
Uncaught InternalError: Unable to create socket at line 4 to 2 c)^ in function "connect" called from line col 16 mqtt.connect(); in function called from system

**Comment by gfwilliams** [comment]
I'm 99% sure it's because you're connecting to MQTT *before* you connect to WiFi. Try moving all your MQTT init stuff inside the `wifi.connect` callback

for support questions please ask in the forum first. There's even an ESP8266-specific section: http://forum.espruino.com/microcosms/925/
