### ISSUE TITLE
MPU6050 module - no output after 1v94 update

### ISSUE THREAD

**Issue by frontsidekante** [espruino/Espruino#1259]
`I2C1.setup({scl:B6,sda:B7});`
`var mpu = require("MPU6050").connect(I2C1);`

`mpu.getTemperature();`
`mpu.getRotation();`

would return the relevant data. Also a bunch of startup output.
After the firmware update those methods don't return anything.

**Comment by frontsidekante** [comment]
needs console.log() now to display

**Comment by gfwilliams** [comment]
Thanks for figuring it out - but just FYI they never did print anything even in previous versions - unless you input the last 2 lines on the left-hand side of the IDE.
