### ISSUE TITLE
official build is not working on NUCLEOL476RG board for Neopixel module

### ISSUE THREAD

**Issue by hutualive** [espruino/Espruino#1264]
I'm trying the official build on NUCLEOL476RG board with Neopixel module. it's not working.

I tried up to the 1st release of official build for NUCLEOL476RG, no one is working. 

attached the screen shoot FYI. it's not implement on L476 or just a type error caused issue ? thanks.

<img width="1680" alt="error-nucleo-l476-neopixel" src="https://user-images.githubusercontent.com/527337/31987142-7dae2090-b930-11e7-9d95-ce3d99182646.png">

**Comment by gfwilliams** [comment]
Yes, as suggested in the error message, it's not supported.

If you want sure-fire support for stuff like this, it's best to use the official Espruino boards.
