### ISSUE TITLE
ESP32 compile bug

### ISSUE THREAD

**Issue by chegewara** [espruino/Espruino#1265]
Hi,
I just wanted to give it a try but after following instructions from section "Build the firmware" http://www.espruino.com/ESP32 im getting this error:

```
A fatal error occurred: Segment loaded at 0x40168bec lands in same 64KB flash mapping as segment loaded at 0x40168bd4. Can't generate binary. Suggest changing linker script or ELF to merge sections.
make: *** [espruino_1v94.175_esp32.bin] Error 2
```

**Comment by wilberforce** [comment]
The latest Travis build for esp32 was ok...

Perhaps you could compare the logs here:

https://travis-ci.org/espruino/Espruino/jobs/303561865
