### ISSUE TITLE
[Feature Request] Looking for HTTPS support for ESP8266

### ISSUE THREAD

**Issue by gnanaswaroop** [espruino/Espruino#1266]
I see the official boards do support HTTPS support but the other popular boards like ESP8266 donot support HTTPS calls out of the box. 

This is a feature request to support HTTPS for ESP8266, ESP32.

There are 3rd party services like httpTohttps but that defeats the purpose of having HTTPS as a part of the request would have to be sent via HTTP to an intermediate repeater.

**Comment by gfwilliams** [comment]
ESP32 supports HTTPS already I believe.

ESP8266 won't support HTTPS without reducing the available RAM to the point where you can't run any useful JS code. If we could have produced a build with it in, we would have.

Basically if you want proper HTTPS support,  you're best off using the official Espruino boards.
