### ISSUE TITLE
Error when using template literals

### ISSUE THREAD

**Issue by aporcupine** [espruino/Espruino#1269]
Template literals work fine, but an error is shown under Settings > Console when sending to the device:
```
SyntaxError: Unterminated string constant (3:29)
ERROR: [notify_error] Acorn parse for plugins/compiler.js failed.<br/>Check the editor window for syntax errors
```

The following code works, but presents the aforementioned error: 

```
let entity = 'World';

console.log(`Hello ${entity}`);
```

**Comment by gfwilliams** [comment]
Thanks - looks like an issue with the acorn version used in the IDE. I've updated it and the error seems to disappear now
