### ISSUE TITLE
http.createServer().listen() should return a Server instance

### ISSUE THREAD

**Issue by opichals** [espruino/Espruino#1276]
server.listen() is void unlike the [node.js implementation](https://nodejs.org/dist/latest-v8.x/docs/api/net.html#net_server_listen_port_host_backlog_callback) where it returns an instance of the server.

As the fix is trivial it appears to be worth fixing for better developer compatibility.

**Comment by gfwilliams** [comment]
Just fixed :)

Also I noticed that dgram.bind returned the parent without locking it again - but fixing it causes memory leaks - so I think there might be something iffy going on with locks in dgram - perhaps an extra lock somewhere else where there shouldn't be one... It might be worth looking into as it could cause problems later on?
