### ISSUE TITLE
Missing break after case BLEP_NFC_STATUS

### ISSUE THREAD

**Issue by drandreas** [espruino/Espruino#1291]
In my humble opinion a break is missing after `case BLEP_NFC_STATUS:` in `bluetooth.c`

https://github.com/espruino/Espruino/blob/720f57ed58a235f9b68499f0c4a611671575c308/targets/nrf5x/bluetooth.c#L228

**Comment by gfwilliams** [comment]
Damn. Thanks! I guess that means that 1v95 outputs a warning every time NFC is used. I might need to create a new firmware without that.
