### ISSUE TITLE
Generate basic scaffold

### ISSUE THREAD

**Issue by Lysandroc** [espruino/Espruino#1292]
Hi, 

I would like to know about how can I create a template project with live-reload, I run javascript from CLI and it's very boring.

At first time I found [thingssdk](https://github.com/thingsSDK/thingssdk-cli), but it doesn't work. 

:thinking:

**Comment by gfwilliams** [comment]
Hi - please could you ask [on the forum](http://forum.espruino.com/), and maybe include the type of board you're using?

You should just be able to use `npm install -g espruino` then `espruino -p your_device_port -w your_project.js` though,
