### ISSUE TITLE
Missing bracket in src/jspin.c

### ISSUE THREAD

**Issue by shodan8192** [espruino/Espruino#1314]
https://github.com/espruino/Espruino/blob/5b6d1eff60b3ad8dfa5692c63218346cd7753f11/src/jspin.c#L64

should be :

`} else if (port == JSH_PORTA) {`

**Comment by gfwilliams** [comment]
Thanks - sorry, not sure how that one slipped in. I guess I'd been building nRF52 which doesn't have a port A.
