### ISSUE TITLE
How to put byte array in flash memory .

### ISSUE THREAD

**Issue by Akskaypohankar** [espruino/Espruino#1318]
Hi,
thanks in advance for addressing this request.
We are using Arduino for **programming** and **Sparkfun esp 32** things board for hardware.    

in my code, I am receiving a large data of approximately  3kb [all hexa. bytes ] in size via a hardware serial port which I need to store and then process for further processing. because of its size, i think flash is the only place where I can store this but while using **preferences** library for this how can I make an array in a flash to store all this data under one variable.
please if you know any better or alternate way to solve this problem feel free to suggest

**Comment by gfwilliams** [comment]
Hi. This is the repository for Espruino - http://www.espruino.com

It looks like you're after Arduino: https://www.arduino.cc

Espruino is software that happens to be available for ESP32 (among others), but it has no other relation to ESP32, ESP8266, or EspressIf (who make those chips)

**Comment by Akskaypohankar** [comment]
yes I realized my mistake a while ago anyways thank you
