### ISSUE TITLE
RAK815 Support

### ISSUE THREAD

**Issue by MrAPierce** [espruino/Espruino#1357]
Hi I believe that this [device](https://www.aliexpress.com/item/RAK815-Hybrid-Location-Tracker-LoRa-Bluetooth-5-0-Beacon-GPS-Sensors-LCD-LoRaWAN-1-0-2/32849717052.html) is running a a nrf52832 along side a sx127x lora module with a barrage of other sensor including gps, would it be possible to support this board?

**Comment by gfwilliams** [comment]
Closing for now - can always discuss this on the forum: http://forum.espruino.com/microcosms/1085/
