### ISSUE TITLE
Not creating new variable scope in catch block

### ISSUE THREAD

**Issue by andrewwakeling** [espruino/Espruino#1367]
The identifier (which holds the thrown value) [should only be available in the catch block.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch)

```javascript
var e = 'hi';
try {
  throw new TypeError();
} catch(e) {}
console.log(e);
```

Expected: 'hi'
Actual: TypeError

**Comment by andrewwakeling** [comment]
Apologies. I know this is really obscure. It caught me unawares when my code was minified.

**Comment by gfwilliams** [comment]
Hi - thanks for reporting these. Out of interest, how did you find them? Did you run tests, or was it literally just some code you had that exhibited all these problems? It seems like you're particularly unlucky if so.

**Comment by andrewwakeling** [comment]
I stumbled across this when minifying code from my workaround I posted in #1363.

`valueOrThenable` was renamed to `e` which caused my workaround to do strange things when my code was minified.

**Comment by andrewwakeling** [comment]
@gfwilliams, this is what I've been working on https://github.com/andrewwakeling/espruino-webpack-babel-sample
