### ISSUE TITLE
Add crypto to original Espruino board

### ISSUE THREAD

**Issue by gfwilliams** [espruino/Espruino#1368]
So it can be used with websockets: http://forum.espruino.com/conversations/319040/#comment14173531

We can hopefully strip out the SHA224/etc code and have *just* SHA1 which will leave enough space

**Comment by wilberforce** [comment]
I think you have done this now with

https://github.com/espruino/Espruino/commit/27d9572ce291136932e718768c168ab20eebcb4c

.?

**Comment by gfwilliams** [comment]
Yes, thanks!
