### ISSUE TITLE
Add ON Off - reasonable  or a waste of vars.

### ISSUE THREAD

**Issue by MaBecker** [espruino/Espruino#1372]
Added ON OFF to my fork and asking myself if this would make sense to add this to the master.

src/jswrap_number.c:

```
/*JSON{
  "type" : "variable",
  "name" : "ON",
  "generate_full" : "1",
  "return" : ["int32","Logic 1 - this is the same as just typing `1`"]
}*/

/*JSON{
  "type" : "variable",
  "name" : "OFF",
  "generate_full" : "0",
  "return" : ["int32","Logic 0 - this is the same as just typing `0`"]
}*/
```

**Comment by gfwilliams** [comment]
Honestly, probably not... We already have `HIGH` and `LOW` for Arduino compatibility - are ON and OFF used there as well, or it just seems nice to have?

**Comment by MaBecker** [comment]
Nichtig have 😊

**Comment by MaBecker** [comment]
Nice to have 😊
