### ISSUE TITLE
wifi is reconnecting permanently for ESP8266-STA connect to ESP8266-AP

### ISSUE THREAD

**Issue by MaBecker** [espruino/Espruino#1392]
Testreport and details are in  #1391

No idea where to start to figure out why a ESP8266-Station can not setup a stable connect to an ESP8266-AccessPoint

**Comment by MaBecker** [comment]
ESP8266-STA has no reconnect issues when using a  ESPRUINOWIFI board as AP

**Comment by wilberforce** [comment]
What version of the sdk are your running on the boards? Perhaps the AT firmware is using a later firmware.

The other difference will be the open lwip firmware vs the espressif closed lib on the AT version

**Comment by MaBecker** [comment]
Same tests are working with SDK 2.2.1, so close this when issues #1207 is available.
