### ISSUE TITLE
`E.reboot()` function

### ISSUE THREAD

**Issue by gfwilliams** [espruino/Espruino#1429]
We have ESP8266/32.reboot, but nothing general-purpose.

It'd be great to have something for all platforms, then you could do stuff like:

`setWatch(E.reboot, BTN1, {irq:true})`

which would do a reboot in an IRQ, so would act as a reset pin.

`E.break()` to trigger a ctrl-c event would be equally useful

**Comment by wilberforce** [comment]
What is name history behind `E ? . Should this type of thing be part of `process` ?

**Comment by gfwilliams** [comment]
It's mainly a catch-all for functionality that isn't part of normal JavaScript or a module. I'd rather not add it to `process` since it's not part of `process` in Node.js.
