### ISSUE TITLE
Storage and fs.list('config') to check if 'config' is already saved

### ISSUE THREAD

**Issue by MaBecker** [espruino/Espruino#1430]
This should be helpful if someone wants to check if  eg 'config' is already saved or not by just use list and  the name to look for.

```
if (fs.list('config')) {
  console.log('read config');
  config = fs.readJSON('config');
} else {
  console.log('save config');
  fs.write('config'); 
}
```

What do you think?

**Comment by wilberforce** [comment]
Is `fs` a `Storage` object?

**Comment by MaBecker** [comment]
> Is fs a Storage object

yes

**Comment by MaBecker** [comment]
or mybe  fs.exist('config')

**Comment by gfwilliams** [comment]
We could do, but it's just as fast as doing `fs.read('config')!==undefined` (that's what would basically be done under the hood). Is it really worth adding that as a utility function when we're down to our last 100 bytes on some platforms?

I could make it only available on ones with enough memory, but that just feels even more confusing.

**Comment by MaBecker** [comment]
Ok, so lets use 

fs.read('config')!==undefined

and close this.
