### ISSUE TITLE
Missing require('Storage').readStream('file')

### ISSUE THREAD

**Issue by opichals** [espruino/Espruino#1432]
It'd be nice way to stream data out in WebServer via `pipe()` call.

Also this can allow processing larger than 65kB contents (as strings are limited to this).

A first step may be adding `offset`+`len` support to `Storage.read()` i.e. `jsfReadFile()`

**Comment by opichals** [comment]
> With the 65k limit, I think we can actually get away without that on all but the most confined (<1k vars) platforms. I've just tweaked it.

I don't understand. How can the data beyond the 65k limit /that can be written by require('Storage').write('file', "test", 66000, 100)/ be accessed?

**Comment by opichals** [comment]
And yes, the JS module is completely fine for this, not sure what would be more space-saving.

**Comment by gfwilliams** [comment]
Closing this as you can now do `E.pipe(require('Storage').read(...), dst)` and this should work fine
