### ISSUE TITLE
Reception failure following a !m_intTxEnabled transmission

### ISSUE THREAD

**Issue by disk91** [espruino/Espruino#1442]
With new version ensuring no interrupt during transmission at 9600 bps the transmission error have been fixed. A new problem has appeared: the reception is corrupted on the first bits and some bits are missing.
I assume, this could be due to the execution of the pending interrupt blocked during transmission when the slave device is responding too fast. ( 5 - 10ms ) these one could delay the RxInterruption execution. As Rxinterruption is waiting up-to the end of the stop bit, interrupt are chained and delay is propagated to multiple bits.
Not sure how to fix it.

**Comment by gfwilliams** [comment]
Sorry, but there's nowhere near enough information here to be any help...

What device are you using? What's it connected to? Is it Serial, I2C, etc? Do you have example code for what you're doing?

**Comment by gfwilliams** [comment]
This isn't related to Espruino. `m_intTxEnabled ` isn't in the source at all.

If you have a problem with the ESP8266 in general please get in contact with EspressIF - this repo is for Espruino.

**Comment by disk91** [comment]
hum you're full right, I've not created the issue in the right repo. Too many open tabs ;) sorry for that
