### ISSUE TITLE
setInterval and module with class

### ISSUE THREAD

**Issue by pkjq** [espruino/Espruino#1446]
When i create a new module with exported class and setInterval in this file i see timers size is very big.
Example:
### project:
`require("test-module");`

### test-module:
```
class AnyClass {
    constructor() {
        this.arr1 = [1,1,1,1];
        this.arr2 = [1,1,1,1];
        this.arr3 = [1,1,1,1];
        this.arr4 = [1,1,1,1];
        this.arr5 = [1,1,1,1];
        this.arr6 = [1,1,1,1];
        this.arr7 = [1,1,1,1];
        this.arr8 = [1,1,1,1];
        this.arr9 = [1,1,1,1];
        this.arr0 = [1,1,1,1];
        this.arra = [1,1,1,1];
        this.arrb = [1,1,1,1];
        this.arrc = [1,1,1,1];
        this.arrd = [1,1,1,1];
        this.arre = [1,1,1,1];
        this.arrf = [1,1,1,1];

        this.arr11 = [1,1,1,1];
        this.arr22 = [1,1,1,1];
        this.arr33 = [1,1,1,1];
        this.arr44 = [1,1,1,1];
        this.arr55 = [1,1,1,1];
        this.arr66 = [1,1,1,1];
        this.arr77 = [1,1,1,1];
        this.arr88 = [1,1,1,1];
        this.arr99 = [1,1,1,1];
        this.arr00 = [1,1,1,1];
        this.arraa = [1,1,1,1];
        this.arrbb = [1,1,1,1];
        this.arrcc = [1,1,1,1];
        this.arrdd = [1,1,1,1];
        this.arree = [1,1,1,1];
        this.arrff = [1,1,1,1];
        
        this.arr111 = [1,1,1,1];
        this.arr222 = [1,1,1,1];
        this.arr333 = [1,1,1,1];
        this.arr444 = [1,1,1,1];
        this.arr555 = [1,1,1,1];
        this.arr666 = [1,1,1,1];
        this.arr777 = [1,1,1,1];
        this.arr888 = [1,1,1,1];
        this.arr999 = [1,1,1,1];
        this.arr000 = [1,1,1,1];
        this.arraaa = [1,1,1,1];
        this.arrbbb = [1,1,1,1];
        this.arrccc = [1,1,1,1];
        this.arrddd = [1,1,1,1];
        this.arreee = [1,1,1,1];
        this.arrfff = [1,1,1,1];        
    }
};


//exports.create = AnyClass;


////////////////

setInterval(function(){
    console.log('Tick');
}, 1000);
```

When class exported:
>E.getSizeOf(global['\xFF'],1)
=[
  {
    "name": "timers",
    **"size": 93 },**
  {
    "name": "watches",
    "size": 3 },
  {
    "name": "net",
    "size": 2 },
  {
    "name": "modules",
    "size": 83 },
  {
    "name": "history",
    "size": 113 }
 ]

When class doesn't exported:
>E.getSizeOf(global['\xFF'],1)
=[
  {
    "name": "timers",
    **"size": 23 },**
  {
    "name": "watches",
    "size": 3 },
  {
    "name": "net",
    "size": 2 },
  {
    "name": "modules",
    "size": 8 },
  {
    "name": "history",
    "size": 26 }
 ]

In my real code the size of timers is about 500 😨  when i create one repeated event.

**Comment by gfwilliams** [comment]
`E.getSizeOf` shows the size of a variable *and everything it references*. For instance if I do:

```
var a = (function() {
  var d = "lots of data";
  return function() { return d; } 
})();
```

Then `a` is a single function, but it references the scope it was defined in, which contains `d` which might be big.

So what you're seeing is the size of the whole module (because that's part of the scope that is saved when that function is defined) - the timer itself isn't actually that big.

To reduce the size of your actual module, I'd look at http://www.espruino.com/Performance. If you can pack all your arrays into one typed array you'd save a bunch of memory.
