### ISSUE TITLE
Use of Potentially Dangerous Function - CWE-676

### ISSUE THREAD

**Issue by teamwoot** [espruino/Espruino#1455]
Hi Team, 

We observed that `https://github.com/espruino/Espruino/blob/master/targets/linux/jshardware.c#L302`

i.e

`usleep(shortSleep ? 1000 : 50000);`

This C routine is considered obsolete (as opposed to the shell command by the same name). The interaction of this function with SIGALRM and other timer functions such as sleep(), alarm(), setitimer(), and nanosleep() is unspecified such as (CWE-676). 

Use nanosleep(2) or setitimer(2) instead.

Request team to have a look for same.

Regards
Team w00t

**Comment by wilberforce** [comment]
@gfwilliams 

Shall we close this? Are you likely to change `sleep` in the Linux server build?

**Comment by gfwilliams** [comment]
It wouldn't be a big change, so I'm tempted to do it. I wonder whether at some point the fact it's obsolete will mean that there start being issues when compiling it for embedded linux targets.

**Comment by wilberforce** [comment]
Looks like there is a function you could use to replaced defined in the mbed libs:

https://github.com/espruino/Espruino/search?q=usleep&unscoped_q=usleep

**Comment by gfwilliams** [comment]
Thanks - just sorted
