### ISSUE TITLE
Support malloc, add init Security to GAP, buffer notifications, minHeap

### ISSUE THREAD

**Issue by jumjum123** [espruino/Espruino#1460]
Some commits have been pushed to ESP32-v3.0 branch.
- added missing handling of malloc in jsvar.c jsvGetAddressOf
- added initialization and event handling of Security for GAP
- notification for bluetooth are buffered now, to avoid tons of single char notifications
- added a function to get minimal available heap, could be helpful for adjusting jsVars

**Comment by gfwilliams** [comment]
It sounded from recent posts like you wanted this week to work on it? What's in that branch looks fine for me to merge if you want me to though?

**Comment by jumjum123** [comment]
Just uploaded some changes.
From my best knowledge, its ready to be merged.
UART works on Android, but on Windows 10 I still have problems.
And there's a size problem in advertising

**Comment by wilberforce** [comment]
@jumjum123 have these changes been made?

Can this be closed?

**Comment by jumjum123** [comment]
@wilberforce 
changes are done.
There is still a problem in BLE with connecting, but thats a different playground
