### ISSUE TITLE
Any way to get the list of built-in modules?

### ISSUE THREAD

**Issue by vshymanskyy** [espruino/Espruino#1464]
`Modules.getCached()` only returns modules that were already required.
Is there a way to get all built-in modules that I can `require()`?

**Comment by wilberforce** [comment]
The web ide does It - look at the console after connect.  

`console.log(process)

For this kind of question, please using the forums rather than raising as an issue - as it's not an issue with the firmware/build.

**Comment by vshymanskyy** [comment]
Great. Thanks, I found it: 
```
process.env.MODULES.split(',')
```
No, i still think this is is issue - but more on documentation side.
I think this is worth adding to the API reference.

**Comment by gfwilliams** [comment]
As @wilberforce says, please can you ask these kinds of questions on the forum in future?

So you want to add better descriptions to the `process.env` docs? They definitely seem out of date.

If you want to issue a PR it's as easy as clicking on `=>` next to the the method/field name in the docs and it'll bring you to the place in the code file in GitHub that needs changing.
