### ISSUE TITLE
ESP32: Slow SPI

### ISSUE THREAD

**Issue by vshymanskyy** [espruino/Espruino#1477]
I just faced the same performance issue described here:
http://forum.espruino.com/conversations/321375
@gfwilliams commented that:
```
Personally I'd like to sort out SPI properly so that
it could work with buffers and DMA. That'd massively
improve performance on all platforms.
```
So I decided to create this ticked to track this issue.

**Comment by gfwilliams** [comment]
Please don't open bugs like this. This is already more than covered in:

* https://github.com/espruino/Espruino/issues/695
* https://github.com/espruino/Espruino/issues/1212

Last thing I need is 50 of every bug, one for each board.

**Comment by vshymanskyy** [comment]
Sorry, both these issues seemed unrelated at first glance
