### ISSUE TITLE
Error in module BMP085, reading signed short

### ISSUE THREAD

**Issue by jbgagnon** [espruino/Espruino#1483]
in module https://www.espruino.com/modules/BMP085.js
fonction BMP085.prototype.readS16 
line 61 : return (i>=32767) ? i - 65536 : i;

must be written: return (i>=32768) ? i - 65536 : i;
or : return (i>32767) ? i - 65536 : i;
or : return (i&0x8000) ? i - 65536 : i;

it's the small bug because the case of i==32767 never happen because readS16 is only used for reading coefficient but if once it happens the function will return -32769 and not 32767 !!!

**Comment by gfwilliams** [comment]
Fixed with https://github.com/espruino/EspruinoDocs/commit/67d1eedf37c4c561b5d70101a57a43f138576c12 - turns out a bunch of other stuff was broken like this as well!
