### ISSUE TITLE
ESP32: Neopixel does not work anymore with experimental 1v99

### ISSUE THREAD

**Issue by NielsLeenheer** [espruino/Espruino#1484]
When using the experimental 1v99 version of Espruino, using the following command from the documentation to change the color of a NeoPixel nothing happens: 

````is
require("neopixel").write(D13, [255,0,0]);
````

However, if I flash the current 1v95, it works without issues.

**Comment by wilberforce** [comment]
Could this be related to ?

https://github.com/espruino/Espruino/commit/fcccdccb4a826e4ce66c6dea1214a4100acad5a2

**Comment by gfwilliams** [comment]
Nope - ESP32 uses its own function esp32_neopixelWrite - which as far as I know hasn't changed since it was created ages ago.

I guess it's the new ESP32 SDK?

**Comment by wilberforce** [comment]
v1_98 is the last working version
https://www.espruino.com/binaries/espruino_1v98_esp32/
2018-05-18

**Comment by wilberforce** [comment]
@jumjum123 

This has stopped working from we changed to the V3.0 sdk.

Any ideas of what needs to be updated here:

https://github.com/espruino/Espruino/blob/master/targets/esp32/esp32_neopixel.c

?

**Comment by jumjum123** [comment]
Hmm, I only know about a change around V3.1
  SET_PERI_REG_MASK(DPORT_PERIP_CLK_EN_REG, DPORT_RMT_CLK_EN);
  CLEAR_PERI_REG_MASK(DPORT_PERIP_RST_EN_REG, DPORT_RMT_RST);
needs to be replaced with
  DPORT_SET_PERI_REG_MASK(DPORT_PERIP_CLK_EN_REG, DPORT_RMT_CLK_EN);
  DPORT_CLEAR_PERI_REG_MASK(DPORT_PERIP_RST_EN_REG, DPORT_RMT_RST);
To be honest, I did not check. And for about a month I will not have much time.

**Comment by wilberforce** [comment]
This has been fixed in 
https://github.com/espruino/Espruino/pull/1585
