### ISSUE TITLE
Math.round must return a Number not an int32_t 

### ISSUE THREAD

**Issue by jbgagnon** [espruino/Espruino#1485]
Math.round must return something equal to Math.floor or Math.ceil 
Math.round(Date.now()) return an invalid value
in google console : 1533657792393
in espruino : 2147483647
(in espruino Math.floor and Math.ceil are OK)
to convert to an int32_t we must use something like : ( value | 0)

**Comment by gfwilliams** [comment]
Thanks! Just fixed.
