### ISSUE TITLE
function setTime() strip to seconds on ESP32

### ISSUE THREAD

**Issue by jbgagnon** [espruino/Espruino#1488]
in file: targets/esp32/jshardware.c
function: jshSetSystemTime
line: 611
  tm.tv_sec=(time_t)(newTime/1000000L);
  tm.tv_usec=0; 

can be change in :
  tm.tv_usec = (suseconds_t) (newTime % 1000000L); 
or: (if divide a second time  loose too much time)
  tm.tv_usec = (suseconds_t) (newTime - tm.tv_sec * 1000000L); 

for testing:
function tstTime() {
  let t1 = getTime();
  setTime(t1);
  let t2 = getTime();
  console.log(t2 -t1);
}
must not write negative value !

**Comment by wilberforce** [comment]
Closed by

https://github.com/espruino/Espruino/commit/9de4b65bb6a5d870bb5873dcb2a57a7b72c205b2
