### ISSUE TITLE
btoa returns empty string for array

### ISSUE THREAD

**Issue by MaBecker** [espruino/Espruino#1509]
btoa("Hallo");
    ="SGFsbG8="
    btoa([0,1,2,3,4,5,6,7,8,9]);
    =""

**Comment by gfwilliams** [comment]
I think this is a more general issue than ESP8266. Was pretty sure I fixed it last week, but maybe I forgot to push it. I'll check when I return

**Comment by MaBecker** [comment]
Thanks
