### ISSUE TITLE
Serial.setup() with options for bytesize, parity and stopbits cause ASSERT(0)

### ISSUE THREAD

**Issue by MaBecker** [espruino/Espruino#1510]
Serial2.setup(9600,{rx:D12,tx:D13,bytesize:8,parity:'none',stopbits:1});

    ASSERT(0) FAILED AT targets/esp8266/jshardware.c:833
      #1[r1,l2] Object {
        #2[r1,l2] Name String [1 blocks] "\xFF"      #3[r1,l1] Object {
    ....
    507089> ASSERT FAILED AT targets/esp8266/jshardware.c:833
    ---console end---
    507095> CRASHING. 
    507097> Fatal exception 9(LoadStoreAlignmentCause):

Serial2.setup(9600,{rx:D12,tx:D13}); works fine and can be used because 8 none 1 is default.

The structure [JshUSARTInfo](https://github.com/espruino/Espruino/blob/master/src/jshardware.h#L232-L243) is not corrected handled on ESP8266 in [jshUSARTSetup](https://github.com/espruino/Espruino/blob/master/targets/esp8266/jshardware.c#L792-L837)

changing `unsigened char` to `unsigned int` fixes this on ESP8266 what about side effect on other devices?

**Comment by gfwilliams** [comment]
> changing unsigened char to unsigned int fixes this on ESP8266 

On all elements of  JshUSARTInfo ?

I'm not sure I understand what's going on here - maybe you could print the contents of every element in JshUSARTInfo?

If ESP8266 is unable to read/write from an `unsigned char` in a struct then that's something that needs sorting with compiler flags, as while we could patch over this one, there are hundreds of other points that this coulkd fail in the future?

**Comment by wilberforce** [comment]
This isn't a flash alignment issue is it? - the structure would be in ram.

**Comment by gfwilliams** [comment]
Yeah, should be - so I wonder why the `LoadStoreAlignmentCause`?

**Comment by MaBecker** [comment]
This is not the first time that a structure cause `LoadStoreAlignmentCause`
happend for [jshI2CSetup](https://github.com/espruino/Espruino/commit/3b70b659d1a011158469c03c0ed7d22fda8db8f6#diff-86c89974f1c0df2bdfa41c84fa2bd764R311)  too and was fixed by reordering the entries.


`Serial2.setup(9600,{rx:D12,tx:D13});` works, so this is ok for ESP8266.

Using `typedef struct { }` will always fail on ESP8266 for one byte entries.

**Comment by gfwilliams** [comment]
I guess we could have a PACKED_FLAGS_MAYBE thing where it was enabled for all platforms except ESP8266 - I don't have time right now to figure out what would be affected on other platforms if we removed the packing completely.

**Comment by MaBecker** [comment]
Thanks Gordon, will run some test with different `typedef struct{}` and compiler flags.

**Comment by MaBecker** [comment]
> I guess we could have a PACKED_FLAGS_MAYBE .... 
What do you mean @gfwilliams?

**Comment by gfwilliams** [comment]
Rather than having even more `#ifdef ESP8266` we have `PACKED_FLAGS_MAYBE` which is defined in `jsutils.h` like `PACKED_FLAGS`, but which does stuff for all platforms **except** ESP8266.

`PACKED_FLAGS_MAYBE` is a bad name - I'm open to better suggestions

**Comment by MaBecker** [comment]
Sounds funny, had no idee that it is defined jsutil.h

So let me check gcc flags and run some tests.

**Comment by MaBecker** [comment]
> On a serious note there must be compiler flag for this. 
Do you mean -mforce-l32                 
Use l32i to access 1- and 2-byte quantities in
memory instead of l8ui/l16ui

If Yes, it is implemented for ESP8266_4MB builds
