### ISSUE TITLE
Was there a reason for adding SHA256 and SHA512 on ESP8266_4MB

### ISSUE THREAD

**Issue by MaBecker** [espruino/Espruino#1517]
As far as I know there is only module `ws` that is using sha1? Or do I miss some modules or functions 
that use SHA256 or even SHA512?

This is all about remove not needed stuff to have space for important things.

Like to remove it if not needed.

**Comment by gfwilliams** [comment]
I haven't heard of anyone needing it. I think they just got added because there was space for them at one point.

Are we still trying to fit in 512k on the 4MB parts though?

**Comment by gfwilliams** [comment]
Maybe leave this open for a week and see if anyone complains, then remove them?

**Comment by hungryforcodes** [comment]
What would it normally be used for, aside from HTTPS related stuff? A version of TEA (Tiny Encryption Algorithm) might be nice to put in the ESP8266 build instead, if I had to make choices about space. Unless someone has another compact encryption library they would nominate instead.

**Comment by MaBecker** [comment]
> Are we still trying to fit in 512k on the 4MB parts though?

Fortunately not :-)

> Maybe leave this open for a week and see if anyone complains, then remove them?

Yes

> A version of TEA (Tiny Encryption Algorithm)

check #1055

**Comment by hungryforcodes** [comment]
Ah, I missed that for some reason -- thanks! ;)

**Comment by MaBecker** [comment]
Ok, lets remove it
