### ISSUE TITLE
WiringPi Build Failing (EV_EXTI references)

### ISSUE THREAD

**Issue by wybiral** [espruino/Espruino#1525]
While attempting to build for Linux using WiringPi I'm getting this error:

```BASH
targets/linux/jshardware.c: In function ‘irqEXTI1’:
targets/linux/jshardware.c:110:39: error: ‘EV_EXTI1’ undeclared (first use in this function)
 void irqEXTI1() { jshPushIOWatchEvent(EV_EXTI1); }
                                       ^~~~~~~~
targets/linux/jshardware.c:110:39: note: each undeclared identifier is reported only once for each function it appears in
targets/linux/jshardware.c: In function ‘irqEXTI2’:
targets/linux/jshardware.c:111:39: error: ‘EV_EXTI2’ undeclared (first use in this function)
 void irqEXTI2() { jshPushIOWatchEvent(EV_EXTI2); }

...
```

It looks like [this change](https://github.com/espruino/Espruino/commit/ec20db143856283463ba48d375c098420aa55b61#diff-686586050c3f81d4362bfe8700742cb8) may have broken the references in [this file](https://github.com/espruino/Espruino/blob/master/targets/linux/jshardware.c#L108). Changing those references to `EV_EXTI0+1`, `EV_EXTI0+2`, etc results in a successful build but I'm not sure if there are any downsides to that workaround.

**Comment by gfwilliams** [comment]
Thanks for checking it out in so much detail! Yes, it's absolutely fine to fix it that way (it's done in a few other places in that file as well) as EXTI_COUNT is 16 for all the Linux builds anyway.
