### ISSUE TITLE
Storage.readArrayBuffer do 1 variable memory leak

### ISSUE THREAD

**Issue by jbgagnon** [espruino/Espruino#1532]
require('Storage').write('f','hello world !');
process.memory();
for(var i = 0; i< 100;i++) {
    var a = require('Storage').readArrayBuffer('f');
 }
 process.memory();

// you loose 100 variable !

**Comment by jbgagnon** [comment]
same problem with readJSON

require('Storage').write('f',JSON.stringify({x:3,y:4}));
process.memory();
for(var i = 0; i< 100;i++) {
 var a = require('Storage').readJSON('f');
 }
 process.memory();
// you loose 100 varaibles again ! (need to reboot now ... )

**Comment by iotong** [comment]
no！you need call process.memory() after readJSON or readArrayBuffrr

**Comment by gfwilliams** [comment]
Thanks - yes, it looks like they're missing unlocks. Thanks for the report - I'll sort it on Monday
