### ISSUE TITLE
operator 'in' throws error for Uint8Array

### ISSUE THREAD

**Issue by jbgagnon** [espruino/Espruino#1534]
a = new Uint8Array([1,2,3]);
a.buffer !== undefined  => return true (great !)
'buffer' in a => generate an error ... (Uncaught Error: Cannot use 'in' operator to search a Uint8Array)
but 'typeof a' say that a is an object so operator 'in' can be use (normaly) , no ?

**Comment by gfwilliams** [comment]
Thanks - internally, Uint8Array isn't actually an object, but `in` should still work on it. Looks like it'll need to check jswrapper for the various properties using the same function Object.keys/etc use (plus the numeric indices too).

**Comment by gfwilliams** [comment]
The fix above works for the case shown above, but not:

```
a = new Uint8Array(10)
5 in a // should return true
```

Same for `length` - so leaving this open
