### ISSUE TITLE
buffer to small in function jsfLoadBootCodeFromFlash

### ISSUE THREAD

**Issue by jbgagnon** [espruino/Espruino#1540]
```
bool jsfLoadBootCodeFromFlash(bool isReset) {
  // Load code in .boot0/1/2/3
  char filename[6] = ".bootX";
```
.bootX\0 have 7 bytes

see http://forum.espruino.com/conversations/327034/

**Comment by jbgagnon** [comment]
no permission to commit the change ...

**Comment by gfwilliams** [comment]
Thanks - You can just do a GitHub pull request from a fork on your personal account - for obvious reasons the repo isn't open to everyone to commit what they want :)

In this case it's super-simple, so I'll commit the change and save you some trouble though.
