### ISSUE TITLE
Hope to introduce the nrf5 mesh network into espruino.

### ISSUE THREAD

**Issue by espirate** [espruino/Espruino#1544]

**Comment by gfwilliams** [comment]
You are going to do this yourself? Or you would like someone else to add it?

I've been looking at this for a while, but Bluetooth Mesh isn't as amazing as it sounds none of the devices acting as internal mesh nodes are low power at all, so it's not really suitable for battery-powered devices.

There is also provision for mesh nodes to access normal Bluetooth LE devices, so it's still totally possible to use Espruino devices as-is in a mesh. You just need to have fully-functional powered mesh nodes.

**Comment by espirate** [comment]
thank you

**Comment by gfwilliams** [comment]
I'm a bit confused - were you going to add support yourself? Or was this a request for it to be added for you?
