### ISSUE TITLE
ESP8266 deepSleep invalid microseconds

### ISSUE THREAD

**Issue by sirpy** [espruino/Espruino#1547]
Its not possbile to set deepsleep for a long time
for example this 10 digit number returns an error:
6000000000
while 9 digits works

since deepsleep is in micro seconds it really limits the range.
```
>ESP8266.deepSleep(9071992547)
Uncaught Error: Invalid microseconds.
 at line 1 col 29
ESP8266.deepSleep(9071992547)
                            ^
>ESP8266.deepSleep(907199254)
=undefine
```

**Comment by MaBecker** [comment]
bool system_deep_sleep(uint64 time_in_us)
uint64 : 0 to 18446744073709551615 

This is the line that has to be fixed to handle uint64  [`int sleepTime = jsvGetInteger(jsMicros);`](https://github.com/espruino/Espruino/blob/master/targets/esp8266/jswrap_esp8266.c#L356) 

Change it to `uint64_t sleepTime = jsvGetLongInteger(jsMicros);`and try again if you can build by out own.
