### ISSUE TITLE
in a switch default can't be elsewhere than at the end

### ISSUE THREAD

**Issue by jbgagnon** [espruino/Espruino#1570]
function a(x) {
switch(x) {
default:
case 0: return "case 0";
case 1: return "case 1";
case 2: return "case 2";
}
return "no case";
}

thow an error when arriving at case 0 because after "default" nothing else is possible.

I know it's hard to resolve because the parser must records where the default is and at the end of the switch go back to it if no case appens

(and in many cases it's easy to do differently to prevent the use of default)

**Comment by MaBecker** [comment]
Well what about `break;` between your cases?

Have you check [switch Javascript MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch)?
