### ISSUE TITLE
many jsiConsolePrintf are available for RELEASE=1

### ISSUE THREAD

**Issue by MaBecker** [espruino/Espruino#1578]
capsulate jsiConsolePrintf to make only available when DEBUG=1

#ifdef DEBUG
#define DBG(...) jsiConsolePrintf("[Flash] "__VA_ARGS__)
#else
#define DBG(...)
#endif

**Comment by MaBecker** [comment]
Searching for [jsiConsolePrint](https://github.com/espruino/Espruino/search?q=jsiConsolePrint&unscoped_q=jsiConsolePrint) returns 27 code results in espruino/Espruino

**Comment by gfwilliams** [comment]
Is that a problem? Looking at it the majority of those are things that are intended to print things to the console - they're not debug/log messages that are erroneously built in.

**Comment by MaBecker** [comment]
Not a problem but a potential step to shrink size
