### ISSUE TITLE
Would like to help you create a nicer looking website

### ISSUE THREAD

**Issue by loganpowell** [espruino/Espruino#1593]
Hi, I just bought your book and am very much looking forward to getting started with Espruino. I need to brush up on my front-end javascript skills and I'm looking for a practice project. Don't take this personally, but I think I may be able to put together a nicer looking website to give a nicer impression of Espruino to newbs like me. Would you like some help with this? No strings attached except for that I would be doing it in my spare time.

**Comment by gfwilliams** [comment]
Thanks for the offer - it does need a bit of love but I'm actually looking at getting a new/tweaked logo and I'd probably get a new site design as part of that when it happens.

However, if you see things that obviously seem broken or that could be tweaked I'm definitely up for doing minor CSS/etc changes.

I should note that the Espruino website design isn't itself on GitHub - it's literally the only bit of the whole project that isn't open (all the docs/hardware/software *are*), but that does make it a bit more difficult to contribute to.
