### ISSUE TITLE
No DFU zip for releases for the MDBT42 module

### ISSUE THREAD

**Issue by AkosLukacs** [espruino/Espruino#1594]
The download page contains only .hex files for the releases, for example `espruino_2v00_mdbt42q.hex`, and only the cutting edge build has a zip package for DFU.

The [travis build for 2v00](http://www.espruino.com/binaries/travis/ff35517cb6046e96d261568f24b78fac7a892c4d/) does have a zip, and the cutting edge build is working for me. Just wanted to let you know...

**Comment by gfwilliams** [comment]
Thanks! I'm just going builds for 2v01 so I'll get that fixed
