### ISSUE TITLE
HIDU2F

### ISSUE THREAD

**Issue by johnmacd** [espruino/Espruino#1610]
Is it possible to add USB HIDU2F support, so (say) pico could be used for U2F key.

**Comment by gfwilliams** [comment]
You mean this? https://fidoalliance.org/specs/fido-u2f-v1.0-ps-20141009/fido-u2f-hid-protocol-ps-20141009.html

On the STM32s there is currently no HID_OUT endpoint, which means that communications from the PC to the Pico aren't possible right now.

However if someone were to fix that then you should be able to implement what's in that link above in pure JavaScript.

On nRF52-based devices, there actually *is* two way HID communications over Bluetooth LE, so assuming there's no restriction on the layer HID goes over you could implement HIDU2F support on it in JS right now.

**Comment by gfwilliams** [comment]
No response - closing.
