### ISSUE TITLE
Graphics.clear should reset font/align/etc?

### ISSUE THREAD

**Issue by gfwilliams** [espruino/Espruino#1615]
It's always a bit frustrating if you're doing Graphics and you set to a large font - then next time around the code that used to draw a small font now draws it large.

I think maybe `.clear()` should reset the font options? But probably not color or rotation.

Any thoughts?

**Comment by gfwilliams** [comment]
@IrregularShed @MaBecker do you have any feelings about this either way?

**Comment by IrregularShed** [comment]
I'm not sure. There's arguments both ways, depending on how the graphics are being used - if I'm creating a display with one value being reported it's handier to not have to think about the font size each iteration, whereas if I were to have one large value and two smaller ones (for example) I can see how the automatic reset would help.

Any mileage in having an optional parameter passing through flags? That might be a little excessive, I guess.

**Comment by gfwilliams** [comment]
I think an optional parameter might be overkill, but maybe `g.reset()` or something that would set all these items to their default values would be better? Doing `g.clear();g.reset()` isn't the end of the world, but it's a lot better than having to reset fonts/etc manually each time.

**Comment by IrregularShed** [comment]
Seems reasonable!

**Comment by wilberforce** [comment]
remember you could chain...   `g.clear().reset()`

How about  `g.clear(1)`

**Comment by gfwilliams** [comment]
@wilberforce thanks - `g.clear(1)` sounds like a perfect solution

**Comment by MaBecker** [comment]
g.clear(1) - perfect for me too.
