### ISSUE TITLE
httpCRq and related class documentation incomplete

### ISSUE THREAD

**Issue by SpenceKonde** [espruino/Espruino#1620]
http://www.espruino.com/Reference#httpCRq 

Lists 4 methods/fields - drain, end, error and write. 

It apparently also has a headers field which is not mentioned in the reference. It seems likely that other fields of this and/or httpCRs/httpSRq/httpSRs may also be undocumented, as none of the others mention any facility for interacting with headers. 

http://forum.espruino.com/conversations/321747/

**Comment by gfwilliams** [comment]
This can now fixed by adding lines like:

```
/*JSON{
    "type" : "property",
    "class" : "httpCRs",
    "name" : "headers",
    "generate" : false,
    "return" : ["JsVar", "A map of header name -> value" ]
}
Some more info here
*//*Documentation only*/
```
