### ISSUE TITLE
Get static web content hosted beside Espruino firmware

### ISSUE THREAD

**Issue by T94T** [espruino/Espruino#1638]
Is there a way to put some web content on the free flash space? And serve it over port 80?

**Comment by MaBecker** [comment]
Better post this @ Espruino forum

http://forum.espruino.com

**Comment by gfwilliams** [comment]
Yeah - we try to keep GitHub just for bugs/issues with test cases, or we just get spammed with the same questions over and over.

It's been answered a few times already on the forum I believe, but you just need to use the 'Storage' module: http://www.espruino.com/Reference#Storage

You can then just read the 'file' out of flash and write it to the connection when needed.
