### ISSUE TITLE
extend Wifi.connect() with channel for quicker connects

### ISSUE THREAD

**Issue by MaBecker** [espruino/Espruino#1640]
Connect to AP can speed up when adding the channel of the AP.

**Comment by MaBecker** [comment]
Ups, this is already implemented - sorry

**Comment by gfwilliams** [comment]
Did you intend to reopen this again?

**Comment by MaBecker** [comment]
Yes - because first I mixed it up with Wifi.startAP() which already allow to add channel.

Will check this for AT commands too.
