### ISSUE TITLE
Add filesystem support to STM32F4DISCOVERY

### ISSUE THREAD

**Issue by swineone** [espruino/Espruino#1645]
I'm opening this issue just to request that filesystem support be added to STM32F4DISCOVERY. I've enabled and tested it, and it's working just fine. A pull request will follow.

**Comment by swineone** [comment]
Is it possible to merge this? It's necessary to use SD cards with STM32F4DISCOVERY.

**Comment by gfwilliams** [comment]
Ahh, sorry - I got this confused with #1644 since it also appeared to fix those changes as well.
