### ISSUE TITLE
Neopixels fail on nRF5 SDK 15

### ISSUE THREAD

**Issue by urish** [espruino/Espruino#1655]
Calling `require("neopixel").write` freezes the CPU. From quick investigation, it seems like the signature for [i2s_ws2812b_drive_handler](https://github.com/espruino/Espruino/blob/85bb03d503cb661b73c64330fb8211eb5a543e3a/targets/nrf5x/i2s_ws2812b_drive.c#L15) has changed and should read:

```
static void i2s_ws2812b_drive_handler(nrfx_i2s_buffers_t const *p_released, uint32_t status)
```

thus, the [current method of busy-waiting](https://github.com/espruino/Espruino/blob/85bb03d503cb661b73c64330fb8211eb5a543e3a/targets/nrf5x/i2s_ws2812b_drive.c#L132) simply blocks forever.

**Comment by gfwilliams** [comment]
I just spotted a commit which says it fixes neopixel for nRF52840 (which would be SDK15):

https://github.com/espruino/Espruino/commit/ff6da1b1d1d1c4b789d3c67f16428793aa6b9cfa

So I'm pretty sure this was fixed in 2020
