### ISSUE TITLE
Slow to interpreter toString function on large Arrays 

### ISSUE THREAD

**Issue by HongxuChen** [espruino/Espruino#1660]
When trying to interpreter `toString` on a large array, Espruino may perform quite slowly.

```javascript
var a = new Array(100000)
var s = a.toString()
```

On my Ubuntu 18.04 x86_64, the execution of first line is fast, however the second line may take nearly 7s.

As a comparison, [mujs](https://github.com/ccxvii/mujs) took 0.34s, and JSC took 0.01s.

**Comment by gfwilliams** [comment]
Looks like this is jsvArrayJoin - it should be able to do better by keeping an iterator for the output string
