### ISSUE TITLE
No DFU zip for releases for Nordic Thingy:52

### ISSUE THREAD

**Issue by Karolis92** [espruino/Espruino#1667]
There are no zip's for stable releases to flash Thingy using DFU, there are only hex files.

**Comment by gfwilliams** [comment]
Thanks for letting me know - I'll get that sorted.

For the moment you can use the cutting edge builds from http://www.espruino.com/binaries/travis/master/

**Comment by gfwilliams** [comment]
Sorted: http://www.espruino.com/Download#thingy52
