### ISSUE TITLE
NRF.requestDevice throws timeout error

### ISSUE THREAD

**Issue by gurchk** [espruino/Espruino#1669]
In firmware version 2v03 on the board MDBT42Q a NRF.requestDevice throws the error

```
Error: clearTimeout(undefined) not allowed. Use clearTimeout() instead.
```
Tried version 2v01; works like a charm

**Comment by gfwilliams** [comment]
Thanks for this report - it should now be fixed if you try a 'cutting edge' build in a few minutes.

You should still be able to use `NRF.findDevices` on 2v03 if you need to use it.
