### ISSUE TITLE
setFontBitmap not working with NO_VECTOR_FONT

### ISSUE THREAD

**Issue by fanoush** [espruino/Espruino#1671]
Due to this
https://github.com/espruino/Espruino/blob/6ef2123f12c3c2f3b82fb977e82e77ef6c37cc2f/libs/graphics/jswrap_graphics.c#L779
one cannot select builtin 4x6 bitmap font as `setFontBitmap` is just alias to `jswrap_graphics_setFontSizeX(parent, JSGRAPHICS_FONTSIZE_4X6, false)`
and the call throws this  exception. The exception and ifdef/else/endif should perhaps be restructured to something like
```
#ifdef NO_VECTOR_FONT
  if (size>0) jsExceptionHere(JSET_ERROR, "No vector font in this build");
  else {
#endif
  if (checkValid) {
    if (size<1) size=1;
    if (size>1023) size=1023;
  }
  if (gfx.data.fontSize == JSGRAPHICS_FONTSIZE_CUSTOM) {
    jsvObjectRemoveChild(parent, JSGRAPHICS_CUSTOMFONT_BMP);
    jsvObjectRemoveChild(parent, JSGRAPHICS_CUSTOMFONT_WIDTH);
    jsvObjectRemoveChild(parent, JSGRAPHICS_CUSTOMFONT_HEIGHT);
    jsvObjectRemoveChild(parent, JSGRAPHICS_CUSTOMFONT_FIRSTCHAR);
  }
  gfx.data.fontSize = (short)size;
  graphicsSetVar(&gfx);
#ifdef NO_VECTOR_FONT
  }
#endif
```
Or is there another way? I am using custom fonts and then want to switch to builtin font so I tried to use setFontBitmap()

**Comment by gfwilliams** [comment]
Thanks! Just fixed I hope :)
