### ISSUE TITLE
Add I2S support for ESP8266

### ISSUE THREAD

**Issue by Piruzzolo** [espruino/Espruino#1693]
It would be great!

**Comment by gfwilliams** [comment]
What do you actually want the support for? As far as I remember the `neopixel` library uses it under the hood, but trying to actually do audio could be problematic with Espruino's low processing speed.

**Comment by Piruzzolo** [comment]
To get sound samples from a i2s mic.

To make it fast, it should call a device-specific C function, I guess. Then offer a common API to access i2s

**Comment by MaBecker** [comment]
> To get sound samples from a i2s mic.
> 
> To make it fast, it should call a device-specific C function, I guess. Then offer a common API to access i2s

Are you planing to implement i2s as c-code?

**Comment by MaBecker** [comment]
> @MaBecker I dubt I could implement it properly, if I tried. But maybe someone has already done the low level work. Need to google a bit

Well, try and find out :)

**Comment by MaBecker** [comment]
Look's like no one likes to jump in to add this and there haven't been  further request in the forum.
