### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [espruino/Espruino#1695]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`README_Building.md`](https://github.com/espruino/Espruino/blob/83615d6a27fff227187bcae3ec3c933f14f88a50/README_Building.md). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by gfwilliams** [comment]
Thanks - not sure how I missed this at the time.
