### ISSUE TITLE
Espruino build is broken  for devices without LCD

### ISSUE THREAD

**Issue by MaBecker** [espruino/Espruino#1715]
Build Espruino on and for  Mac OS X  for quick test cycles

On my way to build Espruino

BOARD=LINUX RELEASE=1 make clean 
BOARD=LINUX RELEASE=1 make 

    libs/graphics/graphics.c:132:27: error: use of undeclared identifier 'LCD_WIDTH'
       gfx->data.clipRect.x2 = LCD_WIDTH-1;
                          ^
    libs/graphics/graphics.c:133:27: error: use of undeclared identifier 'LCD_HEIGHT'
     gfx->data.clipRect.y2 = LCD_HEIGHT-1;

Any hint how to fix this?

Like to to test the Bresenham  Ellipse version over the weekend.

**Comment by MaBecker** [comment]
Oh, same for ESP8266 boards

**Comment by MaBecker** [comment]
Just commented the clip section, so I can build Espruino 

![Bildschirmfoto 2019-12-06 um 18 56 47](https://user-images.githubusercontent.com/15932646/70344515-3398da00-185a-11ea-8249-b3f1fba6e6c2.jpg)



![Bildschirmfoto 2019-12-06 um 18 58 47](https://user-images.githubusercontent.com/15932646/70344644-73f85800-185a-11ea-8206-bf3ae03a8e9f.jpg)

So I am ready for coding ;-)

**Comment by MaBecker** [comment]
A first test with javascript  ;-)

![Bildschirmfoto 2019-12-06 um 19 11 57](https://user-images.githubusercontent.com/15932646/70345415-4f9d7b00-185c-11ea-8aef-afeaacfcb004.jpg)

**Comment by gfwilliams** [comment]
Thanks!
