### ISSUE TITLE
parseInt("0b",16)

### ISSUE THREAD

**Issue by gfwilliams** [espruino/Espruino#1722]
Not sure how this one slipped through, but it looks like even if you explicitly set the radix, Espruino can be tripped up:

```
// espruino
>parseInt("0b",16)
= 0
// node.js
> parseInt("0b",16)
= 11
```

**Comment by MaBecker** [comment]
Just tested, only wrong for "0b" and "0B"

"0a,0c-0f" and "0A,0C-0F"  are correct

**Comment by MaBecker** [comment]
>parseInt("0x0b",16);
=11

https://github.com/espruino/Espruino/blob/3251c043d6afad2e44f219b6c003ed4555faa4c9/src/jsutils.c#L122-L128

**Comment by gfwilliams** [comment]
Wow, this is a mess: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt

Sometimes I hate JS:

```
parseInt("0b01",2)
0
parseInt("0b01")
0
Number("0b01")
1
> parseInt("066")
66
> Number("066")
66
> 066
54
```

So `0x...` is actually a special-case for parseInt
