### ISSUE TITLE
Allow "of" as var name

### ISSUE THREAD

**Issue by mfikes** [espruino/Espruino#1729]
```
>function of() {}
Uncaught SyntaxError: Got ?[198] expected ID
 at line 1 col 10
function of() {}
         ^
```

But in Node, JavaScriptCore, etc., this is allowed.

> Note: This issue can arise if Google Closure Compiler chooses to shorten the name of a symbol to `of`.

**Comment by gfwilliams** [comment]
Sorry, I've just spent a while looking at this, and it's total rabbit hole. Looks like there are only a few reserved words right now where this is an issue (let,of,static?) but implementing it in Espruino will slow execution down across the board, complicate the code, and increase code size quite a bit.

I'll make sure I document this on http://www.espruino.com/Features though
