### ISSUE TITLE
ESP32 NRF.updateServices error

### ISSUE THREAD

**Issue by mfikes** [espruino/Espruino#1730]
Following the example in the [NRF.updateServices documentation](https://www.espruino.com/Reference#l_NRF_updateServices), directly calling `updateServices` instead of as a result of a button push:

```
>NRF.setServices({
:  0xBCDE : {
:    0xABCD : {
:      value : "Hello",
:      maxLen : 20,
:      notify: true
:    }
:  }
:});
=undefined
>NRF.updateServices({
:    0xBCDE : {
:      0xABCD : {
:        value : "World!",
:        notify: true
:      }
:    }
:  });
FIXME
Uncaught Error: Unable to find service with UUID 0xabcd
 at line 8 col 4
  });
   ^
```

**Comment by mfikes** [comment]
The [`FIXME` output](https://github.com/espruino/Espruino/blob/dc10d8934117f3e15a7612baaae7afed26b0e9f6/libs/bluetooth/bluetooth_utils.c#L257) is indicating that this is not yet implemented for the ESP322.

**Comment by alfierivera** [comment]
Any ideas of how much effort will this take to be implemented? I might be able to sponsor such a feature, as I need it for an experiment I'm making.

**Comment by gfwilliams** [comment]
For me personally to do it I'd imagine between 0.5 and 1 day, so £500-1000 ish. Others may be cheaper though.

@mfikes if you're interested feel free to post up what you'd be willing to do it for. I have way too much work on my plate right now so if you're interested please don't have any concerns about stealing work from me :)

**Comment by MaBecker** [comment]
@mfikes have you been working on this. If yes please share - Thanks.

**Comment by mfikes** [comment]
@MaBecker No, I have not been working on this.

**Comment by MaBecker** [comment]
Would you like too?
