### ISSUE TITLE
analogWrite for built-in LED fails on serial console

### ISSUE THREAD

**Issue by bartmichu** [espruino/Espruino#1732]
Hello, I'm using Espruino Pico with 2v04.

This sample code works fine when uploaded via npm, but fails with ```ERROR: Pin B2 is not capable of PWM Output``` when executed on serial console.

```
analogWrite(LED1, 0.5);
```

I know I can use ```{soft: true}``` as a workaround, but this issue is more about inconsistent outcome.

**Comment by bartmichu** [comment]
After more testing I see that this is not the case, but I'm hitting on something else that I will describe in a separate issue.

**Comment by gfwilliams** [comment]
Ok, thanks! Do you have a link to the new issue?

**Comment by gfwilliams** [comment]
ahh, got it: https://github.com/espruino/EspruinoTools/issues/112#issuecomment-569140157
