### ISSUE TITLE
Problems with Graphics.createArrayBuffer size

### ISSUE THREAD

**Issue by defaude** [espruino/Espruino#1761]
First of all: Thanks for this great project :)

So I've been toying around a bit with [this board](https://github.com/Xinyuan-LilyGO/TTGO-T-Display) that features a 240x320 18/16/12 Bit color display. I wanted to prepare a module very much in the spirit of [the one for the ST7565 display](https://www.espruino.com/ST7565).

However: When I tried to pass the width, height and bits-per-pixel values into `Graphics.createArrayBuffer` it fell apart with the error message "Invalid length for ArrayBuffer".

I've looked up this error message and found [these lines](https://github.com/espruino/Espruino/blob/3bd026c239985f578baca1525e24acafc734b3e9/src/jswrap_arraybuffer.c#L199-L206). First of all, the second `if` will never trigger because the condition is already included in the first one ;)

But my actual question is: Why is there the upper bound of `JSV_ARRAYBUFFER_MAX_LENGTH` (i.e. 65535) in the first place? Sure, there are unsigned ints flying around everywhere but **could** we possibly replace those with unsigned long values?

Or can you think of a potential solution for my initial "I want to use this display" problem? :)

I mean... would be even better to create a board definition including a LCD instance fit for this display here in the C world, anyway - I just don't know enough about the inner workings of this project (yet) so I think I might not be able to provide something of value...

**Comment by gfwilliams** [comment]
Hi - it's basically because of this: http://www.espruino.com/Internals

Variables are packed into 16 byte chunks, and arraybuffers are no exception - but that means there are only 2 bytes left for size, hence the max 65535 size. It's not usually an issue as most boards don't have more than 64k RAM.

However it is possible to define a memory area in RAM and then use that directly I believe.
