### ISSUE TITLE
Bangle.js and FW 378 doesn't boot

### ISSUE THREAD

**Issue by ra100** [espruino/Espruino#1767]
I've flashed espruino_2v04.378_banglejs.zip to bangle.js but after restart it stays on Bangle.js logo, and only thing I can do is to flash some other FW.
Flashing to .85 works fine.

**Comment by gfwilliams** [comment]
Have you tried installing completely new JS from https://banglejs.com/apps/ (about -> install default apps).

In recent versions I made some big changes to Storage, so previously uploaded apps would be lost.

**Comment by ra100** [comment]
So I should first install new apps and then update the firmware?

**Comment by gfwilliams** [comment]
No, you should be able to just install the firmware and the reflash.

Did you try this: https://www.espruino.com/Bangle.js#resetting-without-loading-any-code

It'll stop Espruino from loading any files at boot, which should allow you to program it just fine.

Worst case you could do `require("Storage").eraseAll()` on the old firmware, and then write new Bangle.js firmware - but that shouldn't be required

**Comment by ra100** [comment]
Ah, ok, now I get it, thanks.

**Comment by gfwilliams** [comment]
I think this would probably be fixed by https://github.com/espruino/Espruino/issues/1766 when implemented too
