### ISSUE TITLE
improvements for the  new bitmap_font_6x8.c

### ISSUE THREAD

**Issue by MaBecker** [espruino/Espruino#1770]
Some chars might look better when they are centered, eg  ! " , ; : ` ( )  |

part 1  has correct values

![part_1](https://user-images.githubusercontent.com/15932646/76057400-bcb6ce80-5f79-11ea-816e-3824fc8d873c.png)

part 2 needs some corrections, will come up with a list

![part_2](https://user-images.githubusercontent.com/15932646/76057421-c5a7a000-5f79-11ea-8de4-80dcb274fd1f.jpeg)

```
// ugly code but does it's work
function drawCharTable(p) {
    var cc = 33, sf = 2, x = 0, y = 50, yo = 1, i = 33;
    s = p ?  8 : 2;e = p ? 16 : 8; yo = 1;
    g.clear().setFont("6x8",sf);
    g.drawString("part "+(p+1), 80, 20);
    g.drawString(" 0123456789ABCDEF",x,y);
    for (i = s;i<e;i++){ g.drawString(i.toString(16).toUpperCase(),x,y+8*sf*yo);yo++;}
    cs = p ?  128 : 32; ce = p ? 255 : 127; yo = 1;x =0;
    for (row = 0; row < 16; row++) {
        sfcc = " ";
        console.log(cs,ce);
        if (cs > ce) break;
        for ( col = 0; col < 16;col++ ) {
            sfcc += String.fromCharCode(cs);
            cs++;
        }
        g.drawString(sfcc,x,y+(row+1)*8*sf);
    }
}

//drawCharTable(0);
drawCharTable(1);
```

**Comment by gfwilliams** [comment]
Ok, thanks! The font itself is ISO8859-1/windows-1252 (which I believe is actually the 'default' 8 bit encoding for web browsers) whereas the Dylex font used ISO10646 (which I believe is UTF-16 - so just the bottom-most 256 characters of the 0-65535 range).

Since `String.charCodeAt` returns UTF-16, simple translation from the web browser would be using the ISO10646 codepage.

So it looks like we could just convert the ISO8859-1 font to ISO10646-1, and there may be ways to programatically do this (which might save you some hard work!)

**Comment by gfwilliams** [comment]
Actually: https://www.cl.cam.ac.uk/~mgk25/unicode.html#ucs

> What are UCS and ISO 10646?
> The UCS characters U+0000 to U+007F are identical to those in US-ASCII (ISO 646 IRV) and the range U+0000 to U+00FF is identical to ISO 8859-1 (Latin-1)

So it may be that the character positions are actually ok!

**Comment by MaBecker** [comment]
> So it may be that the character positions are actually ok!

I think so too , but it’s a big difference in look and feel comparing old with new font especially for clocks

**Comment by gfwilliams** [comment]
> it’s a big difference in look and feel comparing old with new font especially for clocks

Yes... However the character spacing should at least be the same.

Talking of which I guess it might be nice to add a `6x8v` mode where certain 'thin' characters were actually rendered thin.

**Comment by MaBecker** [comment]
![25EC8D16-0246-4900-81A3-37D9E284C9FD](https://user-images.githubusercontent.com/15932646/76076454-3319f780-5f9f-11ea-841b-895828987800.jpeg)

**Comment by MaBecker** [comment]
Do you see the spacing

**Comment by gfwilliams** [comment]
Of the colon? Yes, that needs to change. Stuff like that should be pretty easy to tweak with: https://github.com/espruino/Espruino/blob/master/libs/graphics/bitmap_font_6x8.c

**Comment by MaBecker** [comment]
> Of the colon? Yes, that needs to change

Yes, this is what I mean with:

> Some chars might look better when they are centered, eg ! " , ; : ` ( ) |

**Comment by gfwilliams** [comment]
See most recent update ^^^

**Comment by MaBecker** [comment]
Wow, you are to fast for me 😁

**Comment by MaBecker** [comment]
> So it may be that the character positions are actually ok!

* Compared codes and chars with https://ascii.cl/htmlcodes.htm just a few changes are needed

* Circumflex or accent circonflexe (â, ê, î, ô, û) are very hard with 6x8 https://en.wikipedia.org/wiki/French_orthography

*  add char code values 

* update ` : "\_XX__"

* update ´ :  "__XX\_"

* update ^ : "_XXX_"

Have you thought about  a translation for values higher than 255, like 338  to 140?

**Comment by MaBecker** [comment]
latest version, might help to check

![6x8_with_corrections](https://user-images.githubusercontent.com/15932646/76193466-584b7780-61e4-11ea-99be-462e3493ba0b.jpg)

**Comment by gfwilliams** [comment]
> Have you thought about a translation for values higher than 255, like 338 to 140?

The issue is that Espruino Strings can't support anything outside the 0-255 range. If there are unused characters then sure, we can use them for other stuff - but it'd need to be documented because if nobody knows they are there it's not useful :)

Perhaps this now means that the unicode converter in the IDE should stop doing the strange UTF-8 stuff, and should just convert to ISO 10646 (first 8 bits). I could update the terminal to work in a similar way as well.

**Comment by MaBecker** [comment]
I had a lookup table in mind to handle this.

**Comment by gfwilliams** [comment]
Where would the lookup table be though? In the Web IDE before upload? I'd have to add it to BangleApps as well...

**Comment by MaBecker** [comment]
Not sure, but maybe  this is too much effort for less than a hand full of chars ....

And just keep it in mind to add it to the Fonts documentation page.
