### ISSUE TITLE
Bangle.js E.showMenu(menu); glitch an improvement 

### ISSUE THREAD

**Issue by sebi5361** [espruino/Espruino#1773]
I find `E.showMenu(menu);` great.

I have noticed a small glitch: with the up, right and bottom arrows displayed on the right, if a text line is too long, its last character will mess up the last column of the screen when scrolling up and down.

Additionally a nice improvement would be to scroll long lines automatically to the left when highlighted, so that they can be read completely, don't you think?

This feature could also exist in the launcher where it is difficult to read app names as they are truncated on the right.

**Comment by gfwilliams** [comment]
Sounds like a plan as long as it doesn't slow down the menu rendering too much for normal every-day cases.

I'm open to PRs ;) https://github.com/espruino/Espruino/blob/master/libs/js/banglejs/E_showMenu.js

**Comment by sebi5361** [comment]
Indeed it might slow down the rendering... so not worth it.

And to avoid such a glitch:
![screenshot](https://user-images.githubusercontent.com/18078043/76361634-b466e680-631f-11ea-8faf-4d2a87c3f82f.png)
one just has to take care that the text doesn't exceed 19 characters or use `.substring(0, 19);`.
Am closing this issue.
