### ISSUE TITLE
E.getTemperature() is returning garbage on 2v05.425 on Pixl.js

### ISSUE THREAD

**Issue by nikmartin** [espruino/Espruino#1788]
After upgrading to 2v05.425 on my Pixl.js, calls to `E.getTemperature()` now return numbers like: `1585406286592`, `1585406286624` etc. I'm making the call like: `console.log(E.getTemperature());`

**Comment by nikmartin** [comment]
Also, I noticed that the output from getTemperature() looks eerily like a timestamp, becaaue now it's outputting `1585413626592`

**Comment by gfwilliams** [comment]
Thanks for this - just spotted what the problem was!

It's only been like it for a few commits, since I made a tweak for the new Puck.js
