### ISSUE TITLE
Blockly and loading js library

### ISSUE THREAD

**Issue by davidbozo** [espruino/Espruino#1793]
Hi! I'm working on some additional blocky block. Some of them to work require more then a few line of code to work.
Where can i put the most code? To avoid to genarate a lot of code with blockly.
Should i use the module system an require() it when generating the code?
Or there is a place where i can dump the code and it will be loaded always?
(I would prefer not to write native code and js wrapper.)

**Comment by gfwilliams** [comment]
You could use the module system, or you can actually just ensure that you only add the code if your blocks are used inside blockly. For instance: 

https://github.com/espruino/EspruinoWebIDE/blob/gh-pages/blockly/blockly_nordic_thingy.js#L88

It feels like that'd be by far the tidiest solution
