### ISSUE TITLE
Array.sort() compare function doesn't work with small floats

### ISSUE THREAD

**Issue by singintime** [espruino/Espruino#1798]
## What happens

Trying to sort an array of floats with absolute values < 1 "the usual way" (compare function returning the numbers' difference) doesn't actually yield a sorted array.

## Steps to reproduce

1. Create an array of small floats (absolute values less than 1)
2. Call `array.sort((a, b) => a - b)`

Expected result: the sorted array
Actual result: the array is not sorted

I encountered this issue in the emulator, I'm not sure if it's present on the boards too.

Apparently, in order for the sorting to work, the values returned by the compare function need to be integers, or at least with values greater than 1. Doing `array.sort((a, b) => (a - b) / Math.abs(a - b))` successfully sorts the array. It's not the documented behavior, though, and it's not how other JavaScript interpreters usually work.

**Comment by gfwilliams** [comment]
Ahh, thanks for the report - that's great! Just fixed :)
