### ISSUE TITLE
Use of multiple setWatch cause unpredictable output on nRF PPI

### ISSUE THREAD

**Issue by sleuthware** [espruino/Espruino#1810]
Sun 2020.05.03

First spotted two months ago using MDBT42Q with code examples

[Tutorial example output anomaly using low level access PPI](http://forum.espruino.com/conversations/344453/)
Home >> Official Espruino Devices >> Puck.js, Pixl.js and MDBT42

And today by fbedussi using Bangle with code and video

[Bug in setWatch?](http://forum.espruino.com/comments/15250842/)
Home >> Official Espruino Devices >> Bangle.js

**Comment by gfwilliams** [comment]
Please stop posting issues with no steps to reproduce.
