### ISSUE TITLE
Anomaly in deployed module corrupts user namespace global scope

### ISSUE THREAD

**Issue by sleuthware** [espruino/Espruino#1811]
Sun 2020.05.03

I believe this to be specific to the WiFi module at this time, although knowing I've
had intermittent issues for some time, every module should now be suspect.

It is likely to be how the previous declaration for what is now minified to var c was. Should every module be in it's own closure? Worst case, might only need a modification to how minification works or it's internal rules.

[Multiple occurances during a trace() output](http://forum.espruino.com/conversations/346667/)
Home >> Official Espruino Devices >> General

**Comment by gfwilliams** [comment]
To post issues, you need to post something that's actually wrong with clear steps to reproduce.

Just posting a link to a multi-page rant on a forum just pisses everyone off.
