### ISSUE TITLE
Binary download of file from IDE corrupted

### ISSUE THREAD

**Issue by tomgidden** [espruino/Espruino#1815]
I uploaded an 8x8 1-bit PNG via the IDE, consisting of a diagonal line from top-right to bottom-left.  ![8x8 1-bit PNG](https://user-images.githubusercontent.com/1640098/81243137-e6868300-9006-11ea-9c28-841f099325a3.png)

`storage.read()` reports the expected bytes: 8,8,1,1,2,4,8,16,32,64,128 -- width, height, bpp, and then the eight bytes.

However, when downloaded using the "three-disc" icon in the IDE, I get 8,8,1,1,2,4,8,16,32,64,**194**,128 -- looks like UTF-8's **0xc2** prefixing the high-bit value for the last line.

**Comment by gfwilliams** [comment]
Thanks for tracking this down to such a neat test case :)

This was an issue with the Web IDE / EspruinoTools - the download was going fine, it was just the implementation of the file save dialog!
