### ISSUE TITLE
jswrap_banglejs_setHRMPower description talks about 'GPS' event instead of 'HRM' event

### ISSUE THREAD

**Issue by ikkala** [espruino/Espruino#1825]
https://github.com/espruino/Espruino/blob/9d6370cbbfb2df5b1102b7847da4adacb030da2f/libs/banglejs/jswrap_bangle.c#L1157

> When on, data is output via the `GPS` event

Should be:

> When on, data is output via the `HRM` event

?

**Comment by gfwilliams** [comment]
Thanks! Just fixed :)
