### ISSUE TITLE
DNS is not cleared after RSTn is triggered for a WIZ550io or WIZ850io

### ISSUE THREAD

**Issue by MaBecker** [espruino/Espruino#1830]
Testing WIZ550io and  WIZ850io, both bases on chip W5500.

A reset via RSTn pin should clear all entries 

```
>digitalPulse(D15,0,1);
// wait 500ms
>eth.getIP()
={
  ip: "0.0.0.0",
  subnet: "0.0.0.0",
  gateway: "0.0.0.0",
  dns: "192.168.194.1",
  mac: "00:00:00:00:00:00"
 }
```

https://github.com/Wiznet/ioLibrary_Driver/issues/100

**Comment by MaBecker** [comment]
Should we clear this manually if `ip: "0.0.0.0"`?

**Comment by gfwilliams** [comment]
Just do a check in `eth.getIP`? I guess we could do that...

Does it actually cause any problems?

**Comment by MaBecker** [comment]
No problem, just a strange output.

**Comment by MaBecker** [comment]
There was no response from Wiznet until now.
