### ISSUE TITLE
"ram" functions broken in latest nightly

### ISSUE THREAD

**Issue by nebbishhacker** [espruino/Espruino#1856]
Functions that use the "ram" directive appear to be broken in 2v05.168. I first noticed the issue in the morphing clock app, but I can reproduce it using the linux build of espruino as well.

Minimal test case:

```
require("Storage").write("foo.js", `
function foo() {
  "ram";
  return 42;
}

print(foo());
`);

load("foo.js");
```

Output:

```
Uncaught ReferenceError: "printurn" is not defined
 at line 1 col 2
;printurn 42;
 ^
in function "foo" called from line 7 col 11
print(foo());
          ^
```

**Comment by gfwilliams** [comment]
Wow... ok, thanks. I'll look into this ASAP
