### ISSUE TITLE
Graphics.asImage() missing buffer when bpp != 8

### ISSUE THREAD

**Issue by nebbishhacker** [espruino/Espruino#1863]
The buffer field is missing from the output of Graphics.asImage when bpp != 8 and msb = false.

Test case:
```
let g = Graphics.createArrayBuffer(8,8,1);
let image = g.asImage();
print(image);
```
Output:
```
{ "width": 8, "height": 8 }
```
Expected output:
```
{ "width": 8, "height": 8, "bpp": 1,
 "buffer": new ArrayBuffer(8)
}
```

Looks to be the root cause of http://forum.espruino.com/conversations/349170/#comment15347262

**Comment by gfwilliams** [comment]
Argh, sorry - looks like it should have fallen through to copying pixels and it somehow didn't
