### ISSUE TITLE
Math.floor returns values equal to null

### ISSUE THREAD

**Issue by mfikes** [espruino/Espruino#1865]
In 2v06:

```
>Math.floor(0.5) == null
=true
>Math.floor(1.5) == null
=false
```

Both results should be `false`

**Comment by MaBecker** [comment]
Not sure about this, check the examples on this MDN page:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Equality

**Comment by mfikes** [comment]
@MaBecker On that page, under "Comparison with type conversion" it has this example:

```
0 == null;            // false
```

Did you have something else in mind?

**Comment by MaBecker** [comment]
Ups, still on 2v05

**Comment by mfikes** [comment]
FWIW, the issue was originally noticed on 2v04... but I checked to see that it is still reproducible on 2v06.

**Comment by gfwilliams** [comment]
Thanks - just checked into this and:

```
>trace(Math.floor(0)) 
#33[r0,l1] Double 0 
>trace(0)
#31[r0,l1] Integer 0 

>0==null
false
>0.0==null
true
```

So the issue appears to be with comparison of floating point numbers with null, rather than Math.floor itself
