### ISSUE TITLE
Setting prototypes can overwrite Object.prototype

### ISSUE THREAD

**Issue by nebbishhacker** [espruino/Espruino#1875]
Creating a plain JS object and then setting its prototype via `__proto__` or `setPrototypeOf` will overwrite `Object.prototype`.

Test case:
```
let base = {foo: 42};
let child = {};
Object.setPrototypeOf(child, base);
print(child.__proto__ == Object.prototype);
print(Object.prototype);
```

Expected result:
```
>false
>{ }
```

Actual result:
```
>true
>{ "foo": 42 }
```

**Comment by gfwilliams** [comment]
Wow, thanks - I'll have a look into that.
