### ISSUE TITLE
What about adding something  to .gitignore to allow custom board files?

### ISSUE THREAD

**Issue by MaBecker** [espruino/Espruino#1896]
For my project I have different board files with different settings, it would be nice to permanently ignore them.

A simple way to ignore them is to add a prefix or a postfix to the board file name and create a new entry in .gitignore.

I would go for a postfix  like **_CUST**  and an entry like this **/board/*_CUST.py** for .gitignore.

**Comment by MaBecker** [comment]
Great - Thanks!

**Comment by gfwilliams** [comment]
Just added for `_CUSTOM.py` - but IMO this sort of thing really isn't worth doing in general.

Mainly because without documentation it's effectively useless - I seriously doubt anyone except you will end up using this :)

**Comment by MaBecker** [comment]
If you like I can  document this in  e.g. https://github.com/espruino/Espruino/blob/master/README_BuildProcess.md or where ever you suggest :)

**Comment by gfwilliams** [comment]
That'd be great actually - in https://github.com/espruino/Espruino/blob/master/README_BuildProcess.md#board-definition-file-- ?

Mentioning the custom board name addition would be really neat as well.
