### ISSUE TITLE
Bluetooth 5 planned?

### ISSUE THREAD

**Issue by BaloMueller** [espruino/Espruino#1903]
Hi everyone!

Awesome project, I love it and am using it for years!

Just a request: As the Nordic nRF52823 is capable of Bluetooth 5, do you have planned to implement it? I would like to use the long range feature.

Thanks
Balomueller

**Comment by gfwilliams** [comment]
Hi - this is something that's been covered in the forum a bit, for instance: http://forum.espruino.com/conversations/303958/

But basically:

* You can build an SDK15 version of Espruino right now, which supposedly supports Bluetooth 5
* nRF52832 doesn't actually support any of the long range features of Bluetooth 5, so literally all SDK15 gets you is higher resource usage (so less RAM&Flash available for your code).
* nRF52840 *does* support long range stuff, and while the features aren't exposed in Espruino right now, when I do start selling nRF52840 based devices I'll add it (it's pretty simple), or maybe someone else will do it at some point
