### ISSUE TITLE
boot failed

### ISSUE THREAD

**Issue by vidalouiswang** [espruino/Espruino#1917]
![image](https://user-images.githubusercontent.com/26226049/90608965-ef0d6d00-e235-11ea-8880-11288a98169b.png)

I used `require("Storage").write` before this happened. Then it will reboot every 5 seconds and give no response to Serial input, only flash firmware can make it back.

**Comment by vidalouiswang** [comment]
It will shows 
```Storage is corrupt.
Erasing Storage Area...
after firmware flashed.

**Comment by MaBecker** [comment]
Hi can you provide a code snippet to reproduce the error?

**Comment by MaBecker** [comment]
This can also caused by trying to read stored coding with  newer Espruino version. In this case flash_erase and then flash again. Can you still reproduce the error with the latest Espruino version?

**Comment by vidalouiswang** [comment]
> This can also caused by trying to read stored coding with newer Espruino version. In this case flash_erase and then flash again. Can you still reproduce the error with the latest Espruino version?

I dont use this code any more and I haven't see this error in the 2.08
