### ISSUE TITLE
extend .gitignore to ignore aditional /targetlibs/nrf5x_15 files 

### ISSUE THREAD

**Issue by MaBecker** [espruino/Espruino#1931]
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	targetlibs/nrf5x_15/config/
	targetlibs/nrf5x_15/license.txt

should this be added to .gitignore?

**Comment by gfwilliams** [comment]
Sounds good - just FYI I don't think there's a great need to file an issue and PR for stuff like this. Just the PR is fine

**Comment by MaBecker** [comment]
ok
