### ISSUE TITLE
Regex /[.]/

### ISSUE THREAD

**Issue by gfwilliams** [espruino/Espruino#1948]
full stop in `[]` shouldn't need escaping

```
"he.lo".split(/[\.]/)
[ "he","lo" ]

"he.lo".split(/[.]/)
// espruino: [ "", "", "", "", "", "" ]
// expected: [ "he","lo" ]
```

**Comment by MaBecker** [comment]
Wow never used it like this, good to know.

always using this one
```js
>"he.lo.Espruino".split('.')
=[
  "he",
  "lo",
  "Espruino"
 ]
> 
```

**Comment by gfwilliams** [comment]
I was trying to split up a version number with `"2v08.123".split(/[v.]/)` :) It works if you escape it, but then eslint gets unhappy because it says you're escaping something that doesn't need escaping
