### ISSUE TITLE
Math.acos() implementation is wrong for negative inputs

### ISSUE THREAD

**Issue by Franzo-** [espruino/Espruino#1950]
The function `Math.acos()` generated by `jswrap_math.c` returns correct results only for positive inputs.
This can be easily proved with the help of WolframAlpha:

- [atan(sqrt(1-x*x) / x)](https://www.wolframalpha.com/input/?i=atan%28sqrt%281-x*x%29+%2F+x%29) (implementation of acos() currently used in Espruino Math library)

- [acos(x)](https://www.wolframalpha.com/input/?i=acos%28x%29)

The plot is the same between the two functions only for `x >= 0`, but negative inputs return very different results.

As suggested by WolframAlpha, `acos()` could be correctly implemented using `asin()`: `1/2 (π - 2 * asin(x))`

**Comment by gfwilliams** [comment]
Thanks! I'll get that change in.
