### ISSUE TITLE
Bangle JS Accelerometer "0x1b" register 

### ISSUE THREAD

**Issue by seragENTp** [espruino/Espruino#1951]
I was trying to retrieve Bangle "0x1b" register values using Bangle.accelRd(0x1b,1); 
I was expecting to receive a value of Uint8Array(0) according to https://github.com/espruino/Espruino/blob/RELEASE_2V08/libs/banglejs/jswrap_bangle.c#L1589 but received Uint8Array(1), What could be the reason for that ?

firmware version:  2v08

**Comment by gfwilliams** [comment]
`new Uint8Array(1)` means a single element Uint8Array that is all zeros, so it's what you expect.

```
>(new Uint8Array(1)).toString()
="0"
>(new Uint8Array(2)).toString()
="0,0"
>(new Uint8Array([0])).toString()
="0"
>(new Uint8Array([1])).toString()
="1"
```

It's a bit confusing in this case, but it makes a lot more sense if you're trying to dump the value of a 100 element array that's all empty - you don't want a console full of zeros :)
