### ISSUE TITLE
Add support for stm32f405

### ISSUE THREAD

**Issue by eugenio** [espruino/Espruino#196]
I have two fez_cerb40 boards (stm32f405vgt)  which I  tried to flash with espruino_1v46_stm32f4discovery.bin and dfu-util. The board, though, never came up on any serial port after reset. I think it's a firmware issue, but I don't know for sure.
Could you please release a build for this microntroller?

**Comment by gfwilliams** [comment]
Did anyone ever have any luck with this? Over 18 months old now so tempted to close it if not.

**Comment by gfwilliams** [comment]
Closing. It'd be trivial to add support if required.
