### ISSUE TITLE
Segmentation faults and floating point exception

### ISSUE THREAD

**Issue by docfate111** [espruino/Espruino#1983]
On Ubuntu 20:04 running the espruino binary on the files in the zip cause crashes. Mainly null pointer derefence/deferencing overwritten addresses and processing floating point numbers.

**Comment by gfwilliams** [comment]
There doesn't appear to be anything in that zip file?

**Comment by docfate111** [comment]
[crashes.zip](https://github.com/espruino/Espruino/files/5984009/crashes.zip)
Sorry I attached the wrong file, here is the correct one.

**Comment by gfwilliams** [comment]
Thanks - just fixed.

It seems all of the SIGSEGV were related to an invalid free if there was an error in the condition for a while loop.
