### ISSUE TITLE
Gadgetbridge: Announce firmware version of Bangle.js

### ISSUE THREAD

**Issue by kuleszdl** [espruino/Espruino#1991]
Gadgetbridge has a feature that it displays the firmware version of the connected device when you click on the dots next to it. However, for the Bangle.js it shows noting in there.

Couldn't we simply send the Bangle.js's firmware to Gadgetbridge, eventually also combined with the version of the Gadgetbridge app running on the Bangle.js?

**Comment by gfwilliams** [comment]
Thanks - yes, this sounds like a good plan! Should be pretty easy to add that.

Have you got a link to the code in Gadgetbridge for another device? If so it should be pretty easy to just copy it in

**Comment by kuleszdl** [comment]
@gfwilliams Sorry for leaving this issue unanswered for so long. One example you asked for could be here for the Miband:

https://codeberg.org/Freeyourgadget/Gadgetbridge/src/branch/master/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/miband/AbstractMiBandFWHelper.java

**Comment by gfwilliams** [comment]
This is sorted now
