### ISSUE TITLE
The new Espruino drawLineAA bugs

### ISSUE THREAD

**Issue by tyrone1984** [espruino/Espruino#2021]
I  built and tested the new Espruino, and the drawLineAA seems had bugs to dotted line.
 Is  It a bug?  Or just me  had this problem?
![IMG_20210702_072331](https://user-images.githubusercontent.com/78072335/124200629-683d4800-db08-11eb-96b6-db4fe3a60dd9.jpg)

**Comment by gfwilliams** [comment]
What command are you using? Did it work on earlier firmware? And do you see it on the emulator?

If you try a command line `g.drawLineAA(0,0,200,240)` in the emulator you'll see a slight 'beating':

![screenshot](https://user-images.githubusercontent.com/754445/124249009-5913c580-db1b-11eb-9dc4-99318ba3a340.png)

This is to be expected as when the line converges on a single pixel, that one pixel is brighter than two half-brightness pixels. The fix would really be to adjust the gamma curve on the LCD to ensure that 50% brightness was exactly the same as 1 pixel on, 1 pixel off

**Comment by tyrone1984** [comment]
Thanks,
I found the same problem after  tested  several earlier built, so i adjusted the gamma curve,  But it's really a hard work, :-( so i droped

**Comment by gfwilliams** [comment]
So are you saying this is an issue that only recently occurred? As far as I know it would have been present in `drawLineAA` since it was created.

If there's an easy way to do gamma correction when working out how to blend pixels then I'm all for pulling it in though.

**Comment by gfwilliams** [comment]
any thoughts on the above?
