### ISSUE TITLE
Graphics bitmap font size in X and Y

### ISSUE THREAD

**Issue by gfwilliams** [espruino/Espruino#2044]
Currently we allow bitmap fonts to be scaled up by a factor of 2/3/4/etc

We *could* allow them to be scaled up by a different factor in each dimension, without too many painful changes.

Is this something that would be useful? I can imagine that maybe in menus on Bangle.js 1 it might be better to triple the height but only double the width...

**Comment by gfwilliams** [comment]
Just a note to say I made some initial tweaks and it doesn't look too bad.

The only issue is how we set the font up... I guess we could just extend `setFont` to `setFont("FontName",x,y)` although I recently added `g.setFont("FontName:size")` which is nice in that the font is just one text string, which is easily changed. 

So we could just tweak it to allow `g.setFont("FontName:XxY")` like `g.setFont("6x8:1x2")`

What does everyone think?

**Comment by MaBecker** [comment]
my choice is g.setFont("6x8:1x2")

**Comment by MaBecker** [comment]
Could this be available for vector font too?

**Comment by gfwilliams** [comment]
Yes, it works for that too. Only gotcha is it's max of 63x63 pixel size when you scale separately because we've had to pack all the font info into 16 bits.

Still, it's pretty handy.
