### ISSUE TITLE
Bangle.js: should holding BTN3 reset LCDOffset?

### ISSUE THREAD

**Issue by ps-igel** [espruino/Espruino#2048]
Notify on the Bangle will display messages from Gadgetbridge via Bangle.setLCDOffset(). If you happen to press and hold BTN3 while a message is showing, the LCDOffset is not reset and the message is still showing.

There does not seem to be any way to remove the message, except if you dismiss a new incoming message.

Should holding BTN3 better reset the LCDOffset to 0?

**Comment by gfwilliams** [comment]
Try with the latest builds? This should be fixed now: https://github.com/espruino/Espruino/commit/1721c9005c0541eb672c5ca952d151579b4decda
