### ISSUE TITLE
Deprecated Github link to "create_sine_model.ipynb" 

### ISSUE THREAD

**Issue by baljo** [espruino/Espruino#2065]
Found a deprecated link in the Tensorflow readme (https://github.com/espruino/Espruino/tree/master/libs/tensorflow#readme), section "Actually using it"

This is old:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/examples/hello_world/create_sine_model.ipynb

As far as I know, this is the one replacing:
https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/examples/hello_world/train/train_hello_world_model.ipynb

**Comment by gfwilliams** [comment]
Fixed now!

**Comment by embeddeddesignblog-way2know** [comment]
link still not working
