### ISSUE TITLE
String substring on flash string

### ISSUE THREAD

**Issue by d3nd3** [espruino/Espruino#2066]
> jswrap_string_substring

What do you think about the new string returned to also be a flash string if the parent string is a flash string?  If because it would only be an address change and length update. 
At the moment i'm reading a file, then calling `E.toArrayBuffer` in order to bypass memory overhead.

**Comment by gfwilliams** [comment]
It's a good point. That definitely could be done reasonably easily.

What are you using it for where you need it? It feels like it might be quite a rare thing to do
