### ISSUE TITLE
with second storage bank enabled jsfCompactInternal corrupts Espruino firmware 

### ISSUE THREAD

**Issue by fanoush** [espruino/Espruino#2081]
more info here https://github.com/espruino/Espruino/pull/2080#issuecomment-954024336

**Comment by fanoush** [comment]
OK, so it is like this. I just upload one file to SPI flash and then delete it.
```
require("Storage").eraseAll()
require("Storage").write("fooX",new Uint8Array(10000))
require("Storage").erase("fooX")
require("Storage").compact()
```
this goes into this line
https://github.com/espruino/Espruino/blob/master/src/jsflash.c#L410
and writeAddress is exactly 0x60000000
so `jsfGetAddressOfNextPage(writeAddress-1);` returns 0 as it is called with 0x5FFFFFFF

**Comment by fanoush** [comment]
retried with clean build from latest tree, compiled with ARM gcc 8-2019-q3-update and yes, it erases 0x26000 page and then hangs

**Comment by fanoush** [comment]
- jsfGetAddressOfNextPage could first add page size to the address and then get that page
- since jsfGetAddressOfNextPage  can return zero jsfEraseFrom here https://github.com/espruino/Espruino/blob/master/src/jsflash.c#L411 should erase only if not zero

**Comment by gfwilliams** [comment]
That's great - thanks for tracking this down, I can reproduce easily here as well. I just put a fix in for it.

Not sure what you think, but we currently do `jsfEraseFrom` at the end of compact. It checks everything and is super slow on external storage. I'm thinking of just erasing the pages that had files in?
