### ISSUE TITLE
break scoping error in nested for loops

### ISSUE THREAD

**Issue by stephenPspackman** [espruino/Espruino#2084]
Bangle emulator 2v10.166.

```
>for (;;) {for (;;) break; break;}
Uncaught SyntaxError: BREAK statement outside of SWITCH, FOR or WHILE loop
 at line 1 col 27
for (;;) {for (;;) break; break;}
                          ^
```

Interestingly, this bug is not triggered when the _inner_ loop is a while or do-while loop, or when it contains no break statement(s); the kind of the outer loop is apparently immaterial.

This is the smallest reproduction I can find. In real code, the loop bodies and conditions would be nontrivial. This bug interferes with natural coding of nested mid-exit loops, though of course it can be worked around once characterised.

**Comment by gfwilliams** [comment]
Thanks! I'll have a look at that.

It's possible this is another one of those cases where a speed optimisation is trying to quickly run over the code quickly, but didn't change the parse state correctly
