### ISSUE TITLE
Bangle.setUI on teh Bangle 1  does not delete touchHandler

### ISSUE THREAD

**Issue by jeffmer** [espruino/Espruino#2095]
The problem is a typo on line 10 of Bangle_setUI_F18.js:

```
  if (Bangle.touchandler) {
    Bangle.removeListener("touch", Bangle.touchHandler);
    delete Bangle.touchHandler;
  }
```
Clearly `Bangle.touchandler` should be `Bangle.touchHandler`.

Took me ages to work out was going on :-(

**Comment by gfwilliams** [comment]
Great - thanks for tracking this down! Just put a fix in
