### ISSUE TITLE
BangleJS 2 LCD backlight turns on randomly with no movement or button/touch interaction

### ISSUE THREAD

**Issue by Izaic** [espruino/Espruino#2100]
Even if I just sit it down on a table and not touch it, the LCD's backlight on my BangleJS 2 turns on and off seemingly randomly. I'm running version 2v10.226.

**Comment by gfwilliams** [comment]
It doesn't do that for the one I have here - do you have any non-default apps installed? Maybe they are forcing the backlight on?

**Comment by gfwilliams** [comment]
Also, could you try turning off 'Wake on twist' in LCD settings and see if that has an effect - that would narrow it down

**Comment by gfwilliams** [comment]
any update on this?

**Comment by Izaic** [comment]
> any update on this?

Sorry I forgot that I opened this one. After a firmware update it stopped happening.
