### ISSUE TITLE
ü is broken on 12x20 font

### ISSUE THREAD

**Issue by gfwilliams** [espruino/Espruino#2105]
```
g.clear(1).setFont("12x20").drawString("ü");
```

![image](https://user-images.githubusercontent.com/754445/144023864-30d4e3e5-067e-4542-900c-d9219f659a92.png)

**Comment by MaBecker** [comment]
just tested the other umlaute 

```js
g.clear(1).setFont("12x20").drawString("äöüÄÖÜß");
```

![IMG_1800](https://user-images.githubusercontent.com/15932646/144024835-2d5e2f85-6f15-4b7d-9bff-1063aff277b5.jpg)

looks like they all need fixing

**Comment by gfwilliams** [comment]
It seems that one or two character widths are off, and that's making the characters more and more off the further along the codepage you get
