### ISSUE TITLE
BangleJS2 - Watch faces show "Bluetooth ->" at the bottom

### ISSUE THREAD

**Issue by Izaic** [espruino/Espruino#2117]
I'm seeing bluetooth -> and bluetooth <- messages at the bottom of the clock faces I use, which causes them to scroll upwards to make room for the messages. This is on the 2v11 firmware.

**Comment by gfwilliams** [comment]
It's an error caused by previous firmwares (the one mentioned in the update where you have to `Rewrite settings`)
