### ISSUE TITLE
Bangle.js 2 Bangle.getPressure may not succeed on some devices

### ISSUE THREAD

**Issue by gfwilliams** [espruino/Espruino#2120]
Reported at: https://github.com/espruino/BangleApps/pull/1092#issuecomment-996754700

It may work if the barometer has previously been powered on, but maybe it's related to the time allowed for the barometer to start up if it was previously off.

Doesn't happen on the first device I tried here so it may only be on some watches

**Comment by elrod16** [comment]
You're on to something with the power up timing. It looks like SensiBLE works reliably because they explicitly power up the barometer and verify the power status before trying to fetch data from it. Or at least that's what I think it is doing.

**Comment by elrod16** [comment]
Would it be practical to include some kind of non-busy waiting in the call? Like it sends the sensor power on, then idles until it gets returned a valid integer before returning a value to the calling app? I imagine though that there are plenty of ways that that could go wrong.

However, being it is a sensor that needs a brief "warm up", I imagine it would be practical for devs to expect a slight delay.

**Comment by gfwilliams** [comment]
Thanks - `getPressure` returns a promise that resolves with the value rather than blocking, and yes, it does actually do a bit of a wait for power-up already (as far as I remember) so it *may* just be a matter of increasing that delay a little to account for some sensors.

I can do that and we can see if it fixes it for your Bangle however I'd like to try and find one here that it's an issue for, just in case the problem turns out to be something a bit tricker for fix :)
