### ISSUE TITLE
Date.now() returns floating point number instead of integer (milliseconds)

### ISSUE THREAD

**Issue by MRuy** [espruino/Espruino#2123]
BangleJS2: `Date.now() // 1641003034026.6885`  
Chrome/Firefox/Node.js: `Date.now() // 1641003039841`

**Comment by gfwilliams** [comment]
Interesting - thanks! Is this causing you problems?

I think maybe some folks are using the sub-millisecond precision for timing, so changing it might require them to switch to `getTime`

**Comment by MRuy** [comment]
It doesnt cause problems for me, just noticed the extra numbers while logging data to a file.

**Comment by gfwilliams** [comment]
Closing this one as wontfix - I'll make sure there's a note in the docs on it though
