### ISSUE TITLE
String.prototype.concat is not defined

### ISSUE THREAD

**Issue by are** [espruino/Espruino#2140]
First of all, thanks for everything you do!

String.prototype.concat seems to not be defined. This usually shouldn't be a problem for just writing code, but certain transpilers (including TypeScript) emit code that uses concat instead of template strings. This poses trouble for cross-environment JS libraries and forces users to use polyfills.

To reproduce:
1. Go to https://espruino.com/ide/?emulator
2. Run the following code:
```
var myString = "hello";
console.log(myString.concat(" ", "world"));
```

Result:
```
>Uncaught Error: Function "concat" not found!
 at line 3 col 22
console.log(myString.concat(" ", "world"))
```

Expected:
```
>"hello world"
```

**Comment by gfwilliams** [comment]
Thanks! Interesting - I'm amazed we missed that out.

Adding it shouldn't be a big deal though
