### ISSUE TITLE
[Bangle1] LCD mode broken in 2v12 ?

### ISSUE THREAD

**Issue by ps-igel** [espruino/Espruino#2155]
Games like CarCrazy do not seem to work properly on my Bangle1 with 2v12.

Screen starts flickering and displaying artifacts. [see [video](https://www.dropbox.com/s/6ut72eafx3pscwo/MOV_6605.mp4)]

A simple test code via WebIDE seems to confirm:

´´
Bangle.setLCDMode("doublebuffered");
g.clear().drawLine(1,1,240,160);
g.flip();
´´

In 2v11 the above code does draw a straight line as expected.

In 2v12 it partially draws a line while still displaying artifacts from previous renderings [see [image](https://www.dropbox.com/s/wpnhhuklihzm11p/DSC_6645.JPG)].

Also, resetting to the clock face with long-press BTN3 only partially reset the clock face [see [image](https://www.dropbox.com/s/wpnhhuklihzm11p/DSC_6645.JPG)]

**Comment by gfwilliams** [comment]
Sorry about that - just pushed a change and it seems to fix it for me - but let me know if you still have issues!
