### ISSUE TITLE
Writing to storage can corrupt storage

### ISSUE THREAD

**Issue by WizardStan** [espruino/Espruino#2174]
### Summary
In some circumstances, writing to the storage can corrupt the storage.  In some cases this results in some files incorrectly overwritten, in worse cases the watch becomes almost inoperable and must be rebooted, at which time it detects the corruption and erases the storage.

Background: I've been experimenting with messages being kept on the watch even when cleared from the phone which can result in hundreds of messages being recorded and ultimately lead to this particular discovery and experiment.

### Environment
Bangle.js 2 running 2v12

### Steps to reproduce
Run the following code
```
var count = 0;
var page = 0;
const PAGE_SIZE = 100;

function pushMessage() {
  g.clear();
  Bangle.drawWidgets();
  g.setFont("6x8:2");
  g.setColor("#000000");
  var messages = require("Storage").readJSON("messages_" + page + ".json",1)||[];
  count = messages.length;
  while (count >= PAGE_SIZE) {
    ++page;
    messages = require("Storage").readJSON("messages_" + page + ".json",1)||[];
    count = messages.length;
  }
  g.drawString("Loaded page " + page, 0, 30);
  g.drawString("Count " + count, 0, 50);
  var event = {
    id: count,
    t: "add",
    new: true,
    timestamp: Date.now(),
    src: "gmail",
    title: "Test message",
    body: "We would like to speak with you about your car's extended warranty",
  };
  messages.push(event);
  g.drawString("Added", 0, 70);
  require("Storage").writeJSON("messages_" + page + ".json", messages);
  g.drawString("Written", 0, 90);
}

Bangle.loadWidgets();
var addMessageTest = setInterval(pushMessage, 100);
```

### Expected behaviour
The messages are written to the file without any issues, until the storage is full and the writeJSON call fails gracefully.

### Actual behaviour
At approximately page=9 count=5 the app locks up and the debug console (ide) says
```
>FW addr 0x00769198 fail
Status 0
Uncaught Error: File already written with different data
 at line 30 col 70 in messages
... + page + ".json", messages);
                              ^
in function called from system
>FW addr 0x0076960c fail
Status 0
Uncaught Error: File already written with different data
 at line 30 col 70 in messages
... + page + ".json", messages);
                              ^
in function called from system
Uncaught Error: Function "push" not found!
 at line 28 col 12 in messages
  messages.push(event);
           ^
```
The "push not found" error is then repeated until the app is closed.  If the storage is inspected several corrupt files can be observed with names like $bee$, "earrafdq\u00029,j\"id", and body: "we would like (etc...)

The file .boot0 is deleted (overwritten by $bee$ perhaps?)

Despite getting to page=9 and count=5 there is not a messages_9.json.  messages_8.json exists with a full 100 messages.

Rerunning the same code successfully skips to page 9 and attempts to continue.  This will completely corrupt the storage requiring the watch be rebooted at which time it will indicate the storage has become corrupt and erase it.

### Frequency
100%

### Additional information

By changing PAGE_SIZE to 10, it can reach page 806 before it corrupts the storage.  In this case it does not always corrupt the storage so much that it needs to be erased.  Inspecting the storage does show some corrupt files, including duplicates of messages_803.json, messages_804.json, and messages_805.json however.

By changing the PAGE_SIZE to 200 it reaches page 4, count 6 before locking up.  Despite reaching page 4 there is only up to messages_3.json.  PAGE_SIZE of 50 reached page 35 count 1 before locking up.

It just seems interesting to me that smaller files takes longer to cause corruption than larger files; this is obviously not a case of running out of flash storage.

**Comment by gfwilliams** [comment]
Thanks - I'm trying it here now and definitely did manage to reproduce some brokenness. Mine just hung though and then when I ctrl-c'd out it said `FW error 0x00000000`.

Are the `FW addr 0x0076960c fail` errors always with basically the same `0x00769xxx `address?

**Comment by gfwilliams** [comment]
Just to add, if you add the code `g.drawString("Free " +require("Storage").getFree(), 0, 110);` you can see the amount of free memory in storage reducing to 0 at which point the error occurs, so I think this is probably a bug in the storage compaction process that is used to free up deleted files.

It's great to have a test case to reliably reproduce this as I should be able to find the issue much more quickly

**Comment by WizardStan** [comment]
No, it's always different.  This time it was 
```
>FW addr 0x0026a994 fail
Status 0
Uncaught Error: File already written with different data
 at line 30 col 70 in messages
... + page + ".json", messages);
                              ^
```

Next execution (following a reboot and storage erase) gave me 0x00346494.

Strange that you're only getting a hang though.  When I use PAGE_SIZE=100 I get corruption and erase-storage-on-reboot 100% of the time, and I've done this at least a dozen times.  Different page sizes don't always lead to that level of corruption, like with page size of 10 I can see some corrupted files but I can reboot no problem.

I added that getFree line and yeah, weird; it does count down to 0 and that's where the problem occurs.  So a file with 100 messages in it consumes less storage than 10 files with 10 messages in them.  Colour me confused.

And to top it off, just did a factory reset, updated apps, installed Android, messages, and pedometer widget, and it at page 8 count 97 it froze up as storage read just over 4000 bytes remaining.  And then, about a minute later, it kept going, with "Free" reading almost the full 8MB again: no errors, no corruption, just a delay and then away it goes.  I'm assuming the compaction process is asynchronous then? And I've managed to hit on a use case that interferes with it in just the right way.

**Comment by gfwilliams** [comment]
I just tried some more times and I see what you do now - errors right away.

> it kept going, with "Free" reading almost the full 8MB again: no errors, no corruption, just a delay and then away it goes

Yes, so that's what *should* happen! And yes, luckily something in what you've done manages to break it more times than not.

I actually have very similar code that I've been running on the bangle to stress-test it and somehow my code always works - it'll be interesting to dig in and see what's different.

> I'm assuming the compaction process is asynchronous then?

No, it's synchronous. It only happens when you run out of free storage space. At some point it may be done automatically (like at midnight, when on charge - so as not to inconvenience anyone with the pauses)

**Comment by WizardStan** [comment]
Gotcha.  Yeah, I threw in a `require("Storage").compact();` when count == PAGE_SIZE and it takes about 17 seconds which is not an acceptable delay; I imagine it'll take even longer the more files there are.  I think I understand the process here now and it makes sense why the larger files appear to consume more storage than multiple small files.  Colour me unconfused.

**Comment by gfwilliams** [comment]
Just fixed this I think - it's been running for almost half an hour now and hasn't crashed. Up to page 46.

Thanks again for your help getting a reproducible test case. It makes my like **so** much easier
