### ISSUE TITLE
[showMenu] Dirty screen if text overflows

### ISSUE THREAD

**Issue by alessandrococco** [espruino/Espruino#2190]
I noticed a glitch when the text overflows the panel as the screen isn't cleared when the selection change:

![image](https://user-images.githubusercontent.com/2331798/166204493-752d3b6a-2df0-410f-93ca-dd97e03139ea.png) ![image](https://user-images.githubusercontent.com/2331798/166205690-7bc9c37c-7416-400c-955a-c6707b9e01b2.png)

**Comment by gfwilliams** [comment]
Argh, ok - thanks. Since it's a vector font we should probably just set the font size such that it fits in the box
