### ISSUE TITLE
2v13.51 - broken (sub)menus

### ISSUE THREAD

**Issue by alessandrococco** [espruino/Espruino#2192]
I just installed the latest cutting edge firmware (2v13.51) and it seems the (sub)menus are broken now :-(

```
Uncaught ReferenceError: "s" is not defined
 at line 1 col 187
...nchange(a.value);r.scroll=s.scroll;p()}
                              ^
in function "e" called from line 1 col 7
f();e()
      ^
in function "n" called from line 1 col 17
d.handled||n(a,d)
                ^
in function called from system
> 
```

**Comment by gfwilliams** [comment]
Sorry - I think @rigrig just fixed it with https://github.com/espruino/Espruino/pull/2193

**Comment by alessandrococco** [comment]
Hi @gfwilliams, I just updated to 2v13.84 but the issue is still here:

![image](https://user-images.githubusercontent.com/2331798/168292067-1852d17b-8931-4788-af44-8029bcc2b805.png)

**Comment by gfwilliams** [comment]
Ok, thanks - looks like it fixed one of the errors but not all of the. Fixing now
