### ISSUE TITLE
Graphics.wrapString only cuts a word in half once

### ISSUE THREAD

**Issue by gfwilliams** [espruino/Espruino#2194]
Mentioned at: https://github.com/espruino/BangleApps/issues/1380

```
g.clear().setFont("4x6");
lines = g.wrapString("ABCDEFGHIJ", 10);
// lines is ["AB","CDEFGHIJ"]
// lines should be ["AB","CD","EF","GH","IJ"]
```

Not trivial to fix in `jswrap_graphics_wrapString` with the current code though - it'll need refactoring a bit

**Comment by thyttan** [comment]
Just leaving a comment here to mention I encountered this bug today while coding on a new app.

Reading the discussion on espruino/BangleApps#1380 I'm thinking it could be worth mention this bug in the HW reference for Graphics.wrapString? I can do a PR for that if you think it's a good idea, @gfwilliams.

**Comment by gfwilliams** [comment]
Yes, I guess a note in the hardware reference would be good.

... of course if someone wanted to actually fix this, that would be better ;)

**Comment by gfwilliams** [comment]
Fixed with https://github.com/espruino/Espruino/commit/19868ef2b10d0a4f2265757df165ef92e0be05a5
