### ISSUE TITLE
Better lvalue handling

### ISSUE THREAD

**Issue by mariusGundersen** [espruino/Espruino#2214]
I found a bug caused by the way expressions return variables:

```
//given this setup code
var b = 0;
var obj = {
  get v(){
    return ++b;
  }
};

obj.v // returns 1, b is incremented once

obj.v || 0 // returns 3, b is incremented twice (since last time)
```

This is because the binary expression (and most of the expression code) is working with variable references. That's not entirely correct, as the expressions should return values, not references. I think what's needed is to use `jsvSkipName()` before returning the `JsVar*`, so that a value is returned not a reference to the variable containing that value. But this might lead to some issues somewhere.

One thing this also fixes is that today there isn't proper checking of lvalues. So for example the following seems to work in espruino, but it should not be possible: `(false || b)++`. Since the reference to b is returned from the binary expression the increment behaves correctly, and b is incremented. This should throw a syntax error. If the binary expression returned a value instead it would not work: `(false || 3)++`.

**Comment by mariusGundersen** [comment]
This might speed up expressions a bit too, as now the jsvSkipName method is called multiple times for each value

**Comment by gfwilliams** [comment]
You can mark as a draft, which would help.

In terms of benchmarks, I really need to get something automatic set up that runs on real hardware - the Linux compile isn't really that good an indicator as it does some odd stuff for resizable variables.
