### ISSUE TITLE
Scopes of const/let in 2v13.122

### ISSUE THREAD

**Issue by halemmerich** [espruino/Espruino#2215]
The weather widget exhibits an
`weather.wid.js ReferenceError: ReferenceError: "storage" is not defined` error with this firmware version. Changing the globally scoped `storage` var in the lib.js from `const` to `var` fixes this. To get the widget to working without errors, there also needs to be a change from `let` to `var` for the `expiryTimeout` variable.

It seems the access from functions to globally defined const/var variables does not yet work correctly.

**Comment by halemmerich** [comment]
Further experiments show additional variables need changes for full functionality (including Gadgetbridge message parsing).
In `lib.js` there are `const` variables `B2` and `_GB` that need to be changed to `var`.

This is just a workaround, I assume correct solution would be fixing the scope handling.

**Comment by gfwilliams** [comment]
> It seems the access from functions to globally defined const/var variables does not yet work correctly.

Do you think you could give me some short example code of what's not working that should be?

**Comment by gfwilliams** [comment]
This is very likely  related to https://github.com/espruino/Espruino/issues/2207 and http://forum.espruino.com/conversations/376541/

**Comment by halemmerich** [comment]
I have done some experiments and found a relatively small example which seems to show this problem:

Upload this as `issue2215`:
```
function test(p){
  console.log("Test", p);
}

let variable_let = { test: test};
const variable_const = { test: test};
var variable_var = { test: test};

exports.func_let = function (){
  variable_let.test("let");
};

exports.func_const = function (){
  variable_const.test("const");
};

exports.func_var = function (){
  variable_var.test("var");
};
```
The following snippets can then be run from RAM:
Working as expected:
```
require("issue2215").func_var();
require("issue2215").func_const();
require("issue2215").func_let();
```
```
()=>{
  var test = require("issue2215");
  test.func_var();
  test.func_let();
  test.func_const();
}();
```
Only `func_var()` working;
```
()=>{
  let test = require("issue2215");
  test.func_var();
  test.func_let();
  test.func_const();
}();
```
```
()=>{
  const test = require("issue2215");
  test.func_var();
  test.func_let();
  test.func_const();
}();
```
The following is strange to me, this also works:
```
require("issue2215");
()=>{
  const test = require("issue2215");
  test.func_var();
  test.func_let();
  test.func_const();
}();
```

**Comment by halemmerich** [comment]
Adding the example as cached module does not reproduce the problem:
```
Modules.addCached("issue2215", function() {
  function test(p){
    console.log("Test", p);
  }

  let variable_let = { test: test };
  const variable_const = { test: test };
  var variable_var = { test: test };

  exports.func_let = function (){
    variable_let.test("let");
  };

  exports.func_const = function (){
    variable_const.test("const");
  };

  exports.func_var = function (){
    variable_var.test("var");
  };
});


()=>{
  const test = require("issue2215");
  test.func_var();
  test.func_let();
  test.func_const();
}();
```

**Comment by gfwilliams** [comment]
Thanks - well this is all pretty strange!

More stuff...

This breaks:

```
()=>{
  const x = 5;  
  var test = require("issue2215");
  test.func_var();
  test.func_let();
  test.func_const();
}();
```

And it'd seem that `addCached` is effectively like requiring the module first, which is why it fails. Add a `const` in there and it can fail too:

```
()=>{
  const x = 5;
  
  Modules.addCached("issue2215", function() {
    function test(p){
      console.log("Test", p);
    }

    let variable_let = { test: test };
    const variable_const = { test: test };
    var variable_var = { test: test };

    exports.func_let = function (){
      variable_let.test("let");
    };

    exports.func_const = function (){
      variable_const.test("const");
    };

    exports.func_var = function (){
      variable_var.test("var");
    };
  });

  var test = require("issue2215");
  test.func_var();
  test.func_let();
  test.func_const();
}();
```

The issue seems to be that in those cases the const/let are being created in the wrong scope (probably the same one as the first const) - but now I have a self-contained test I should be able to fix it pretty quick - thanks for the help!
