### ISSUE TITLE
RELEASE_2V14 tag can not be checked out

### ISSUE THREAD

**Issue by halemmerich** [espruino/Espruino#2223]
It seems the 2V14 tag can not be checked out in a local clone of this repo. Github shows the tag at https://github.com/espruino/Espruino/tree/RELEASE_2V14, but claims `This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.`

**Comment by gfwilliams** [comment]
Interesting, thanks - I did `git push RELEASE...` but not just a normal `git push`
