### ISSUE TITLE
Module sched not found in factory image

### ISSUE THREAD

**Issue by BartS23** [espruino/Espruino#2229]
HW: Bangle 2 + Bangle 1 (only tested in emulator)
Affected Version: 2v14

Installed apps: Factory defaults
Settings: Factory defaults

Steps to reproduce:

- Connect to watch (or emulator) with web-ide
- Run "Bangle.factoryReset()"
- Skip welcome
- Open menu and select "Alarms"

```
Uncaught Error: Module sched not found
 at line 15 col 24 in alarm.app.js
var alarms=require("sched").getAlarms();
```

**Comment by gfwilliams** [comment]
Thanks! Just fixed! I bet that affects normal Bangles shipped with 2v14 firmware too, so alarms wouldn't have worked out the box :(

**Comment by BartS23** [comment]
That's bad. Do you think there is a way for a unit test to make sure this doesn't happen again?

**Comment by gfwilliams** [comment]
> Do you think there is a way for a unit test to make sure this doesn't happen again?

It's not so easy as we're not running any of this in Node.js - it's all in Espruino.

Conceivably you could inject touch/button events into the watch via the REPL (on a real or emulated watch) and then compare screenshots though.

**Comment by BartS23** [comment]
That sounds complicated. I'm afraid my programming skills are not sufficient for this.

Is there any documentation how to update the emulator?

**Comment by gfwilliams** [comment]
https://github.com/espruino/EspruinoWebIDE/blob/master/extras/create_emulator.sh

But best bet is to just wait until I do it as you'd have to host your own IDE. You can still manually load the relevant 'sched' files into the emulator via the IDE
