### ISSUE TITLE
Broken let scope in calback

### ISSUE THREAD

**Issue by qucchia** [espruino/Espruino#2240]
Running this on Bangle.js 1:
```js
(() => {
  function a() {
    console.log(b);
  }

  let b = 3;
  a(); // expected output: 3
})();
```
Gives the following error:
```sh
Uncaught Error: Unhandled promise rejection: ReferenceError: "b" is not defined
```
This might have something to do with the changes made here? #971 

The [kbmorse](https://github.com/espruino/BangleApps/blob/master/apps/kbmorse/lib.js) library is currently broken because of this bug.

Some notes:
- This only happens with `let` and `const`. If `b` is defined with `var`, or without a keyword, the script runs fine.
- This only happens in callbacks - outside of them it works.

**Comment by gfwilliams** [comment]
Thanks - which firmware version are you running?

**Comment by qucchia** [comment]
2v14.

**Comment by gfwilliams** [comment]
Just tried on cutting edge and this works fine :)
