### ISSUE TITLE
Suggestion: make Bangle.js reference prettier

### ISSUE THREAD

**Issue by qucchia** [espruino/Espruino#2243]
The [Bangle.js](https://banglejs.com/reference) reference isn't as pretty or functional as [Espruino's](https://espruino.com/Reference#Software). Any chance the styles and scripts could be copied over?

**Comment by gfwilliams** [comment]
Good point, yes!

However I've actually been considering auto-generating documentation for Bangle.js/Puck/Pixl.js/etc and hosting them on the main Espruino site. Then I'd just make the reference redirect...

I feel like that might make more sense?

**Comment by qucchia** [comment]
Yep, that sounds good to me!

**Comment by gfwilliams** [comment]
Fixed this now :)
