### ISSUE TITLE
Strange results with Math.ceil() and slice()

### ISSUE THREAD

**Issue by qucchia** [espruino/Espruino#2245]
The error can be reproduced the following way:
```js
const items = Math.ceil(2 / 2);
console.log(items); // outputs 1 correctly
console.log([1,2,3].splice(0, items)); // expected output: [1] but gets [1,2,3]
```
Even though the value of `items` is `1`, `splice` seems to ignore the argument and returns the entire array.

**Comment by gfwilliams** [comment]
Thanks - looks like:

```
>trace(items)
#34[r1,l1] Double 1 
```

So the issue is `splice` is checking for an int, when actually it should just be checking for a number. fixing now
