### ISSUE TITLE
Module MPR121 failing with example script - Function "readword" not found - executing mpr.touched()

### ISSUE THREAD

**Issue by SimonGAndrews** [espruino/Espruino#2259]
![image](https://user-images.githubusercontent.com/55559464/186760243-b3e33b0b-1d86-4ce0-a934-e877a71488fa.png)
The above script is failing on an Espruino MDBT42Q with the error:
![image](https://user-images.githubusercontent.com/55559464/186760908-e55bb491-6369-417c-9b36-2a3c7b0da09d.png)

Looks like prop. an error introduced in the last last change of module MRP121, last May.

**Comment by SimonGAndrews** [comment]
Changing the references to the functions in the object MPR , in the module,  from this.readword() to to MPR.readword fixes the issue in a local copy of the module.  As in the following.  

![image](https://user-images.githubusercontent.com/55559464/186762349-42a6d592-8552-492d-b5e7-0c1e80423d10.png)

Thanks in advance for your help with this issue.

**Comment by mariusGundersen** [comment]
Seems like the module was changed to use the arrow function syntae, that doesn't work with `this`. Since you are using the latest firmware version you can also/instead change it to
```
...
touched() {
  return this.readWord(0);
}
... 
```

**Comment by gfwilliams** [comment]
Argh, sorry - not sure how that happened.

I've just sorted this out, and it'll go live next time I update the website, which should be this week
