### ISSUE TITLE
Question: Is __FILE__ for getting the currently running file an official feature?

### ISSUE THREAD

**Issue by kyleplo** [espruino/Espruino#2269]
I've been looking for a while for a way to get the currently running file, and came across `__FILE__` which seems to do exactly what I want. However, I don't see it documented anywhere. Before I publish any code using it, I'd like to make sure that `__FILE__` is an official feature that can be used in production code.
If not, is there another way to do what I want?

**Comment by gfwilliams** [comment]
Yes, this is definitely an official feature that you can rely on. Good point about the docs - I'll add something now.
