### ISSUE TITLE
BangleJs 1: Uncaught InternalError: Variable type cannot be converted to string

### ISSUE THREAD

**Issue by banglejsdev** [espruino/Espruino#2282]
Using "+=" to concatenate strings in a particular context (see code below) results in "F 0" being printed to the console (and my Bangle1 hanging) and an "Uncaught InternalError: Variable type cannot be converted to string" error when the code is run within the emulator. This problem started occurring in 2v14 but I didn't exercise the problematic code until recently. Fortunately, there's a simple workaround--just modify the code to not use the "+=" operator.

```
var players = "player1,player2,player3";
require("Storage").write("rcntplyrs.txt", players);
players = undefined;

function updateRecentPlayers(mostRecentPlayer) {

  let updatedPlayers = mostRecentPlayer + ",";

  if (require("Storage").read("rcntplyrs.txt") != undefined) {
    let recentPlayersString = require("Storage").read("rcntplyrs.txt");
    let playerCount = 1;
    let start = 0;
    let comma = recentPlayersString.indexOf(',');
    while (comma >= 0 && playerCount < 10) {
      let name = recentPlayersString.substring(start, comma);
      if (name != mostRecentPlayer) {
        updatedPlayers += name + ",";
      //updatedPlayers = updatedPlayers + name + ","; // workaround
      }
      start = comma + 1;
      comma = recentPlayersString.indexOf(',', start);
      playerCount++;
    }
  }
}

updateRecentPlayers("player2");

```

**Comment by gfwilliams** [comment]
Thanks for the clean test case to reproduce! I can run this on a desktop build and get an error too, so I'll get a fix in in the next hour or so.

It's to do with appending to 'flash strings' - which there was a fix in for previously, but it looks like it didn't cover all eventualities :)
