### ISSUE TITLE
ESP32 with spiram  larger than 4MB fails

### ISSUE THREAD

**Issue by MaBecker** [espruino/Espruino#2302]
```c

E (552) spiram: Expected 4096KiB chip but found 8192KiB chip. Bailing out..

```

looks like the size is fixed in `sdkconfig` 

```c
#
# SPI RAM config
#
CONFIG_SPIRAM_BOOT_INIT=y
CONFIG_SPIRAM_IGNORE_NOTFOUND=y
CONFIG_SPIRAM_USE_MEMMAP=
CONFIG_SPIRAM_USE_CAPS_ALLOC=
CONFIG_SPIRAM_USE_MALLOC=y
CONFIG_SPIRAM_TYPE_ESPPSRAM32=y
CONFIG_SPIRAM_SIZE=4194304                     <---
CONFIG_SPIRAM_SPEED_40M=y
CONFIG_SPIRAM_MEMTEST=y
CONFIG_SPIRAM_CACHE_WORKAROUND=y
CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL=16384
```

**Comment by gfwilliams** [comment]
```
gw@sparky:~/workspace/Espruino$ grep "chip but found" -R .
grep: ./app/build/esp32/libesp32.a: binary file matches
```

Looks like it's internal :( Although am I right in thinking that `libesp32.a` actually gets built and put in EspruinoBuildTools, so it might be fixable?

**Comment by gfwilliams** [comment]
Is this helpful? https://esp32.com/viewtopic.php?t=10666

> Please try setting PSRAM type to "auto-detect" in menuconfig: [https://docs.espressif.com/projects/esp ... piram-type](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/kconfig.html#config-spiram-type)

I don't have a way to test here

**Comment by MaBecker** [comment]
yes it's possible:

![Bildschirm­foto 2022-12-02 um 22 04 13](https://user-images.githubusercontent.com/15932646/205385909-58531e8e-9749-43c5-b432-b018233f00ba.JPG)

will build a new sdk files and give it a try

**Comment by MaBecker** [comment]
```c
diff sdkconfig sdkconfig.old
265c265
< CONFIG_SPIRAM_TYPE_AUTO=y              <-------
---
> CONFIG_SPIRAM_TYPE_AUTO=
267c267
< CONFIG_SPIRAM_TYPE_ESPPSRAM32=
---
> CONFIG_SPIRAM_TYPE_ESPPSRAM32=y
269c269
< CONFIG_SPIRAM_SIZE=-1                  <--------
---
> CONFIG_SPIRAM_SIZE=4194304

````

**Comment by MaBecker** [comment]
And it works :-)

![Bildschirm­foto 2022-12-02 um 23 11 03](https://user-images.githubusercontent.com/15932646/205399528-6c72cc4a-b846-4647-84e1-2f363ffbd447.JPG)

**Comment by gfwilliams** [comment]
Excellent - thanks! Please could you upload the new build to https://github.com/espruino/EspruinoBuildTools ?

You did the build last time so I think you'd be less likely to break things than me ;)

**Comment by MaBecker** [comment]
![Bildschirm­foto 2022-12-06 um 21 17 21](https://user-images.githubusercontent.com/15932646/206013973-ab49f070-17b4-494b-a169-2c7c12323e6e.JPG)

just updated the build tools for esp32.
