### ISSUE TITLE
Graphics.wrapString only wraps the first line

### ISSUE THREAD

**Issue by nxdefiant** [espruino/Espruino#2304]
Seen on BangleJS 2, firmware 2v16.11:

`g.setFont("6x8:4").wrapString("abcdefghijklmopqrstuvwxyz", Bangle.appRect.w)`
>=[
  "abcdefg",
  "hijklmopqrstuvwxyz"
 ]

I would have expected all lines to be max. floor(176px/(6px*4))=7 characters.
The second line is obviously longer.

**Comment by gfwilliams** [comment]
Duplicate of https://github.com/espruino/Espruino/issues/2194
