### ISSUE TITLE
Regression for commit Graphics: Fix drawString with combination of g.setClipRect and g.setRotation

### ISSUE THREAD

**Issue by ps-igel** [espruino/Espruino#2326]
Hi Gordon,

I think there is some kind of bug in this commit: [Graphics: Fix drawString with combination of g.setClipRect and g.setRotation](https://github.com/espruino/Espruino/commit/79286897b49612aca093702e39a31bf108ca526b) 

When I write text using drawString to my ePaper display on my **Espruino wifi**, the text is being displayed correctly in <=2v13 and is being clipped in versions >=2v14. Code is exactly the same in both instances:

```
display.g.bw.setFontVector(30).setRotation(1).drawString("ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ",0,0);
display.g.rw.setFontVector(30).setRotation(1).drawString("ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ",0,30);
display.g.bw.setFontVector(30).setRotation(1).drawString("ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ",0,60);
display.g.rw.setFontVector(30).setRotation(1).drawString("ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ",0,90);
```

<=2v13
![image](https://user-images.githubusercontent.com/60899838/218514154-94995727-3434-4660-9139-6de727653937.png)

\>=2v14
![image](https://user-images.githubusercontent.com/60899838/218514211-1fc58888-9a92-4ec8-a6be-a190683ddd1e.png)

**Comment by gfwilliams** [comment]
Eeep - ok, thanks for narrowing this down! I've just reproduced this here and put a fix in.

By the way, that epaper LCD looks lovely!
