### ISSUE TITLE
Uncaught InternalError: BLE task completed that wasn't scheduled (SERVICE/NONE)

### ISSUE THREAD

**Issue by nravanelli** [espruino/Espruino#2355]
I am having an issue present itself with the Bangle.js 2 connecting to a Bluetooth device. It is seemingly random and occurs with some of my Bangle.js2 devices, but not all.

I can sometimes get it to connect, but it takes many tries and reboots.

**Comment by nravanelli** [comment]
Yes, I apologize for the lack of detail. But, your suggestion helped me narrow down the root cause, among others. Which then also required me to do a massive rewrite to my code... so its better now :) 

Suggestion (or perhaps this already exists and I cannot find it) ==> Could we have a wiki/document for all the BLE errors that could possibly happen?

**Comment by gfwilliams** [comment]
> Could we have a wiki/document for all the BLE errors that could possibly happen?

Sounds like a good idea. Any thoughts for where? We could put it under https://www.espruino.com/Troubleshooting+BLE and hopefully it'd get picked up by espruino.com's search?
