### ISSUE TITLE
btnHandlerCommon block when LCD off

### ISSUE THREAD

**Issue by d3nd3** [espruino/Espruino#2383]
`btnHandlerCommon` blocking when screen off. I created a pull request: #2384

Bangle 1 user.

**Comment by d3nd3** [comment]
Hi, I didn't see you posted here.

I understand that the default desire is that the watch functions best like that. That state is preserved, if lockTimeout is the same value as lcdPowerTimeout, the device locks and turns display off at same time.  I see that this gives more flexibility to the lockTimeout for users who do not want to use that default safer state.

Hope that it makes more sense.

**Comment by d3nd3** [comment]
But the backlight stuff will solve this posts issue:
[https://forum.espruino.com/conversations/387477/#comment17014744](https://forum.espruino.com/conversations/387477/#comment17014744)

And another stab at explaining the need for the lock thing:
If I have lcd power save on (any of lockTimeout,backlightTimeout,lcdTimeout > 0 ) ... then the code at :
https://github.com/espruino/Espruino/blob/491288d9ffb88150e4213f94c4ed30c99380b90b/libs/banglejs/jswrap_bangle.c#LL1598C1-L1605C4 is hit.

So the only way to get unlock whilst screen is off, is to have all (lockTimeout,backlightTimeout,lcdTimeout == 0) , equivalent to setLCDTimeout(0).  I do not want to call setLCDTimeout(0), I want to invidually control the timeouts, eg. lcdTimeout 5000, lockTimeout 0.  But currently not possible, because of how the code is arranged.

**Comment by gfwilliams** [comment]
I think this can be closed now?
