### ISSUE TITLE
Bangle JS2 HRM-raw raw value 0 in 2v18 firmware

### ISSUE THREAD

**Issue by kjjohnsen** [espruino/Espruino#2408]
In 2v18, the "raw" value inside the object passed to the HRM-raw callback is always 0.  This value was populated in 2v17.

**Comment by gfwilliams** [comment]
Thanks for the report - this one was fixed 2 weeks ago with d58609fee802eebcecd1734ad6e6c38afc519aa2 so if you use a cutting edge built it's sorted
