### ISSUE TITLE
Potentially inconsistent behaviour when throwing undefined on Linux

### ISSUE THREAD

**Issue by marccarigiet** [espruino/Espruino#2423]
-Plattform: [Linux, Ubuntu 20.04]

**Description**
Upon throwing undefined, Espruino exits normally and with a 0 exit code and without any output.

**Test case**
Test code to reproduce the behaviour:
```js
throw undefined;

```

**Expected behaviour**
Using Espruinos behaviour on the following snippet and other JavaScript Engines as references
```js 
throw null;
```
I would expect a nonzero exit code and "Uncaught undefined" to be outputted.

**Additional context**
This was found using comparative testing between multiple JavaScript engines. This could very much come down to a design choice. I just wanted to let you know in case it is not intentional

**Comment by gfwilliams** [comment]
Thanks - just fixed
