### ISSUE TITLE
E.showMenu(): onchange method not called

### ISSUE THREAD

**Issue by nxdefiant** [espruino/Espruino#2437]
With Bangle.js2 and firmware 2v19 up to 2v19.86 in the following code example basically [taken from the tutorial](http://www.espruino.com/Bangle.js+App+Settings)
```
const settings = {};

E.showMenu({
    'How Many?': {
      value: 0|settings.howmany,  // 0| converts undefined to 0
      min: 0, max: 100, step: 1,
      onchange: v => {
        console.log("change");
      }
    },
  });
```

the onchange callback is not called when pressing the button. Last time seen working in firmware 2v18. Other menu variants (including setting max=10 in the above code) seem to work ok.

**Comment by gfwilliams** [comment]
Yes - it's perhaps an odd decision but all over the watch we use the button as 'back', so that's what it is here too
