### ISSUE TITLE
Uint8Array constructor byteOffset is restricted to 2bytes

### ISSUE THREAD

**Issue by wagnerf42** [espruino/Espruino#2439]
hi,

byteOffset in the Uint8Array constructor stops working when the integer goes over 65536.
it just wraps around so surely this offset is coded in C as a 2 bytes integer.

i'm not sure how feasible it would be to switch to a larger integer ?

**Comment by wagnerf42** [comment]
thinking again about it, it's not such a big deal, I will be able to get around it using storage.read(). i'm not even sure we did'nt already discuss this actually.
so, maybe we could close the issue.

**Comment by gfwilliams** [comment]
Ok, well, I think this isn't something easily fixable - we only have a certain amount of space in the structure to store an offset.

However it should throw an error, not wrap - i'll see about getting a fix in
