### ISSUE TITLE
Workflow File for Linux

### ISSUE THREAD

**Issue by d3nd3** [espruino/Espruino#2452]
Artifact creation doens't seem to work for Linux builds.

bin/espruino doesn't match the `bin/*.*` regexes?

I changed it temporarily for mine to compile.

**Comment by gfwilliams** [comment]
You mean when using GitHub actions it doesn't upload the binary?

Honestly, I thought that wasn't worth it. When you're on Linux or WSL you just type `make` on your PC and it's built in about 5 seconds, if that.

**Comment by d3nd3** [comment]
Having trouble:
```
gcc: warning: Git: linker input file unused because linking not done
gcc: error: Git: linker input file not found: No such file or directory
```

**Comment by gfwilliams** [comment]
What are you doing that's causing the trouble? What commands? where? what OS?

**Comment by d3nd3** [comment]
```
source ./scripts/provision.sh LINUX
make
```
Windows 11, WSL2 debian

**Comment by gfwilliams** [comment]
That's strange - I wonder why it says `Git:` though?

I just tried again and it works fine here.

Is it possible you're trying to built it through `Git Bash` and not `WSL`?

**Comment by d3nd3** [comment]
I am definitely in a debian shell, I will try a clean repo.

**Comment by d3nd3** [comment]
Works on my laptop. Hm.

**Comment by gfwilliams** [comment]
Maybe try `V=1 make` and see if it gives some clue as to why it's saying `2188a9236:` and `Git:`

Only other thing I can think is maybe Git is set up to check out everything with Windows Line Endings, and that's why it's screwing it up?

**Comment by d3nd3** [comment]
I am using `autocrlf=input`

and I do have a weird git wrapper, that either calls windows git or linux git depending on CWD.

**Comment by d3nd3** [comment]
Ok, it works on my ubuntu wsl1, which ran python2.  It might just be that it works only with python2?

Which python version do you use?

**Comment by d3nd3** [comment]
Okay, that is really funny, my cheeky:
`echo "windows Git"`
Obviously messed up some output from some of the scripts, if its piped or something.!!!
Silly me! Sorry.

**Comment by gfwilliams** [comment]
Ok, great! :)
