### ISSUE TITLE
Typed arrays are broken

### ISSUE THREAD

**Issue by YekkeTechie** [espruino/Espruino#2463]
Typed arrays seem buggy with the new update (`2v21.6`). For example:
```js
console.log(new Uint8Array([1, 2, 3]));
```
prints
```
>new Uint8Array(3)
```

**Comment by gfwilliams** [comment]
What platform are you on? I just tried on the linux build and an Bangle.js and it appears fine on those.

All I can see that has trouble is the Emulator? It seems maybe there's some issue with the Emscripten build there - I'll roll that back for now

**Comment by gfwilliams** [comment]
edit: just rolled back to 2v20 and same problem! I'll have to debug this tomorrow.

**Comment by gfwilliams** [comment]
Just fixed if you refresh the IDE now - that was a total nightmare to track down
