### ISSUE TITLE
 "STRINGIFY" redefined

### ISSUE THREAD

**Issue by brendena** [espruino/Espruino#2467]
So "STRINGIFY" seems to already be named in nordic_common.h

targetlibs/nrf5x_15/components/libraries/util/nordic_common.h:142: warning: "STRINGIFY" redefined
  142 | #define STRINGIFY(val)  STRINGIFY_(val)

So I'm suggesting just renaming STRING**I**FY to STRING**E**FY.  Then changing the names inside this project.  The define shows up around 8 times so it should be easy fix.  

Should get the point across but still be unique enough such that the define won't be in any library.

**Comment by gfwilliams** [comment]
Thanks - yes, it was a minor annoyance but it didn't really affect the build as the defines all did the same thing.

I've just renamed it to `ESPR_STRINGIFY` - I think generally when we have issues like this we should just prefix with JS_ or ESPR_ (ESPR_ is used for a lot of #defines). At least then it's obvious it's related to espruino
