### ISSUE TITLE
Storage.writeJSON and Storage.readJSON are incompatible when numeric keys are present

### ISSUE THREAD

**Issue by PVTejas** [espruino/Espruino#2484]
[espruino/Espruino@59dda13](https://github.com/espruino/Espruino/commit/59dda13c259888671276a55dbcdb7579223d6329) breaks `Storage.readJSON` in cases where dict keys are purely numeric

```
require("Storage").writeJSON("test",{"1":1});
require("Storage").readJSON("test");
```

Throws the error `Got INT expected '}'`

Related issues:
- https://github.com/espruino/BangleApps/issues/3310
- https://github.com/espruino/BangleApps/issues/3346

**Comment by halemmerich** [comment]
It could be later commits on the same code that break this, https://github.com/espruino/Espruino/commit/59dda13c259888671276a55dbcdb7579223d6329 is just the first introducing the change.

**Comment by PVTejas** [comment]
That is likely the case. My bad.

**Comment by gfwilliams** [comment]
Thanks! Just fixed it hopefully so on new firmwares this should all work again
