### ISSUE TITLE
ESP32_IDF4 (ESP32C3) support

### ISSUE THREAD

**Issue by MaBecker** [espruino/Espruino#2499]
This build is on development stage, collecting issues here.

- [x] analogRead support
- [x] REPL doesn't update until there's a newline, only via serial connection
- [x] TLS/Crypto support (update Espruino to use new mbedtls)
- [x] Neopixel support
- [x] REPL via BLE support 
- [x] Switch BLE support (ESP32.enableBLE(false|true) * 
- [x] Wifi only station mode
- [x] Switch Wifi support (ESP32.enableWifi(false|true) * 

* free additional memory

Please [ask questions on the forum post](https://forum.espruino.com/conversations/395499)

(edited by @gfwilliams, @MaBecker )

**Comment by c3c** [comment]
Hey, I realize this is in active development, just eager to test on this new board and wanted to report what currently works for me.

I compiled for ESP32C3_IDF4 and uploaded the firmware. So far I'm able to connect via BLE and get a working REPL. 
Via the Web IDE (over BLE) the device disconnects as soon as I try to upload data/files.
Via USB serial I don't seem to get 2-way interaction (although I do see the bootloader printouts and espruino logo). I'm guessing that might have to do with a slightly different pinout(?) Using M5StampC3.

Is this expected with what is currently implemented?

**Comment by gfwilliams** [comment]
> Via USB serial I don't seem to get 2-way interaction

What happens if you press enter? Just yesterday I fixed the issue where the REPL didn't update immediately (only after newline) so that could be what you were seeing?

**Comment by c3c** [comment]
I had cloned the Git commit right before your REPL commit. Looks like I have the same issue though on master [e1838a2](https://github.com/espruino/Espruino/commit/e1838a26c705e92aaf5e1e8e78e8ec3ed7233c91) (I made sure to `make clean` just in case).

Can the `default_console` configuration affect this?

**Comment by gfwilliams** [comment]
I don't think `default_console` would affect it - I guess it could even be your terminal app (if it's got RTS/CTS flow control enabled)

**Comment by gfwilliams** [comment]
All items complete now and it's available as a cutting edge build, closing this. Definitely feels like a usable build now
