### ISSUE TITLE
Any plans to switch to python3?

### ISSUE THREAD

**Issue by MaBecker** [espruino/Espruino#2500]
Some scripts do still use `python`instead of `$PYTHON`. For the make files it is already implemented. Any plans to switch?

**Comment by gfwilliams** [comment]
I think all the scripts are compatible with python3 now. Which ones did you find that don't reference it directly?

I'd rather not use $PYTHON - it's not set on my system anyway, and IMO that's just a worse way of writing `python`. We should just use `python3`

**Comment by MaBecker** [comment]
this link will give you a list 

https://github.com/search?q=repo%3Aespruino%2FEspruino%20%2Fusr%2Fbin%2Fenv%20python&type=code

**Comment by gfwilliams** [comment]
If you want to change them, check they're ok and do a PR that'd be great? But from my point of view this isn't a high priority as it all works for me as-is

**Comment by MaBecker** [comment]
look's like you have linked python3 to python or somethin else to make python work ;-)

**Comment by gfwilliams** [comment]
`sudo apt install python-is-python3`

I don't believe I have done anything special though - all the GitHub action builds work fine as is

**Comment by MaBecker** [comment]
Ok,  it's all Mac OS X based, so let's close it.
