### ISSUE TITLE
Images pixel crop when rotating

### ISSUE THREAD

**Issue by arvere** [espruino/Espruino#2535]
Hello! Here's something I found with the Graphics library.
The following code would supposedly draw two white square images with a black border. The first is rotated 180 degrees:

```
var img = {
  width : 8, height : 8, bpp : 8,
  buffer : new Uint8Array([
    0,0,0,0,0,0,0,0,
    0,255,255,255,255,255,255,0,
    0,255,255,255,255,255,255,0,
    0,255,255,255,255,255,255,0,
    0,255,255,255,255,255,255,0,
    0,255,255,255,255,255,255,0,
    0,255,255,255,255,255,255,0,
    0,0,0,0,0,0,0,0,
  ]).buffer
};
g.drawImage(img,4,4,{rotate:Math.PI});

var img2 = {
  width : 8, height : 8, bpp : 8,
  buffer : new Uint8Array([
    0,0,0,0,0,0,0,0,
    0,255,255,255,255,255,255,0,
    0,255,255,255,255,255,255,0,
    0,255,255,255,255,255,255,0,
    0,255,255,255,255,255,255,0,
    0,255,255,255,255,255,255,0,
    0,255,255,255,255,255,255,0,
    0,0,0,0,0,0,0,0,
  ]).buffer
};
g.drawImage(img2,4,16);
```

Expected result:
Both images look the same

Actual result:
The first image ends up with pixels cropped on the bottom and left sides (noticeable by the lack of a black border)

Env:
Tested with a Bangle 2, 2v23.9 and the web emulator

Notes:
Discussion in the forum: https://forum.espruino.com/conversations/398259/

**Comment by gfwilliams** [comment]
Thanks for the report! I'll look into this when I get a moment
