### ISSUE TITLE
Unexpected result in array manipulation and arithmetic operations

### ISSUE THREAD

**Issue by theauk** [espruino/Espruino#2547]
https://github.com/espruino/Espruino/commit/7000f5d94f998f6bac6ec1186f037eb0df4234be

**Test case**

```
>var a = [1]; console.log((a.unshift(2) / (a[0] / a.reverse().length)));
4
```

**Expected Behavior**
I would expect it to return 2 from doing (2 / (2 / 2)). Running the test case on other JavaScript engines (Node, Hermes, and QuickJS), I get the expected 2.

Even if I move unshift out and replace it by 2 in the formula (the length of the new array), it still returns 4:

```
>var a = [1]; a.unshift(2); console.log((2 / (a[0] / a.reverse().length)));
4
```

or step-by-step:

```
>var a = [1]
=[ 1 ]
>a.unshift(2)
=2
>a
=[ 2, 1 ]
>a[0]
=2
>console.log(2 / (a[0] / a.reverse().length))
4
```

However, replacing `a[0]` or `a.reverse().length` with their respective values seems to solve it:

```
>var a = [1]; console.log((a.unshift(2) / (2 / a.reverse().length)));
2

>var a = [1]; console.log((a.unshift(2) / (a[0] / 2)));
2
```

**Comment by gfwilliams** [comment]
Thanks! The issue here was in Espruino we have a LVALUE for the left-hand side of the `/` op, but we only turned it into an RVALUE after parsing the second argument.
