### ISSUE TITLE
Reference errors

### ISSUE THREAD

**Issue by bartmichu** [espruino/Espruino#316]
First of all I don't know if it's a bug or a feature, maybe that's how Espruino is supposed to work, but I couldn't find any reference.

When trying to use variables that are not defined, Espruino is happy to accept them instead of throwing a ReferenceError:

```
var x = foo;
=undefined
```

```
function f() {return arguments.length;}
f(blahblah);
=1
```

**Comment by gfwilliams** [comment]
branch here: https://github.com/espruino/Espruino/tree/ReferenceError

**Comment by gfwilliams** [comment]
Post on it asking for opinions here: http://forum.espruino.com/conversations/272650/#comment12448624

**Comment by gfwilliams** [comment]
Merged into master now. Branch deleted.
