### ISSUE TITLE
More support for ASM in Espruino

### ISSUE THREAD

**Issue by jumjum123** [espruino/Espruino#355]
Status: Assembler is a good way to speed up functions. Right now there are only a few functions.
Expectation is, this will change in the future, the Memorytest is an example for that.
Problem: The more assembler functions we get, the more will "kind of disappear" in modules.
Therefore it will be challenging to avoid overwriting of already defined assembler based functions.
Proposal: Add 
- new parameter to process.memory "Start_for_Extensions", set to stackEndAddress on reset
- new function like E.createAssembler(FunctionName,Format,BinaryCode).
So a call like 
E.createAssembler("myASMfunction","int(int)",new Uint16Array([0x7047]));
would:
- store binary starting at "Start_for_extensions"
- create a function named "myASMfunction" getting an int value and returning an int value
- set "Start_for_extensions" to "Start_for_extension + ArrayLength"
- returns Startadress in Memory of new function

**Comment by gfwilliams** [comment]
Closing this now, as `E.nativeCall` now has an optional third data argument that does exactly what's needed. It stores it in with normal variables too, so it can be saved and restored properly.
