### ISSUE TITLE
console.log(string) produces no output for some strings

### ISSUE THREAD

**Issue by SpenceKonde** [espruino/Espruino#365]
> var z="RAWR!\xF3Q\xF7\xBA\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xBA\xDC\x0F\xFE\xE0\xDD\xF0\x0D\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
> ="RAWR!ó" ... "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
> console.log(z)
> =undefined
> z.length
> =106

I'm not sure exactly what it is about this rather perverse string (it was encountered while playing with an EEPROM) trips up console.log.....

**Comment by gfwilliams** [comment]
Closing this - having looked at it, the characters do go in, but there's a `0x0D` in there which is carriage return. It returns to the beginning of the line and outputs `0` over everything else. If you look on a slow connection you can even see the text being written and erased.
