### ISSUE TITLE
I2C Repeated Start

### ISSUE THREAD

**Issue by tomgidden** [espruino/Espruino#390]
I'm trying to write a library for MPL3115A2 (note, NOT the existing MPL115A2) but according to the Arduino library along with various Google results, it appears that it needs Repeated Start capability on I2C: I think this means not sending a STOP command after a read or a write.

Whether or not this is correct behaviour for I2C slave devices (which as far as I can see should be able to support with and without repeated starts), it's been an issue on Raspberry Pi (since fixed), and was added to Arduino in v.1.0.1.

Related code (from the MPL3115A2 Arduino driver):
```C++
// These are the two I2C functions in this sketch.
byte MPL3115A2::IIC_Read(byte regAddr)
{
  // This function reads one byte over IIC
  Wire.beginTransmission(MPL3115A2_ADDRESS);
  Wire.write(regAddr);  // Address of CTRL_REG1
  Wire.endTransmission(false); // Send data to I2C dev with option for a repeated start. THIS IS NECESSARY and not supported before Arduino V1.0.1!
  Wire.requestFrom(MPL3115A2_ADDRESS, 1); // Request the data...
  return Wire.read();
}
```
and also, http://raspberry.znix.com/2013/03/raspberry-pi-and-repeated-start-i2c.html

I'd guess this might be best presented as an extra optional boolean parameter on `I2C.readFrom` and `I2C.writeTo`, although the fix for #370 might scupper that.

**Comment by errantspark** [comment]
I'm trying to get an MMA8451 (http://www.adafruit.com/datasheets/Freescale_MMA8451QR1.pdf) working and it doesn't seem like the repeated start is working properly? 
I get 

     Uncaught InternalError: Timeout on I2C Read BUSY

when I try to read after writing an address with stop set to false. Reading gives me the same 7 bytes every time.

Relevant Arduino code:
https://github.com/adafruit/Adafruit_MMA8451_Library/blob/master/Adafruit_MMA8451.cpp

**Comment by gfwilliams** [comment]
Ok, thanks. Will try and look into it when I get back to the UK.

What board was this on? The I2C implementations are different on different chips

**Comment by gfwilliams** [comment]
What board were you using? a Pico?

**Comment by errantspark** [comment]
yup, using a pico

**Comment by gfwilliams** [comment]
Fixed. On the MPL3115, the following code now works:

```
function r(addr) {
  i2c.writeTo({address:0x60, stop:false}, addr);
  return i2c.readFrom(0x60,1)[0];
}

var i2c = I2C3;
i2c.setup({sda:B4,scl:A8});
r(0x0c)==196; // WHOAMI
```

**Comment by errantspark** [comment]
Just came back to this project, using 1v85 and I cannot get it to connect on I2C1. On I2C3 (on a different board) it works fine. Unfortunately for my current project i'm using those pins for SPI so a way to get this working with I2C1 would be super helpful. Same `Uncaught InternalError: Timeout on I2C Write BUSY` error as before. Using the code snippet from above but different (obviously) addresses.

**Comment by gfwilliams** [comment]
You sure it's not that you're missing pullup resistors or having SDA/SCL mixed? The code is identical for I2C1/2 and 3 - so the chances of it working on one and not the other are pretty minimal.
