### ISSUE TITLE
New ALWAYS_INLINE causes problems when building with Clang (or GCC 5+)

### ISSUE THREAD

**Issue by hugovincent** [espruino/Espruino#450]
The new changes to ALWAYS_INLINE cause the build to fail with Clang with a linker error:
```
Undefined symbols for architecture x86_64:
  "_jsvGetRef", referenced from: ...
  "_jsvLock", referenced from: ...
  "_jsvLockAgain", referenced from: ...
  "_jsvUnLock", referenced from: ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [espruino] Error 1
```
This is because Clang defaults to GNU C11 and your code assumes inline behaves like GNU89, see: http://clang.llvm.org/compatibility.html#inline
This also affects GCC 5 and newer, see: https://gcc.gnu.org/gcc-5/changes.html

It can be fixed by adding `-std=gnu89` to the compiler command line when Clang or GCC 5 is used, but the better way would be to move the bodies of those functions to their respective header files.

**Comment by hugovincent** [comment]
This has become a problem again... for me, this fixed it:
```
diff --git a/src/jsutils.h b/src/jsutils.h
index 6b362a1..2dbe3ee 100644
--- a/src/jsutils.h
+++ b/src/jsutils.h
@@ -249,15 +249,15 @@ typedef int64_t JsSysTime;
 #define NO_INLINE __attribute__ ((noinline))
 
 /// Put before functions that we always want inlined
-#if defined(LINK_TIME_OPTIMISATION) && !defined(SAVE_ON_FLASH) && !defined(DEBUG)
-#define ALWAYS_INLINE inline __attribute__((always_inline))
-#elif defined(__GNUC__)
-// By inlining in GCC we avoid shedloads of warnings
-#define ALWAYS_INLINE inline
-#else
+#if defined(__clang__)
 // clang seems to hate being asked to inline when the definition
 // isn't in the same file
 #define ALWAYS_INLINE
+#elif defined(LINK_TIME_OPTIMISATION) && !defined(SAVE_ON_FLASH) && !defined(DEBUG)
+#define ALWAYS_INLINE inline __attribute__((always_inline))
+#else // defined(__GNUC__)
+// By inlining in GCC we avoid shedloads of warnings
+#define ALWAYS_INLINE inline
 #endif
 
 /// Maximum amount of locks we ever expect to have on a variable (this could limit recursion) must be 2^n-1
```

**Comment by gfwilliams** [comment]
Argh, sorry about that.

Odd though - does that imply that `LINK_TIME_OPTIMISATION` is now set in the Makefile? The idea is that it wasn't set when compiling for a Mac (it assumed clang).

**Comment by hugovincent** [comment]
Yes, strange. I can't find where `LINK_TIME_OPTIMISATION` gets defined. (It is a clean checkout of 6e2ea644aa826600ad2a5617122fb835e931349a though...).

**Comment by gfwilliams** [comment]
Wow, thanks! That feels like a really bad idea of Clang's!

Just tested here on a Mac, same problem (but then I updated it recently). I'll commit that patch in a sec.

**Comment by hugovincent** [comment]
(If it's any consolation, ARM's own compiler also defines `__GNUC__` when in gcc-compatible mode. The consensus seems to be that `__GNUC__` means GNU-compatible C, rather than specifically compiling with GCC... ugh).
