### ISSUE TITLE
System to compile an Espruino build with only the features you need

### ISSUE THREAD

**Issue by ganehag** [espruino/Espruino#466]
As the number of features and libraries increases so does also the final build size. It would be a good idea to write a more _modular_ build process. Maybe not as advanced as `menuconf` but flexible enough for both people and machine to configure.

I have a bunch of different solutions in my head of how to do this. But since this is your project Gordon, I ask for your opinion on:
- Generated single Makefile
- One Makefile for each board
- Configuration in PY file(s)
- Configuration in JS file(s)
- Using Python code to generate build code
- Using Node + JS code to generate build code
- Using Espruino + JS code to generate build code (2-step build)

I should point out that this configuration/build system is just to build the code. Not to generate the board specific source files.

**Comment by gfwilliams** [comment]
This is now handled with an array in `boards/BOARD.py` - so no menu, but it's trivial to tweak.

Also @jumjum123 has come up with a web service to do compiles as well:

* http://forum.espruino.com/conversations/286020/#13125086
* http://www.jumware.eu:89/file?fileName=Espruino/MakeFirmware
