### ISSUE TITLE
New Pico board definition has wrong chip part number, or wrong flash size

### ISSUE THREAD

**Issue by SpenceKonde** [espruino/Espruino#472]
The new PICO_R1_2.py board definition states that the part is STM32F401CC. That part has 256k flash 64k ram - but PICO_R1_2.py says the flash is 384k. I thought we were getting the STM32F401CD, which does have 384k flash?

**Comment by gfwilliams** [comment]
Thanks - yes, it'll be the CD, I just forgot to update the line in the `.py` file. There's also 96kB RAM, although for the moment I'm keeping it using only 48kB for code as the arrangement of flash pages is a bit tricky to work around.
