### ISSUE TITLE
E.getSizeOf() doesn't work on flat strings

### ISSUE THREAD

**Issue by SpenceKonde** [espruino/Espruino#484]
>process.memory();
={ "free": 2815, "usage": 435, "total": 3250, "history": 128,
  "stackEndAddress": 536926328, "flash_start": 134217728, "flash_binary_end": 219196, "flash_code_start": 134688768, "flash_length": 524288 }
>var tester=new Uint8Array(4096);
=new Uint8Array(4096)
>E.getSizeOf(tester);
=1
>process.memory();
={ "free": 2554, "usage": 696, "total": 3250, "history": 137,
  "stackEndAddress": 536926328, "flash_start": 134217728, "flash_binary_end": 219196, "flash_code_start": 134688768, "flash_length": 524288 }
> 

Expected result: 259 (based on memory usage comparison) - 256 jsvars for the data, and 3 for overhead.
Actual result: 1. 

That increase in memory efficiency associated with flat strings will be a great boon when it is expanded to include module prototype functions and functions in the root scope.

**Comment by gfwilliams** [comment]
Thanks, just fixed. Also took the opportunity to use normal strings for ArrayBuffers if it saves memory and/or is faster.
