### ISSUE TITLE
Uint8ClampedArray

### ISSUE THREAD

**Issue by gfwilliams** [espruino/Espruino#486]
Never seen this before but it looks like it's existed for a while:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray

This would be awesome for stuff like LED strings, where you could forget about making sure the value wasn't greater than 255 or less than 0.

**Comment by loop23** [comment]
+1 - I do a lot of work with led strings!
