### ISSUE TITLE
JSON.stringify should dump typed arrays as objects

### ISSUE THREAD

**Issue by gfwilliams** [espruino/Espruino#489]
https://github.com/espruino/Espruino/commit/17b6c3f333acf9b1630a979ac2602c240c57e18a#commitcomment-9507787

```
JSON.stringify(new Uint8Array([0,1])); // Produces the string: '{"0":0,"1":1}'
```

Should keep the same output format as currently when it's used to print out to the console though.

**Comment by gfwilliams** [comment]
As in the bug above, dumping `new Uint8Array(...)` isn't valid JSON at all

**Comment by SpenceKonde** [comment]
Hmm - the standard way is hideous. Wouldn't projecting it as a normal array be much better?

**Comment by gfwilliams** [comment]
Yes, but then it's not doing what JSON.stringify should, and someone will complain that it's not compliant.

So yeah, this is why I've been putting off fixing it :)

**Comment by gfwilliams** [comment]
Meh. Dumping as non-spec-compliant arrays anyway, but documenting it in `JSON.stringify`
