### ISSUE TITLE
Same name for multiple properties

### ISSUE THREAD

**Issue by bartmichu** [espruino/Espruino#495]
I believe it shouldn't be possible to create two properties with the same name:

```
>var foo = {bar: 1, baz: 2, bar: 3}
={ "bar": 1, "baz": 2, "bar": 3 }
```

But then:
```
>for (var i in foo) {console.log(foo[i])};
1
2
1
```

After playing with other interpreters I would expect `{"bar": 3, "baz": 2}` but I'm not sure what's in the specs.

**Comment by gfwilliams** [comment]
Ahh.  Thanks... Yes,  I think this should probably report an error.

**Comment by gfwilliams** [comment]
Seems like other interpreters don't report an error, so not doing it here either.

**Comment by bartmichu** [comment]
Error reporting is not an issue, I was thinking more about returned value i.e. that second "bar" property shouldn't even be added to the object.
