### ISSUE TITLE
No docs for "Allow filesystem to work on user-defined pins (fix #427)"

### ISSUE THREAD

**Issue by SpenceKonde** [espruino/Espruino#516]
There is a commit named:

Allow filesystem to work on user-defined pins (fix #427)

However, there is no documentation on how to use this functionality. 

Edit: Oh, I found it. It's under E (E.connectSDCard) instead of fs...

**Comment by gfwilliams** [comment]
oops - posted on the wrong bug!

------------

There actually is, it's just hard to find: http://www.espruino.com/Reference#l_E_connectSDCard

I'll add a bug in EspruinoDocs - a general FS documentation page is needed badly anyway.

---------------

I get shouted at if I add non-standard things to the 'standard' libraries, hence sticking it in `E` :( Am writing better docs now
