### ISSUE TITLE
Debris from previous ESP8266 iterations in reference docs

### ISSUE THREAD

**Issue by SpenceKonde** [espruino/Espruino#517]
According to the documentation (espruino.com/Reference) we seem to have a preponderance of ESP8266 modules that aren't supported now that it's handled with NetworkJS. The old ESP8266 and ESPWiFi classes are thus obsolete (and as I understand it, they didn't actually work anyway) - and should be removed, because they're likely to steer people down the wrong path. 

Meanwhile, the NetworkJS reference documentation inaccurately references WizNET (copy/paste error).

**Comment by gfwilliams** [comment]
Thanks - I'd forgotten it would still be in the reference...

**Comment by gfwilliams** [comment]
sorted - thanks!
