### ISSUE TITLE
misleading setTimeout and setInterval

### ISSUE THREAD

**Issue by WebReflection** [espruino/Espruino#532]
[Standard timers](http://www.w3.org/TR/2011/WD-html5-20110525/timers.html#timers) have the ability to pass arbitrary amount of arguments since about ever and in every JS engine.

This should log 123, and not an object with a time property.

```js
setTimeout(function (i) { console.log(i); }, 500, 123);
```

This causes incompatibilities with many nodejs modules, and forces creation of user-land callbacks even when it's not necessary.

Moreover, the current passed object is totally unexpected and also the length of the arguments is 2, with an undefined as second argument, which is also inconsistent and unexpected.

**Comment by gfwilliams** [comment]
Odd - I was totally unaware of that. Definitely looks like a good thing to add.

**Comment by gfwilliams** [comment]
OOps - referenced wrong issue

**Comment by WebReflection** [comment]
I was wondering ... indeed there was no arguments related code in the fix ... oh well, good you fixed the other one anyway. Cheers
