### ISSUE TITLE
OSC support

### ISSUE THREAD

**Issue by Jorgen-VikingGod** [espruino/Espruino#542]
would be nice to have OSC support library on Espruino
like this:
https://github.com/CNMAT/OSC

more about this protocoll:
http://opensoundcontrol.org/

**Comment by loop23** [comment]
+1
I may give it a try, I'm into sound protocols and would like to study OSC for personal sake

**Comment by gfwilliams** [comment]
This issue was moved to espruino/EspruinoDocs#145
