### ISSUE TITLE
Uncaught InternalError: setDeviceClockCmd: Unknown Device 816 (same as #409 and #559)

### ISSUE THREAD

**Issue by asez73** [espruino/Espruino#612]
Sorry, but it reappeared on Espruino board with interpreter 1v80.452 this morning...

Uncaught InternalError: setDeviceClockCmd: Unknown Device 816
 at line 1 col 37
Serial4.setup(115200,{tx:C10,rx:C11});

**Comment by gfwilliams** [comment]
Thanks for the report...

Sorry about that - not sure how that happened (I was pretty sure I did a global search when I changed the relevant code, but looks like I missed loads of stuff).

**Comment by asez73** [comment]
No problem, I just updated the board and found this bug at load time...
