### ISSUE TITLE
Use SD card as swapfile

### ISSUE THREAD

**Issue by gfwilliams** [espruino/Espruino#62]
Espruino's fixed-size JsVar blocks were designed for this, but it was never implemented.

You'd have to change jsVarCache, jsvLock and jsvUnLock, and then store only the most-used (and locked) JsVars in RAM - writing the rest onto the SD card. Probably quite a lot of work, but it'd be epic.

It would kill Garbage Collection speed (it might need a re-write?) but then if you had basically infinite memory that's not a huge issue.

**Comment by gfwilliams** [comment]
There's a branch that does this here:

https://github.com/espruino/Espruino/tree/variable_cache

It's still far from perfect:

* it's only built for linux
* the 'backing' data is just stored in a var called `variables`, and isn't written to a file 
* it does crash running some tests

But it proves that it can be done - and without hacking everything around so much that it doesn't run on 'normal' devices.

**Comment by gfwilliams** [comment]
related comment here: https://github.com/espruino/Espruino/issues/817#issuecomment-203382165

**Comment by tve** [comment]
> it does crash running some tests
Do you recall what crashed?

**Comment by gfwilliams** [comment]
No... but building for linux and doing `./espruino --test-all` might show it up.

I can't remember if this branch needs it, but you might want to edit build_platform_config and remove the RESIZABLE_JSVARS line.

**Comment by gfwilliams** [comment]
Killing this due to lack of interest - I guess variable_cache might still happen but honestly it's so easy to find boards with decent amounts of RAM/ROM built in now this isn't a big deal
