### ISSUE TITLE
Check that the password for an access point meets minimum requirements

### ISSUE THREAD

**Issue by nkolban** [espruino/Espruino#636]
Apparently there are rules on password sizes when becoming an Access Point.  This work item asks for study on what those rules might be and then handling of a user program calling `beAccessPoint` and not passing in a "good enough" password.

**Comment by nkolban** [comment]
We now check that if a password is supplied, it is at least 8 characters long.

**Comment by nkolban** [comment]
Code added to the code base and documentation added to the provisional user's guide.

**Comment by rakeshpai** [comment]
Verified. Throws an error for passwords shorter than 8 chars.

```
>ESP8266WiFi.beAccessPoint("Thing", "bad")
Uncaught Error: Password must be 8 characters or more in length.
 at line 1 col 41
ESP8266WiFi.beAccessPoint("Thing", "bad")
                                        ^
=undefined
```
