### ISSUE TITLE
ESP8266WiFi.beAccessPoint shouldn't require a password

### ISSUE THREAD

**Issue by rakeshpai** [espruino/Espruino#637]
It should be possible to create an access point without a password. With the little work I've done with esp8266/arduino, I know that this is possible to do.

Right now, a call to .beAccessPoint without a password (or an empty password) fails:
```
>ESP8266WiFi.beAccessPoint("Thing")
Uncaught Error: No password.
 at line 1 col 34
ESP8266WiFi.beAccessPoint("Thing")
                                 ^
=undefined
```

**Comment by rakeshpai** [comment]
Can't seem to add labels. (Mods only?) Modified the title to make it clear that this is about the ESP8266.

**Comment by gfwilliams** [comment]
Just done :)

**Comment by nkolban** [comment]
In jswrap_esp8266 we have a function called `jswrap_ESP8266WiFi_beAccessPoint` which is where being an access point is controlled.   The design has been changed to no longer reject this function if we supplied no password.  Instead, if no password is supplied then we become an "Open" access point with no access restrictions (password).  In addition, we now check that if a pssword is supplied, it is at least 8 characters long.

**Comment by nkolban** [comment]
Code added to the code base and documentation updated in the provisional user's guide.

**Comment by rakeshpai** [comment]
Thanks @nkolban. However, I'm seeing some strange behaviour. The password isn't a required field anymore. However, it appears that the SSID passed in isn't honoured, at least the first time `.beAccessPoint` is called. I get an SSID that looks like `ESP_FC6182` or something, in my list of networks. The second call to `.beAccessPoint` seems to use the SSID correctly though.

I can seem to replicate this every time after a reset. Let me know if you need any more details.

**Comment by nkolban** [comment]
I have retagged as a bug to look at the code again and see if there is anything obvious to be seen.  Following that, we'll test becoming an access point from a number of different perspectives.  Obviously if you can find a repeatable pattern that demonstrates the issue, we'd love to hear that.

**Comment by nkolban** [comment]
The `beAccessPoint` has been reworked into the `wifi.createAP()` function which will be available in a couple of days.  We need to re-examine this issue in the light of #589 changes.

**Comment by nkolban** [comment]
@rakeshpai Could I impose on you to re-examine and see if this issue is still present in the latest builds.  The whole area was recently re-done.
