### ISSUE TITLE
Provide the ability to stop being an access point.

### ISSUE THREAD

**Issue by nkolban** [espruino/Espruino#640]
The ESP8266 port has the ability to allow us to be an access point such that stations can connect to us.  Unfortunately, we don't have a corresponding API to stop us being an access point.  This request asks for the creation of that function.

**Comment by nkolban** [comment]
A new exposed function called `ESP8266WiFi.stopAP()` has been added into the code and documented in the provisional user's guide.

**Comment by rakeshpai** [comment]
Works a treat! Thanks, @nkolban
