### ISSUE TITLE
Guard against incorrect user function calls where possible

### ISSUE THREAD

**Issue by nkolban** [espruino/Espruino#646]
While working today, I found that I was calling `setWatch` with arguments of `pin` and `func` where I should have been calling them with `func` and `pin`.  This took me a while to figure out and I couldn't help but wonder if Espruino should perform parameter checks (where possible) on supplied parameters to ensure that they are as expected.  The trade off here would be a marginal performance penalty against code execution correctness by problems introduced by incorrect coding.

**Comment by gfwilliams** [comment]
Yes, it should do checks... In fact it already has the checks you suggest, plus more: https://github.com/espruino/Espruino/blob/master/src/jswrap_io.c#L452

I didn't think you had an Espruino board, so is is possible this is something ESP8266-specific (like `jshIsPinValid` might not be working)
