### ISSUE TITLE
Interrupt edge detection via hardware support

### ISSUE THREAD

**Issue by nkolban** [espruino/Espruino#652]
Part of the capability of `setWatch` is to determine what signal edge should cause the interrupt to fire, this can be `rising`, `falling` or `both`.  Examining the Espruino code base, it seems that this logic is performed in the function called `jsiShouldExecuteWatch`.

This issue suggests a possible optimization that would be applicable to some boards.  On some boards, the interrupt trigger can be defined at the hardware level such that a hardware interrupt occurs on a rising edge, a falling edge or both.  Putting it another way, when the logic of `setWatch` is called, the design could ask the board to only watch for edge changes of the correct type and there would no longer be the need to process all edge changes in Espruino logic.

Obviously this is merely an optimization and logic behaves correctly as of now so there is no great imperative to make any changes.  However it is probably worth logging the notion should performance or latency become an issue and the underlying board exhibiting the issue had hardware assist for edge detection.

**Comment by gfwilliams** [comment]
Right now we wouldn't be able to do this without an API change in JavaScript land - while you can request that your JS gets called on the falling edge, the `lastTime` field is updated on the rising edge so you can measure pulse widths without calling into JS too often - and I think this does get used quite a lot.

While it'd be nice, I think this definitely falls into the 'optimisation' category as you noted though. The amount of times this would actually be helpful for the user is really very small.
