### ISSUE TITLE
Debugger not working on ESP8266 board

### ISSUE THREAD

**Issue by nkolban** [espruino/Espruino#659]
When we run the `debugger` command on the ESP8266 board we get the debug prompt but it just seems to hang there for a few seconds and then crashes the board.  This issue is being created to determine what we might be able to do to get the debugger operational.

**Comment by gfwilliams** [comment]
You need the context switching code from Arduino, since the debugger uses and inner loop that won't return control to the system

**Comment by MaBecker** [comment]
There will be no debugger for ESP8266 - so close this
