### ISSUE TITLE
Add USB Mass Storage support if an SD card is inserted

### ISSUE THREAD

**Issue by gfwilliams** [espruino/Espruino#66]
So if you insert an SD card and then plug Espruino in via USB, you get a virtual COM port as well as USB Mass storage device for the SD card.

This would be awesome - but potentially Espruino + the OS accessing the card at the same time could mess up the filesystem...

**Comment by tdulik** [comment]
This idea can be extended - the Mass storage could provide access to the RAM area where the JavaScript is stored.

This way, we could program the Espruino from the online web IDE version and using any browser. Just by downloading the generated JS from server and storing it to the mass storage device.

Mbed does it this way, and now also Micro:bit (which is based on Mbed).

(sorry if this idea is proposed in another feature request... this was the first link Google gave me)

**Comment by opichals** [comment]
Yes the flash content (say the Storage items) could be exposed that way (or via MTP or something simpler perhaps). But USB Mass storage would be the most convenient. It would be nice to see their implementation. Any links?

A related conversation also https://github.com/espruino/Espruino/issues/221#issuecomment-370337892.

**Comment by gfwilliams** [comment]
@opichals just beat me to it with the link :) In 1v96 there's actually a `Storage` module that implements a simple filesystem in Flash memory and which would be perfect for this.

I think exposing the contents of RAM could be a bit more involved, but `Storage` might not be too bad. I'd definitely be interested if someone wanted to have a go at implementing it. Having said that, just writing source code for execution does mean you miss out on some of Espruino's best features (eg the console, stack traces, debugging, etc).

... everything's going to get a bit more involved soon as I add support for USB on nRF52840. I'm not really sure if we'll be able to abstract everything away enough that there's not loads of code duplication everywhere :(

**Comment by gfwilliams** [comment]
Closing this - now the IDE has the Storage menus I'm not sure it's so important

**Comment by gfwilliams** [comment]
Yes, it'd be for STM32 only - you have to write a new one of: https://github.com/espruino/Espruino/blob/master/targetlibs/stm32usb/usbd_cdc_hid.c

One issue is that right now we can do HID and the virtual com port, but trying to do those two and mass storage could be tricky.

Plus you can't really do mass storage as it'd interfere with the FAT filesystem if the SD card was being written/read at the same time at a low level, so as suggested above you'd have to implement media transfer protocol (like Android devices do IIRC). It's feels very nontrivial, which is why we never really got around to it.

**Comment by rikkuness** [comment]
Thanks @gfwilliams , yeah that's about what I expected, for my own selfish needs I could probably even just write a FUSE program that implements the packet transfer protocol 😆 thanks again
