### ISSUE TITLE
Espruino Web IDE Console not responding.

### ISSUE THREAD

**Issue by adishavit** [espruino/Espruino#669]
Hi,

I flashed a NodeMCU devboard with the latest firmware (using ESP8266Flasher.exe). 
I can connect to the board with the Web IDE and the blinking LED demo seems to work fine.

However, the console on the left does not respond to keyboard inputs not does it display any print calls.

Any suggestions? What am I doing wrong?

**Comment by nkolban** [comment]
After a flash, I find that I sometimes have to physically reboot the ESP8266.  Can you try and cycle the device and see if that changes anything?
