### ISSUE TITLE
Memory Leak when auto-connecting to a non-existent AP

### ISSUE THREAD

**Issue by markusgritsch** [espruino/Espruino#670]
There seems to be a memory leak somewhere when the ESP8266 tries to auto-connect to a not-present AP.   Every 1-2 seconds a connection is attempted and 6 JSvars get periodically comsumed without any user code running.

After about 5 minutes, all 1023 JSvars are consumed, and the board resets.

The leaking is stopped, when I call ESP8266WiFi.disconnect().

**Comment by nkolban** [comment]
Starting to examine now.

**Comment by nkolban** [comment]
Fixes included in the master repository.  Latest firmware builds now include the fixes.  Waiting for @markusgritsch to validate.

**Comment by markusgritsch** [comment]
Thanks. Works fine.

ESP8266WiFi.init(); still looses two JsVars on each call though.
