### ISSUE TITLE
Remove I2C Slave address entry from jshardware.h

### ISSUE THREAD

**Issue by gfwilliams** [espruino/Espruino#676]
Oops. Sorry - just realised this was in there from a while back, and it was just a type change that @tve did :)

But same applies - we should rip `slaveAddr` out of `I2C` for now... I2C slave can't be done 'easily' with JS because it needs a guaranteed minimum response time to be reliable.

We should rip the `slaveAddr` field out for now, as a proper implementation will require a lot more work than that :)

**Comment by tve** [comment]
Agreed. And yes, I only made a type change 'cause for some reason 'char' was ending up as unsigned and some function needed to return -1.

**Comment by gfwilliams** [comment]
> for some reason 'char' was ending up as unsigned 

Wow - on ESP8266? Hmm, I guess a lot of stuff could do with changing then - that could lead to a few dodgy bugs.

**Comment by ebirger** [comment]
Or perhaps add -fsigned-char to the generic CFLAGS
