### ISSUE TITLE
Remove the use of struct espconn -> reverse in ESP8266

### ISSUE THREAD

**Issue by nkolban** [espruino/Espruino#681]
The ESP8266 port networking subsystem uses the struct espconn -> reverse as a pointer to app data.  It is believed that this is an invalid usage of that pointer structure.  This issue asks for a rework of the design to no longer use the reverse pointer within the structure but instead perform some more sophisticated mapping from a callback supplied espconn to the appropriate socketData structure.

See also:

* http://bbs.espressif.com/viewtopic.php?f=66&t=702

**Comment by tve** [comment]
The use of the reverse pointer is the right thing to do. I have not encountered any problem with it.
