### ISSUE TITLE
var a = 0; typeof a → "undefined"

### ISSUE THREAD

**Issue by luwar** [espruino/Espruino#683]
Wrong result of the typeof operator (tested in WEB IDE):

correct:
  var b = 5;
  typeof b
= "number"

wrong:
  var a = 0;
  typeof a
= "undefined"

**Comment by gfwilliams** [comment]
Wow, that's a strange one. Thanks! I'll look into it.

**Comment by gfwilliams** [comment]
Thanks for finding that - I'm pretty sure that would have caused some issues elsewhere too!
