### ISSUE TITLE
Close an HTTP client connection after receiving a response

### ISSUE THREAD

**Issue by nkolban** [espruino/Espruino#684]
When we use the HTTP module to send a GET request to an HTTP server there is a scenario where the socket connection to the partner is not closed after receiving a response.

When Espruino sends a request to the partner, today it includes a "Connection: close" HTTP header.  However, if the server does not honor that, when the response comes back, Espruino does not itself close the connection after receiving "Content-Length" bytes of payload.  There is a belief that it should as after receiving "Content-Length" bytes, that is the end of the transaction.

See also the forum thread here:

http://forum.espruino.com/conversations/276661/

**Comment by gfwilliams** [comment]
I'm tempted to close this - you're the only person who has had this problem. I believe it can be fixed pretty easily in software, and it's only an issue if you have a broken HTTP server  that ignores `Connection: close`
