### ISSUE TITLE
Broken link in http://www.espruino.com/Writing+Modules

### ISSUE THREAD

**Issue by nkolban** [espruino/Espruino#690]
At the Espruino web page found here:

http://www.espruino.com/Writing+Modules

There is a link at the section that reads:

Check out some of the `other modules` for examples 

The `other modules` link appears broken.

**Comment by gfwilliams** [comment]
Thanks! Just fixed (it'll get updated this week).

If you find other doc issues on the site, please can you use the `let us know` link in the bottom right? It'll create an issue on the EspruinoDocs repo with the file path in there already.
