### ISSUE TITLE
MQTT protocol

### ISSUE THREAD

**Issue by roccomuso** [espruino/Espruino#691]
Does it support MQTT communication?

**Comment by gfwilliams** [comment]
Yes, although only as a client. There's a library, and a page on it here: http://www.espruino.com/MQTT

**Comment by roccomuso** [comment]
ok, I'm gonna try it soon putting the espruino firmware on a NodeMCU devkit 1.0 (based on esp8266-12e). Have you ever tried this 'configuration'? should it works reliably?

**Comment by gfwilliams** [comment]
You might be better asking on http://gitter.im/espruino/Espruino - I think someone had tried MQTT with it though.

**Comment by roccomuso** [comment]
It seems that the MQTT module causes an error:
    ERROR: Out of Memory!
    Uncaught SyntaxError: Got EOF expected ','

**Comment by gfwilliams** [comment]
I think you probably need something with a bit more memory than the ESP8266 then - like the Pico.

Perhaps you could create your own copy of the module and remove some functionality.

This isn't an Espruino bug though, so I'm closing this. If you have problems, maybe you could post [on the Forum](http://forum.espruino.com/)?
