### ISSUE TITLE
Warn user when a function with "compiled"; on the first line makes it to the board

### ISSUE THREAD

**Issue by SpenceKonde** [espruino/Espruino#707]
Since the syntax for a "compiled" function in Espruino is legal JS, I think it would be a good idea for the Espruino to warn the user when they define a function that has "compiled" on the first line. If the Espruino sees that, the user probably thinks the code is compiled - yet something went wrong (maybe they were on a board that didn't support compiled js?). So we should warn them, so they're not wondering why the compiled function isn't any faster. I think the check only needs to be done when the function is defined though (and we might as well remove the "compiled"; at that point too - since it doesn't do anything other than waste a jsvar or so of memory).

**Comment by gfwilliams** [comment]
Yes, that sounds like a good idea. Less painful to do now the brackets get parsed off as well.
