### ISSUE TITLE
Not building on x86_64 linux

### ISSUE THREAD

**Issue by soapdog** [espruino/Espruino#714]
Trying to build on linux x86_64 using the instructions from the README file fails with  lots and lots of referenced functions that were never defined. The instructions were to clone the repo and issue make with no option.

Most of the errors are referencing ```jsvUnLock```.

**Comment by gfwilliams** [comment]
Can you post up the error messages? I actually develop pretty much everything on x86_64 so it should really work.

**Comment by gfwilliams** [comment]
Did you sort this out at all, or can you post error messages?

Otherwise given it works here, I'll close this.

**Comment by soapdog** [comment]
I will do a fresh pull and try again and post back.
