### ISSUE TITLE
1v83 neopixel issue

### ISSUE THREAD

**Issue by cbnatrix** [espruino/Espruino#751]
The upgrade from 1v82 to 1v83 appears to break the neopixel examples. Using SPI2.setup({baud:3200000, mosi:B15}) my code works perfectly with 1.82 but not 1v83 on a Pico.

**Comment by gfwilliams** [comment]
Thanks! I think it's related to https://github.com/espruino/Espruino/issues/748

So it's actually fixed already if you use the firmware from http://www.espruino.com/binaries/git/commits/master/ - however I'll try and figure out the root cause of this and will push out another firmware update asap
