### ISSUE TITLE
esp8266 wifi getStatus doesn't show savedMode

### ISSUE THREAD

**Issue by tve** [espruino/Espruino#752]
Currently savedMode is just a constant, need to show real saved opmode.

**Comment by MaBecker** [comment]
Hi @tve,   guess now I unterstand what's missing.

add a global static var to store savedMode

    static uint8  savedMode = 0;

set value when calling void jswrap_wifi_save(JsVar *what) {} and  jswrap_wifi_restore(void) {}

      savedMode = conf->mode;

return value when calling JsVar *jswrap_wifi_getStatus(JsVar *jsCallback) {}

      jsvObjectSetChildAndUnLock(jsWiFiStatus, "savedMode",
           jsvNewFromString(wifiMode[savedMode]));

**Comment by MaBecker** [comment]
https://github.com/MaBecker/Espruino/commit/5bf71e2dd42ecd7d12fecfa6ae3e31a9e92495d4
