### ISSUE TITLE
esp8266 Wifi library doesn't handle NULL, null, undefined parameters correctly

### ISSUE THREAD

**Issue by tve** [espruino/Espruino#753]
Need to understand how missing, null, and undefined parameters show up and code accordingly. Specifically, startAP() doesn't handle `{password: null}` correctly and if the options are `null` or missing there's a problem too.

**Comment by MaBecker** [comment]
Hi @tve, 

not sure if I understand this correctly.

This is how I understand startAP() 

* works without password
Wifi.startAP("TEST",{authMode:"open"},function(e){
  console.log("Started AP");
});

* for all other authMode a password is needed
Wifi.startAP("TEST",{authMode:"wpa_wpa2",password:"test1234"},function(e){
  console.log("Started AP");
});

Is that the point you where thinking about, when you created this issue ?

**Comment by MaBecker** [comment]
startAP does not handle a call like this correct:
````
Wifi.startAP("TEST",{authMode:"open", password:null}, function(e){
    console.log("Started AP");
});
````
add a extra if to catch this.
