### ISSUE TITLE
Print error message if input buffer gets full

### ISSUE THREAD

**Issue by gfwilliams** [espruino/Espruino#766]
We currently have `E.getErrorFlags` but a visible warning might save a bit of debugging time!

**Comment by wilberforce** [comment]
Rather than having to poll  `E.getErrorFlags` could we set up an event listener, and register a function to call on error conditions?

Then things like low memory could be alerted at the time before space runs out!

**Comment by gfwilliams** [comment]
I guess I could add an `E.on('error',function(flagName) {..})` sort of thing.

I wonder how much help it'd be? The events only get handled in the idle loop (they're not pre-emptive) so you're not going to be able to actually do anything about an out of memory event when it happens.

**Comment by wilberforce** [comment]
At least you know it just after it happens, I've been adding process.memory() debug statements. I suppose the debugger in the ide does this.
