### ISSUE TITLE
ESP8266 Tutorial no wifi.getIPInfo() method

### ISSUE THREAD

**Issue by olliephillips** [espruino/Espruino#771]
https://github.com/tve/EspruinoDocs/blob/master/tutorials/ESP8266_Flashing.md

Tutorial states ```wifi.getIPInfo();``` will return on object with connection info including IP. That command does not appear to exist the method appears to be ```wifi.getIP()```

I probably should have added this to the EspuinoDocs repo but the tutorial is not there yet it's in a fork of @tves, so thought that may confuse.

**Comment by tve** [comment]
fixed https://github.com/tve/EspruinoDocs/commit/e6cafcc94ee51146c742be818f2a58e87dc59307
