### ISSUE TITLE
JS EOL parsing bug with function names that contain underscores

### ISSUE THREAD

**Issue by jnewcomb** [espruino/Espruino#781]
ESP2866 running espruin­o_1v84.tve_master_d8dec28_esp8266
This one caught me out for a while so I though Id share here..

JS EOL parsing bug with function names that contain underscores
<h5>Paste this program into the edit window:
```javascript
function Test_One()
{}
```
Run it, you get this error:
```Uncaught SyntaxError: Got EOF expected '{'
 at line 1 col 20
function Test_One()```

<h5>Paste this program into the edit window:
```javascript
function TestTwo()
{}
```
Run it, you get this

```
=undefined```

**Comment by gfwilliams** [comment]
Thanks - I'll look into this - it's actually a Web IDE issue. Espruino counts brackets to see if it should continue onto a new line, so we generally recommend that your write in K&R style with the opening brackets on the same line - then you can just copy/paste into the left-hand side of the IDE.

The IDE itself contains some hacks to reformat your code if you don't write code that way, but it looks like there might be something wrong with parsing of names with underscores in.
