### ISSUE TITLE
Can somebody pelase implement sw uart support for esp8266?

### ISSUE THREAD

**Issue by HyGy** [espruino/Espruino#782]
I bought a nextion LCD what is using UART to communicate with the microcontroller. Can somebody please implement the SW or HW UART functionality to esp8266 to be able to use this type of smart LCD's?

**Comment by gfwilliams** [comment]
Closing this, as there's already an issue open for Software Serial here: https://github.com/espruino/Espruino/issues/549

Stuff like this should be generic, not ESP8266-specific. Then everyone can benefit from the changes.

**Comment by HyGy** [comment]
yes, thanks
