### ISSUE TITLE
libs/network/socketserver.c -> httpParseHeaders fails with larger buffer

### ISSUE THREAD

**Issue by dmcnaugh** [espruino/Espruino#783]
The `httpParseHeaders` function in `libs/network/socketserver.c` lines 79-99 is meant to find the end of the http headers by locating the **first** occurrence of `\r\n\r\n`. This has been working fine for everyone, with the default `CHUNK` size of 64. However, if you look at the code, you'll notice it doesn't stop when it finds the first occurrence, it keeps going until it reaches the end of the provided `receiveData`. So actually it finds **last** occurrence of `\r\n\r\n` in `receiveData`. This can cause a failure with a larger `CHUNK` size if another `\r\n\r\n` appears in the data.

``` c++
bool httpParseHeaders(JsVar **receiveData, JsVar *objectForData, bool isServer) {
  // find /r/n/r/n
  int newlineIdx = 0;
  int strIdx = 0;
  int headerEnd = -1;
  JsvStringIterator it;
  jsvStringIteratorNew(&it, *receiveData, 0);
  while (jsvStringIteratorHasChar(&it)) {
    char ch = jsvStringIteratorGetChar(&it);
    if (ch == '\r') {
      if (newlineIdx==0) newlineIdx=1;
      else if (newlineIdx==2) newlineIdx=3;
    } else if (ch == '\n') {
      if (newlineIdx==1) newlineIdx=2;
      else if (newlineIdx==3) {
        headerEnd = strIdx+1;
      }
    } else newlineIdx=0;
    jsvStringIteratorNext(&it);
    strIdx++;
  }
```

Thankfully the problem can be easily fixed with the addition of a single `break;` command inserted at line 95 as follows:

``` c++
      if (newlineIdx==1) newlineIdx=2;
      else if (newlineIdx==3) {
        headerEnd = strIdx+1;
        break;
      }
```

Causing the `while` loop to terminate when the **first** `\r\n\r\n` is found.
I've tested this in my own build and found it to work.

**Comment by gfwilliams** [comment]
That's awesome - thanks for tracking it down!
