### ISSUE TITLE
ESP8266 fails to build with new `esp-open-sdk` because of `lwip`

### ISSUE THREAD

**Issue by drasko** [espruino/Espruino#816]
Based on this: https://github.com/pfalcon/esp-open-sdk/issues/118, new library is named `liblwip_open`, and does not contain `espconn_` calls anymore.

However, Espruino uses `lwip_536` - https://github.com/espruino/Espruino/blob/master/Makefile#L1432, which calls `espconn_` API. 

The lib itself can be get form here: http://bbs.espressif.com/viewtopic.php?f=7&t=1528&p=5059#p5059, but the correct approach would be to replace calls to this lib with new `liblwip_open`.

**Comment by MaBecker** [comment]
@drasko check #851

**Comment by MaBecker** [comment]
now skd 2.0 is used for ESPs - so this issue can be closed.
