### ISSUE TITLE
JSON.stringify() produces invalid JSON if the input object contains a typed array

### ISSUE THREAD

**Issue by SpenceKonde** [espruino/Espruino#819]
```

{"base":new Uint8ClampedArray([0,255,255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]),"twinkle":[new Uint8Array(30),new Int8Array(30),new Int8Array(30)]}


```

This is not JSON. Browsers can't eval() or JSON.parse() it.

**Comment by gfwilliams** [comment]
It's this bug: https://github.com/espruino/Espruino/issues/489

I'd been putting off doing it, because the standards-compliant way is so horrible :)
