### ISSUE TITLE
WIZnet library

### ISSUE THREAD

**Issue by webtoucher** [espruino/Espruino#838]
https://github.com/Wiznet/ioLibrary_Driver
There are many updates in Ethernet library. Please update your code. I need support for old chips so much...

**Comment by gfwilliams** [comment]
I believe you can already use Espruino with older chips with the library that is included. The problem is that (as I think is the case with the newer library) you will have to compile Espruino for each different device you want to support - so I can't just do one build trust works for all of them

**Comment by gfwilliams** [comment]
Closing due to lack of response.
