### ISSUE TITLE
SPI.send function is being corrupted?

### ISSUE THREAD

**Issue by ceremcem** [espruino/Espruino#839]
Hi, 

I load Espruino v1.85 to the STM32F4-Discovery board, set the `SPI` port up with the following code: `SPI1.setup({"sck":A5,"miso":A6,"mosi":A7});` and short circuted the `mosi` and `miso` pins. The expected result is a echo, which is the observed result as far as we use the `.send()` function with only 1 parameter: 

```
>SPI1.send(5)      
=5
>SPI1.send("hello") 
="hello"
>SPI1.send("hello", 5, 26, 6) 
="\x00\x00\x00\x00\x00"
>SPI1.send("hello") 
="\x00\x00\x00\x00\x00"
>SPI1.setup({"sck":A5,"miso":A6,"mosi":A7})
=undefined
>SPI1.send("hello") 
="hello"
>SPI1.send(5) 
=5
```

**Comment by gfwilliams** [comment]
Well, [according to the docs](http://www.espruino.com/Reference#l_SPI_send), SPI.send is only meant to take 1 data parameter. The second parameter is for the `nss` pin.

My guess is that `SPI1.send("hello", 5, 26, 6)` is treating `5` as the `nss` pin, which has changed the pin state of `5` to an output, which then messed up SPI for you until you re-initialised it.

`5` is presumably `A5`, which you're using for `sck`.

So:

* Don't supply extra arguments - if you want to send more stuff do: `SPI1.send(["Hello",5,26,6])`
* If you're going to supply an argument for the `nss` pin - don't make it a pin that's currently used for SPI :)
