### ISSUE TITLE
Negative Date converts to string wrong

### ISSUE THREAD

**Issue by gfwilliams** [espruino/Espruino#854]
```
>(new Date(-1000)).toString()                                                   
="Thu Jan 1 1970 00:00:-1 GMT+0000" 
```

Mentioned here: http://forum.espruino.com/conversations/286378/#comment12966391

**Comment by wilberforce** [comment]
Does this just need abs(X) added to the h, m, s part?

https://github.com/espruino/Espruino/blob/2d30d810baba1a00819a69e04df311f9e89b082f/src/jswrap_date.c#L379

**Comment by gfwilliams** [comment]
No, because it's just another date in 1969.

Chrome says:

```
(new Date(-1000)).toString()
"Wed Dec 31 1969 23:59:59 GMT+0000 (GMT)"
```

It's getTimeFromMilliSeconds that needs changing.
