### ISSUE TITLE
`dump()` causes reset on ESP8266

### ISSUE THREAD

**Issue by ceremcem** [espruino/Espruino#860]
Hi, 

I can use every function of ESP8266-12 as expected, except for a `dump()` call which causes a reset if called after a `load()`: 

```
...
function unpack(t) {var e,n;try{if(e=JSON.parse(t.trim()),void 0===e)throw null}
function merge(t) {var e,n,o,i,r,f;for(e=slice$.call(arguments,1),n=0,o=e.lengt}
var ser = ASSERT(jsvGetLocks(var) < 15) FAILED AT src/jsvar.c:556
  #1[r2,l2] Object { 
    #2[r1,l2] ASSERT(jsvGetLocks(var) < 15) FAILED AT src/jsvar.c:556
REBOOTING!
 ets Jan  8 2013,rst cause:2, boot mode:(3,7)
load 0x40100000, len 1396, room 16 
tail 4
chksum 0x89
load 0x3ffe8000, len 776, room 4 
tail 4
chksum 0xe8
load 0x3ffe8308, len 540, room 4 
tail 8
chksum 0xc0
csum 0xc0
2nd boot version : 1.4(b1)
  SPI Speed      : 40MHz
  SPI Mode       : QIO
...
```

After a `reset()`, `dump()` works as expected: 

```
>reset()
=undefined

 _____                 _ 
|   __|___ ___ ___ _ _|_|___ ___ 
|   __|_ -| . |  _| | | |   | . |
|_____|___|  _|_| |___|_|_|_|___|
          |_| http://espruino.com
 1v85.134 Copyright 2016 G.Williams
Espruino is Open Source. Our work is supported
only by sales of official boards and donations:
http://espruino.com/Donate
Flash map 512KB:256/256, manuf 0xe0 chip 0x4016
WARNING: *** Your flash chip does not match your flash map ***
>dump()
pinMode(D0, "input_pullup");
pinMode(D4, "input_pullup");
pinMode(D5, "input_pullup");
pinMode(D12, "input_pullup");
pinMode(D13, "input_pullup");
pinMode(D14, "input_pullup");
pinMode(D15, "input_pullup");
=undefined
>
```

Environment variables are as follows: 

```
>process.env
={ 
  "VERSION": "1v85.134", 
  "BUILD_DATE": "May 14 2016", 
  "BUILD_TIME": "15:06:45", 
  "GIT_COMMIT": "498b9d4cc0f1fc5e0886c19a3b84ce64279aaf85", 
  "BOARD": "ESP8266_BOARD", 
  "CHIP": "ESP8266", 
  "CHIP_FAMILY": "ESP8266", 
  "FLASH": 0, "RAM": 81920, 
  "SERIAL": "18fe34e0-6e12", 
  "CONSOLE": "Serial1", 
  "EXPORTS": { "jsvLock": 1075850812, "jsvLockAgainSafe": 1075851056, "jsvUnLoc 
    "jsvMathsOp": 1075867780, "jsvMathsOpSkipNames": 1075869496, "jsvNewFromFlo 
    "jsvNewFromBool": 1075859844, "jsvGetFloat": 1075865728, "jsvGetInteger": 1 
    "jspReplaceWith": 1075881160, "jspeFunctionCall": 1075889400, "jspGetNamedV 
    "jsvNewWithFlags": 1075859208 }
 }
>
``` #

**Comment by gfwilliams** [comment]
Looks like this is dependent on which code is uploaded? Could you provide the code that you uploaded and saved first?

**Comment by ceremcem** [comment]
[app.zip](https://github.com/espruino/Espruino/files/277693/app.zip)

**Comment by tve** [comment]
The basic issue here is either deadlock or watchdog reset. Anything that outputs more than a few KB on the console at once will deadlock because the network code never gets a chance to run (I forget the details). If you only output to serial you end up WDT resetting 'cause the Wifi gets locked out in the busy loop printing.

**Comment by ceremcem** [comment]
Ok, then let me see if I can implement a `dump()` function which will take a break after a few KB and continue later...

**Comment by gfwilliams** [comment]
> which will take a break after a few KB and continue later...

That won't be easy to do - it's called from the interpreter, so the interpreter would have to be able to start again in the same place.

If you have enough RAM you could try `E.dumpStr()` which dumps everything to a string - so you can then choose what you want to do with it - for instance outputting it only every so often.

**Comment by ceremcem** [comment]
I thought I could read the rom manually, part by part, then print it to the console... But this really doesn't hurt as you know the reason and as it's not a bug.
