### ISSUE TITLE
esp8266 wifi.stopAP() fails after initial flash

### ISSUE THREAD

**Issue by tve** [espruino/Espruino#883]
After the initial flashing when Espruino first comes up `wifi.stopAP()` has no effect (the AP stays on). Once the STA has been started or other wifi settings have been changed the AP can be turned off. Looking at the code this seems to be a bug in the Espressif SDK (1.5.X) and is really more of a nuisance than anything else given that after the initial problem the function works fine.

**Comment by MaBecker** [comment]
#857 ;-)

**Comment by tve** [comment]
Duplicate
