### ISSUE TITLE
Long event names don't work

### ISSUE THREAD

**Issue by the1laz** [espruino/Espruino#906]
I don't seem to be able to fire events with names longer than 8 characters. obj.on('presentation') won't fire if I obj.emit('presentation'), but I can call it with obj['#onpresentation']()

I tried shortening the event name until I got to 7 characters, which then worked.

This only seems to be a problem on ESP8266. There was a forum post about long event names a little while ago, not sure if this is related. http://forum.espruino.com/conversations/277524/

**Comment by the1laz** [comment]
I've now found this on an stm32 as well, looks like something I'm doing might be causing this. I'll do some more investigation, but I'm not really sure how to debug it.

**Comment by gfwilliams** [comment]
You'd probably want to check up what's in memory using `trace` - it could be to do with the variable name being long enough that 2 variables are needed for it. If you can reproduce it on a normal Linux compile it'd help for debugging (but on those you could be looking at a significantly longer event name to trigger it)

**Comment by the1laz** [comment]
Thanks, I'll give that a go.

**Comment by tve** [comment]
Given "I've now found this on an stm32 as well" does the esp8266 tag make sense on this issue?

**Comment by gfwilliams** [comment]
oops. Good point :)

**Comment by the1laz** [comment]
Thanks!
