### ISSUE TITLE
[micro:bit] NRF.setName does not exist

### ISSUE THREAD

**Issue by k33g** [espruino/Espruino#907]
Hi 😄 
I'm trying Espruino with a micro:bit, but when I use `NRF.setName` I get an error:

```
Uncaught Error: Function "setName" not found!
 at line 3 col 9
     NRF.setName("@k33g_org :-)");
            ˆ
in function called from system
```

is it about the argument format? 

or something has changed recently (it's my beginning with Espruino)?
thank you

**Comment by gfwilliams** [comment]
Hi - yeah, this is a recent change... setName got moved into setAdvertising. The updated docs are here: https://github.com/espruino/Espruino/blob/master/libs/bluetooth/jswrap_bluetooth.c#L1179-L1229

The docs on the website are for the currently released version of Espruino (1v86 at the mo), but the 'cutting edge' builds (which I guess you're using) can be different... You can build your own documentation, but yes, I'm afraid it's a bit of a faff.
