### ISSUE TITLE
IF statements returning values

### ISSUE THREAD

**Issue by gfwilliams** [espruino/Espruino#909]
http://forum.espruino.com/conversations/291954

Looks like IF statements should return the value of the statement they executed - currently they return undefined

**Comment by muet** [comment]
...the last one, if it is a block?

**Comment by gfwilliams** [comment]
It would seem so, yes... it seems like it'd be a struggle to use it for much (and you should probably use ternary instead) but I guess it's part of the spec so needs implementing :(
