### ISSUE TITLE
save() reports -4 bytes available on nRF51

### ISSUE THREAD

**Issue by ddm** [espruino/Espruino#910]
Tested with the following nRF51 variants (QFN48):

- nRF51422-QFAC (256k Flash & 32k RAM) using a [PCA10028 DK](https://developer.nordicsemi.com/boards/nRF51/pca10028/V1.0.0/images/nRF51_PCA10028_top_large.jpg) (`NRF51822DK=1`)
- nRF51822-QFAA (256k Flash & 16k RAM) using a custom board:
```python
info = {
 'name' : "noho-plug",
 'link' :  [ "https://www.noho.care" ],
 'default_console' : "EV_SERIAL1",
 'default_console_tx' : "D29",
 'default_console_rx' : "D30",
 'default_console_baudrate' : "115200",
 'variables' : 310,
 'binary_name' : 'noho-plug.bin',
 'build' : {
  'defines' : [
     'USE_BLUETOOTH'
   ]
 }
};

chip = {
  'part' : "NRF51822", # QFAA
  'family' : "NRF51",
  'package' : "QFN48",
  'ram' : 16,
  'flash' : 256,
  'speed' : 16,
  'usart' : 1,
  'spi' : 1,
  'i2c' : 0,
  'adc' : 1,
  'dac' : 0,
  'saved_code' : {
    'address' : ((256 - 3) * 1024),
    'page_size' : 1024,
    'pages' : 0,
    'flash_available' : (256 - 108 - 3)
  }
};
```
To reproduce using the PCA10028 development kit:

1. `git clone https://github.com/espruino/Espruino.git && cd Espruino`
2. [`git co 1317aa0`](https://github.com/espruino/Espruino/commit/1317aa087c99e64b463ee0750b1f93eedf02e730)
3. `NRF51822DK=1 RELEASE=1 make`
4. [Flash](http://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.rds%2Fdita%2Frds%2Fdesigns%2Fsmart_remote%2Fsmart_remote_3%2Ffirmware%2Fprog_erase_gostudio.html) `espruino_1v86.1614_nrf51822.hex` to [PCA10028 DK](https://www.nordicsemi.com/eng/Products/nRF51-DK)
5. UART @ 9600 bauds/8 bits/no parity or [nRF UART 2.0 (Android)](https://play.google.com/store/apps/details?id=com.nordicsemi.nrfUARTv2&hl=en)
6. `save() ` ⇒ `ERROR: Too big to save to flash (xxx vs -4 bytes)` regardless of the code.

**Comment by universal** [comment]
I think i had a similar issue playing with a waveshare clone, and still have other issues. I think i fixed the byte issue with a changed config, might have just been pages in the chip section which i changed. I hope i don't forget it tomorrow, i only have the code at my work machine since it is still toying around :-)

**Comment by ddm** [comment]
Funny you mention that: I noticed it works on my custom board (but not the PCA10028) when I just add `-g3` compiler flag. No amount of work on the `saved_code` board config values seem to do any good though.

**Comment by gfwilliams** [comment]
On micro:bit this works I think. Change `pages:0` to `pages:3` in your file -  seems to be a bug in the nRF51DK board file

**Comment by ddm** [comment]
@gfwilliams Thank you for the fix Gordon! I just realised that changing `gcc` flags had nothing to do with me getting it to work: I had set `pages:3` on my custom board too... I guess the nRFTag board should be updated too since it uses the same nRF51822-QFAA variant as the micro:bit and my custom board.
