### ISSUE TITLE
Esp8266 - Makefile needs firmware updated from 1.4 to 1.5

### ISSUE THREAD

**Issue by wilberforce** [espruino/Espruino#912]
github.com/espruino/Espruino/blo­b/master/Makefile#L1927

BOOTLOADER = "$(ESP8266_SDK_ROOT)/bin/boot_v1.4(b1).b­in"
to
BOOTLOADER = "$(ESP8266_SDK_ROOT)/bin/boot_v1.5.bin"

**Comment by wilberforce** [comment]
@tve 

Please can you add the 1.5 bootloader referenced here:
https://github.com/espruino/Espruino/blob/master/.travis.yml#L20

esp_iot_sdk_v1.5.0 (1).tgx 

esp_iot_sdk_v1.5.0 (1)/esp_iot_sdk_v1.5.0/bin/


The Makefile also needs a tweak:
github.com/espruino/Espruino/blo­b/master/Makefile#L1927

BOOTLOADER = "$(ESP8266_SDK_ROOT)/bin/boot_v1.4(b1).b­in"
to
BOOTLOADER = "$(ESP8266_SDK_ROOT)/bin/boot_v1.5.bin"

**Comment by gfwilliams** [comment]
And also the ESP8266 readme

**Comment by wilberforce** [comment]
@tve 
I saw that the http://s3.voneicken.com/esp_iot_sdk_v1.5.4.tgx has the `boot_v1.5.bin`

Are we ready to go to SDK 1.5.4?

https://github.com/espruino/Espruino/pull/924

**Comment by wilberforce** [comment]
The has been superseded by a sdk 2.0 build
