### ISSUE TITLE
fillCircle() Filled circles in Graphics library 

### ISSUE THREAD

**Issue by owenmcateer** [espruino/Espruino#920]
A nice to have addition to the graphics library would be a filled circle _Graphics.fillCircle(x, y, rad)_
Here is my proposed code.

**Comment by gfwilliams** [comment]
Nothing seems to be attached?

Ideally whatever solution there was would use the fillRect call for each scanline (rather than drawPixel)

**Comment by owenmcateer** [comment]
Here is my idea. https://github.com/espruino/Espruino/pull/921
This is un-tested and using _graphicsFillRectDevice()_ may not be the fasted way of doing so.

**Comment by gfwilliams** [comment]
not sure if it's fastest, but it's not bad and a lot quicker than doing it in JS - thanks!
