### ISSUE TITLE
BLE RAM start address incorrect for nRF52

### ISSUE THREAD

**Issue by ddm** [espruino/Espruino#922]
This warning is emitted on the UART when using Espruino (commit 058078f) with the NRF52832DK board:

```
WARNING: BLE RAM start address not correct - is 0x20002600, should be 0x200026e0
```

**Comment by gfwilliams** [comment]
Yeah, this is a result of me adding the ability to add more UUIDs - the RAM requirements changed

**Comment by ddm** [comment]
Right, fixed indeed (just tested it on NRF52832DK)
