### ISSUE TITLE
Bad check in telnetStart for return code from netCreateSocket

### ISSUE THREAD

**Issue by nkolban** [espruino/Espruino#931]
While studying the code, I was looking at the `telnetStart` method contained in `jswrap_telnet.c`.  From what I can see there, it calls `netCreateSocket` and if the return from that is `0`, that is considered a failure.  However my understanding is that a return code of <0 (usually -1) is considered an error.   I am thinking that this is a logic error in the code and would appreciate a new pair of eyes on the consideration.

**Comment by gfwilliams** [comment]
```
  /// if host=0, creates a server otherwise creates a client (and automatically connects). Returns >=0 on success
  int (*createsocket)(struct JsNetwork *net, uint32_t host, unsigned short port);
```

So yeah, this definitely looks like a bug. It should check for `<0`. Thanks!
